import { randomUUID } from 'node:crypto';
import { store } from '../../kernel/store.js';
import { audit } from '../../kernel/audit.js';
import type { EntityRow } from '../../kernel/types.js';

export type PolicyStatus = 'VERIFIED_CURRENT_STATUTE' | 'VERIFIED_CURRENT_RATE' | 'ENTITY_CONFIGURATION_REQUIRED' | 'ESTABLISHMENT_CONFIGURATION_REQUIRED' | 'STATE_RULE_REQUIRED' | 'BUSINESS_MODEL_SIGNOFF_REQUIRED' | 'PROVIDER_EVIDENCE_REQUIRED' | 'AWAITING_NOTIFICATION' | 'LEGAL_EXCEPTION_REVIEW' | 'MANAGEMENT_POLICY' | 'LEGACY_PRE_2026_RULE';
export type RegulatoryPolicy = { id: string; policyKey: string; lawFamily: string; jurisdiction: 'INDIA' | 'STATE'; status: PolicyStatus; effectiveFrom: string; effectiveUntil?: string; rateBps?: number; thresholdPaise?: number; calculationBasis: string; statutoryReference: string; legacyReference?: string; sourceUrl: string; sourceLabel: string; verifiedAt: string; version: string; notes?: string; state?: string; createdAt: string };
export type EntityFinanceProfile = { id: string; legalName?: string; pan?: string; tan?: string; gstRegistrationStatus?: 'Registered' | 'Unregistered'; marketplaceModel?: 'VENDOR_SUPPLIER' | 'PLATFORM_PRINCIPAL'; epfStatus?: 'CoveredGeneral12' | 'CoveredReduced10' | 'NotCovered' | 'Unknown'; esicStatus?: 'Covered' | 'NotCovered' | 'Unknown'; workState?: string; updatedAt: string; updatedBy: string };
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const policyRows = (tenant: string) => store.rowsOf(tenant, 'regulatory_policy').map((row) => row.data as RegulatoryPolicy);
const validDate = (value: string) => DATE.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
const baseline = (): Omit<RegulatoryPolicy, 'id' | 'createdAt'>[] => [
  { policyKey: 'ITA2025_TDS_TRANSITION', lawFamily: 'Income Tax', jurisdiction: 'INDIA', status: 'VERIFIED_CURRENT_STATUTE', effectiveFrom: '2026-04-01', calculationBasis: 'Earlier of credit or payment for non-salary TDS; salary at payment.', statutoryReference: 'Income-tax Act, 2025 section 393', legacyReference: 'Income-tax Act, 1961 TDS sections', sourceUrl: 'https://www.incometax.gov.in/iec/foportal/help/all-topics/e-filing-services/tds-compliance', sourceLabel: 'Income Tax Department — TDS Compliance', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'TDS_CONTRACTOR_RESIDENT', lawFamily: 'Income Tax', jurisdiction: 'INDIA', status: 'VERIFIED_CURRENT_RATE', effectiveFrom: '2026-04-01', rateBps: 100, thresholdPaise: 3_000_000, calculationBasis: 'Resident individual/HUF contractor; annual threshold is separately evaluated. Other recipient rate requires classification.', statutoryReference: 'Income-tax Act, 2025 section 393 table', legacyReference: '194C', sourceUrl: 'https://www.incometax.gov.in/iec/foportal/help/all-topics/e-filing-services/tds-compliance', sourceLabel: 'Income Tax Department — TDS Compliance', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'GST_LAUNDRY_9997_18', lawFamily: 'GST', jurisdiction: 'INDIA', status: 'VERIFIED_CURRENT_RATE', effectiveFrom: '2026-09-03', rateBps: 1800, calculationBasis: 'Laundry/cleaning service supply; tax nature must be resolved from supplier and place of supply facts.', statutoryReference: 'GST service Heading 9997', sourceUrl: 'https://cbic-gst.gov.in/hindi/gst-goods-services-rates.html', sourceLabel: 'CBIC GST Goods and Services Rates', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'SALARY_NEW_REGIME_TY_2026_27', lawFamily: 'Income Tax', jurisdiction: 'INDIA', status: 'VERIFIED_CURRENT_RATE', effectiveFrom: '2026-04-01', calculationBasis: 'New regime slabs, resident rebate up to ₹60,000 where taxable income does not exceed ₹12 lakh; high income requires surcharge review.', statutoryReference: 'Income-tax Act, 2025 section 392', legacyReference: '115BAC / 87A', sourceUrl: 'https://www.incometax.gov.in/iec/foportal/help/all-topics/e-filing-services/itr-2/itr-2-faqs', sourceLabel: 'Income Tax Department — AY 2026-27 rates', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'LABOUR_WAGES_50_PERCENT', lawFamily: 'Labour Code', jurisdiction: 'INDIA', status: 'VERIFIED_CURRENT_STATUTE', effectiveFrom: '2025-11-21', calculationBasis: 'Excess excluded allowance above 50% of remuneration is added back to statutory wages.', statutoryReference: 'Code on Wages, 2019 section 2(y)', sourceUrl: 'https://labour.gov.in/sites/default/files/faqs_on_labour_codes.pdf', sourceLabel: 'Ministry of Labour FAQs', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'EPF_GENERAL_12', lawFamily: 'EPF', jurisdiction: 'INDIA', status: 'ESTABLISHMENT_CONFIGURATION_REQUIRED', effectiveFrom: '2026-09-03', rateBps: 1200, thresholdPaise: 1_500_000, calculationBasis: 'General covered establishment rate; membership, ceiling, higher-wage option and 10% category must be configured.', statutoryReference: 'EPF Scheme contribution framework', sourceUrl: 'https://www.epfindia.gov.in/site_docs/PDFs/MiscPDFs/ContributionRate.pdf', sourceLabel: 'EPFO present contribution rates', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'ESIC_3_25_0_75', lawFamily: 'ESI', jurisdiction: 'INDIA', status: 'ESTABLISHMENT_CONFIGURATION_REQUIRED', effectiveFrom: '2026-09-03', rateBps: 400, thresholdPaise: 2_100_000, calculationBasis: 'Employer 3.25% and employee 0.75% of applicable wages; coverage and daily wage exception must be evaluated.', statutoryReference: 'ESI Central Rules contribution framework', sourceUrl: 'https://esic.gov.in/attachments/publicationfile/79b91f03d8b280e6dc6da3537617ef26.pdf', sourceLabel: 'ESIC at a glance', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'PROFESSIONAL_TAX', lawFamily: 'Professional Tax', jurisdiction: 'STATE', status: 'STATE_RULE_REQUIRED', effectiveFrom: '2026-09-03', calculationBasis: 'State, work location, period, registration and applicable slab are required.', statutoryReference: 'Applicable state law', sourceUrl: 'https://labour.gov.in/', sourceLabel: 'State-specific policy required', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'MARKETPLACE_SUPPLIER_MODEL', lawFamily: 'Marketplace Accounting', jurisdiction: 'INDIA', status: 'BUSINESS_MODEL_SIGNOFF_REQUIRED', effectiveFrom: '2026-09-03', calculationBasis: 'Vendor supplier/intermediary and platform principal models must be selected from actual contracts.', statutoryReference: 'Contractual accounting policy', sourceUrl: 'https://www.icai.org/', sourceLabel: 'Business-model evidence required', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
  { policyKey: 'GIG_WORKER_SOCIAL_SECURITY', lawFamily: 'Labour Code', jurisdiction: 'INDIA', status: 'AWAITING_NOTIFICATION', effectiveFrom: '2026-09-03', calculationBasis: 'Architecture only until an applicable central notification provides the rate.', statutoryReference: 'Code on Social Security, 2020', sourceUrl: 'https://labour.gov.in/', sourceLabel: 'Central notification required', verifiedAt: '2026-09-03', version: 'IND-2026.1' },
];

export function listRegulatoryPolicies(tenant: string, asOf?: string) { const date = asOf || new Date().toISOString().slice(0, 10); if (!validDate(date)) throw new Error('REGULATORY_AS_OF_INVALID'); return policyRows(tenant).filter((policy) => policy.effectiveFrom <= date && (!policy.effectiveUntil || policy.effectiveUntil >= date)).sort((a, b) => a.policyKey.localeCompare(b.policyKey)); }
export function installIndia2026Baseline(tenant: string, actor: string) { const now = new Date().toISOString(); let installed = 0; for (const item of baseline()) { if (policyRows(tenant).some((policy) => policy.policyKey === item.policyKey && policy.version === item.version)) continue; const policy: RegulatoryPolicy = { ...item, id: `reg_${randomUUID()}`, createdAt: now }; const row: EntityRow = { id: policy.id, entity: 'regulatory_policy', tenant, status: 'Active', version: 1, created_by: actor, created_at: now, updated_at: now, data: policy }; store.insertRow(row); installed += 1; } audit(tenant, actor, 'finance:india-2026-policy-baseline-installed', { after: { installed, version: 'IND-2026.1' } }); return { installed, policies: listRegulatoryPolicies(tenant) }; }
export function entityFinanceProfile(tenant: string) { const row = store.rowsOf(tenant, 'finance_entity_profile')[0]; return row?.data as EntityFinanceProfile | undefined; }
export function saveEntityFinanceProfile(tenant: string, actor: string, input: Partial<EntityFinanceProfile>) { const existing = store.rowsOf(tenant, 'finance_entity_profile')[0]; const now = new Date().toISOString(); const record: EntityFinanceProfile = { id: existing?.id || `finance_entity_${store.currentStore(tenant)}`, ...existing?.data, legalName: input.legalName?.trim() || existing?.data.legalName, pan: input.pan?.trim().toUpperCase() || existing?.data.pan, tan: input.tan?.trim().toUpperCase() || existing?.data.tan, gstRegistrationStatus: input.gstRegistrationStatus || existing?.data.gstRegistrationStatus, marketplaceModel: input.marketplaceModel || existing?.data.marketplaceModel, epfStatus: input.epfStatus || existing?.data.epfStatus || 'Unknown', esicStatus: input.esicStatus || existing?.data.esicStatus || 'Unknown', workState: input.workState?.trim() || existing?.data.workState, updatedAt: now, updatedBy: actor }; const row: EntityRow = { id: record.id, entity: 'finance_entity_profile', tenant, status: 'Active', version: (existing?.version || 0) + 1, created_by: existing?.created_by || actor, created_at: existing?.created_at || now, updated_at: now, data: record }; store.updateRow(row); audit(tenant, actor, 'finance:entity-profile-saved', { entity: row.entity, row_id: row.id, after: { legalName: record.legalName, panPresent: Boolean(record.pan), tanPresent: Boolean(record.tan), epfStatus: record.epfStatus, esicStatus: record.esicStatus, workState: record.workState, marketplaceModel: record.marketplaceModel } }); return record; }
export function financePolicyReadiness(tenant: string) { const policies = listRegulatoryPolicies(tenant); const entity = entityFinanceProfile(tenant); const missingEntity = ['legalName', 'pan', 'tan', 'gstRegistrationStatus'].filter((key) => !entity?.[key as keyof EntityFinanceProfile]); const stateRequired = !entity?.workState; const marketplaceRequired = !entity?.marketplaceModel; return { policies, policyCount: policies.length, entity: entity ? { ...entity, pan: entity.pan ? '[configured]' : undefined, tan: entity.tan ? '[configured]' : undefined } : null, checks: { statutoryBaseline: policies.length >= baseline().length, entityConfiguration: missingEntity.length === 0, statePolicy: !stateRequired, marketplaceModel: !marketplaceRequired }, missing: { entity: missingEntity, statePolicy: stateRequired ? ['workState'] : [], marketplace: marketplaceRequired ? ['marketplaceModel'] : [] } }; }
