import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, CircleDollarSign, Landmark, Loader2, ReceiptText, ShieldCheck, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useMemo, useState } from 'react'
import { apiGet } from '@/lib/api'
import { formatINR, localDateKey } from '@/lib/utils'

type Center = any
const palette = ['#2d7b72', '#d3a33f', '#335f72', '#b9654e', '#748f62', '#7665a8', '#83979a', '#d17a72']
const addDays = (date: string, days: number) => { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10) }
const financialYearStart = (date: string) => { const value = new Date(`${date}T00:00:00Z`); return `${value.getUTCMonth() >= 3 ? value.getUTCFullYear() : value.getUTCFullYear() - 1}-04-01` }
function rangeFor(kind: string, now: string) { if (kind === 'today') return { from: now, to: now }; if (kind === '7d') return { from: addDays(now, -6), to: now }; if (kind === '30d') return { from: addDays(now, -29), to: now }; if (kind === 'month') return { from: `${now.slice(0, 7)}-01`, to: now }; if (kind === 'fy') return { from: financialYearStart(now), to: now }; return { from: addDays(now, -29), to: now } }

export default function LaundryFinanceCommandCenter() {
  const today = localDateKey(); const [preset, setPreset] = useState('30d'); const [range, setRange] = useState(() => rangeFor('30d', today))
  const query = useQuery({ queryKey: ['finance-command-center', range.from, range.to], queryFn: () => apiGet<Center>(`/finance/command-center?from=${range.from}&to=${range.to}`) })
  const data = query.data; const current = data?.current; const kpis = current?.kpis
  const rangeLabel = useMemo(() => range.from === range.to ? range.to : `${shortDate(range.from)} – ${shortDate(range.to)}`, [range])
  const selectPreset = (value: string) => { setPreset(value); if (value !== 'custom') setRange(rangeFor(value, today)) }
  if (query.isLoading) return <Loading />
  if (query.error || !data || !current || !kpis) return <Failure message={query.error instanceof Error ? query.error.message : 'The finance command center could not load.'} />
  const waterfall = [{ label: 'Gross revenue', value: kpis.grossRevenue, tone: 'positive' }, { label: 'Discounts', value: -(kpis.grossRevenue - kpis.netRevenue - kpis.refunds), tone: 'negative' }, { label: 'Refunds', value: -kpis.refunds, tone: 'negative' }, { label: 'Direct cost', value: -kpis.directCost, tone: 'negative' }, { label: 'Operating cost', value: -(kpis.expenses - kpis.directCost), tone: 'negative' }, { label: 'EBITDA', value: kpis.ebitda ?? 0, tone: 'result' }]
  return <main className="animate-in fade-in slide-in-from-bottom-2 duration-500">
    <header className="rounded-[28px] border border-[#193b42]/10 bg-[#123039] px-5 py-6 text-white shadow-[0_18px_48px_rgba(18,48,57,.16)] md:px-7"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#9ed9cf]">Executive finance</p><h1 className="mt-2 max-w-2xl font-display text-3xl font-semibold tracking-[-.04em] md:text-4xl">The money behind every cleaned garment.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c7dbd8]">A visual operating view from posted local invoices, payments, expenses, cash movements and settlement evidence. {rangeLabel}.</p></div><div className="flex flex-wrap gap-2"><Link to="/laundry/expenses" className="rounded-xl bg-white/10 px-3 py-2 text-xs font-bold text-white transition hover:bg-white/20">Classify expenses</Link><Link to="/laundry/finance-setup" className="rounded-xl bg-[#e6bc65] px-3 py-2 text-xs font-extrabold text-[#17353c]">Finance setup</Link></div></div><div className="mt-6 flex flex-wrap gap-2 border-t border-white/10 pt-4" aria-label="Finance period"><RangeButton active={preset === 'today'} onClick={() => selectPreset('today')}>Today</RangeButton><RangeButton active={preset === '7d'} onClick={() => selectPreset('7d')}>7 days</RangeButton><RangeButton active={preset === '30d'} onClick={() => selectPreset('30d')}>30 days</RangeButton><RangeButton active={preset === 'month'} onClick={() => selectPreset('month')}>This month</RangeButton><RangeButton active={preset === 'fy'} onClick={() => selectPreset('fy')}>Financial year</RangeButton><RangeButton active={preset === 'custom'} onClick={() => setPreset('custom')}>Custom</RangeButton>{preset === 'custom' ? <span className="flex items-center gap-2"><input aria-label="Finance period start" type="date" value={range.from} onChange={(event) => setRange({ ...range, from: event.target.value })} className="h-8 rounded-lg border border-white/20 bg-white/10 px-2 text-xs text-white"/><span className="text-xs text-[#9ed9cf]">to</span><input aria-label="Finance period end" type="date" value={range.to} onChange={(event) => setRange({ ...range, to: event.target.value })} className="h-8 rounded-lg border border-white/20 bg-white/10 px-2 text-xs text-white"/></span> : null}</div></header>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6"><Metric label="Net revenue" value={formatINR(kpis.netRevenue)} comparison={data.comparisons.netRevenue} icon={CircleDollarSign}/><Metric label="Gross profit" value={maybeMoney(kpis.grossProfit)} hint={metricState(current.classification.complete, 'Classify expenses to calculate')} icon={BarChart3}/><Metric label="EBITDA" value={maybeMoney(kpis.ebitda)} comparison={data.comparisons.ebitda} hint={kpis.ebitdaMarginPercent === null ? 'Management classification required' : `${kpis.ebitdaMarginPercent}% margin`} icon={Landmark}/><Metric label="Cash collected" value={formatINR(kpis.collected)} comparison={data.comparisons.collected} icon={WalletCards}/><Metric label="Receivable" value={formatINR(kpis.outstanding)} hint={kpis.orderCount ? `${formatINR(current.receivables.overdue)} overdue` : 'No invoices in range'} icon={ReceiptText}/><Metric label="Operating cash flow" value={formatINR(kpis.operatingCashFlow)} comparison={data.comparisons.operatingCashFlow} icon={kpis.operatingCashFlow >= 0 ? ArrowUpRight : ArrowDownRight}/></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.8fr)]"><Panel eyebrow="Revenue quality" title="Revenue, discounts and collections" action={<Link to="/laundry/reports" className="text-xs font-bold text-[#277267]">View evidence →</Link>}><div className="h-80"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={current.trend} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id="finance-revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2d7b72" stopOpacity=".34"/><stop offset="1" stopColor="#2d7b72" stopOpacity=".02"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9efec"/><XAxis dataKey="date" tickFormatter={shortDate} tick={{ fontSize: 10, fill: '#718087' }} axisLine={false} tickLine={false}/><YAxis tickFormatter={(value) => compact(value)} tick={{ fontSize: 10, fill: '#718087' }} axisLine={false} tickLine={false}/><Tooltip content={<MoneyTooltip/>}/><Area type="monotone" dataKey="netRevenue" name="Net revenue" stroke="#2d7b72" strokeWidth={2.7} fill="url(#finance-revenue)"/><Area type="monotone" dataKey="collected" name="Cash collected" stroke="#d3a33f" strokeWidth={2} fill="transparent"/><Bar dataKey="discounts" name="Discounts" fill="#b9654e" radius={[4,4,0,0]} barSize={10}/></ComposedChart></ResponsiveContainer></div><ChartLegend rows={[['#2d7b72','Net revenue'],['#d3a33f','Cash collected'],['#b9654e','Discounts']]}/></Panel><Panel eyebrow="Revenue mix" title="Channel contribution"><Donut rows={current.composition.channels}/><Legend rows={current.composition.channels}/><Link to="/laundry/online-orders" className="mt-4 inline-flex text-xs font-bold text-[#277267]">Open online order queue →</Link></Panel></section>
    <section className="mt-5"><Panel eyebrow="Margin bridge" title="From booked service to operating result" action={<span className={current.classification.complete ? 'rounded-full bg-[#eaf3ef] px-2.5 py-1 text-[10px] font-extrabold text-[#32695f]' : 'rounded-full bg-[#fff4dc] px-2.5 py-1 text-[10px] font-extrabold text-[#855815]'}>{current.classification.complete ? 'Management classification active' : `${current.classification.unclassifiedExpenses} expense(s) unclassified`}</span>}>{current.classification.complete ? <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{waterfall.map((row) => <Bridge key={row.label} {...row}/>)}</div> : <div className="flex flex-col gap-3 rounded-2xl border border-dashed border-[#e1c583] bg-[#fffaf0] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-[#593e17]">EBITDA is intentionally withheld.</p><p className="mt-1 text-sm text-[#775919]">Classify existing expenses in Store Expense. The dashboard will calculate the bridge from posted records without guessing cost treatment.</p></div><Link to="/laundry/expenses" className="shrink-0 rounded-xl bg-[#123039] px-3 py-2 text-xs font-bold text-white">Classify now</Link></div>}</Panel></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><Panel eyebrow="Cash movement" title="Cash in → cash out → operating cash"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={current.trend} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e9efec"/><XAxis dataKey="date" tickFormatter={shortDate} tick={{ fontSize: 10, fill: '#718087' }} axisLine={false} tickLine={false}/><YAxis tickFormatter={(value) => compact(value)} tick={{ fontSize: 10, fill: '#718087' }} axisLine={false} tickLine={false}/><Tooltip content={<MoneyTooltip/>}/><Bar dataKey="cashIn" name="Cash in" fill="#2d7b72" radius={[4,4,0,0]}/><Bar dataKey="cashOut" name="Cash out" fill="#b9654e" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><div className="mt-3 grid grid-cols-3 gap-3 border-t border-[#263f44]/8 pt-3 text-sm"><MoneyStat label="Cash in" value={formatINR(kpis.cashIn)}/><MoneyStat label="Cash out" value={formatINR(kpis.cashOut)}/><MoneyStat label="Net cash" value={formatINR(kpis.operatingCashFlow)}/></div></Panel><Panel eyebrow="Receivables" title="What customers still owe"><div className="mt-2 flex items-end justify-between"><div><p className="font-display text-3xl font-semibold text-[#17353c]">{formatINR(kpis.outstanding)}</p><p className="mt-1 text-xs text-[#718087]">{formatINR(current.receivables.overdue)} older than 15 days</p></div><Link to="/laundry/reports" className="text-xs font-bold text-[#277267]">Open balances →</Link></div><div className="mt-6 flex h-12 overflow-hidden rounded-xl bg-[#edf2ef]">{current.receivables.aging.map((row: any, index: number) => <div key={row.label} title={`${row.label}: ${formatINR(row.amount)}`} style={{ width: `${kpis.outstanding ? Math.max(0, row.amount / kpis.outstanding * 100) : 0}%`, background: palette[index] }} className="min-w-0 transition-all"/>)}</div><div className="mt-4 grid grid-cols-2 gap-x-5 gap-y-2 sm:grid-cols-3">{current.receivables.aging.map((row: any, index: number) => <span key={row.label} className="flex justify-between gap-2 text-xs text-[#617178]"><i className="mt-1 h-2.5 w-2.5 rounded-full" style={{backgroundColor:palette[index]}}/>{row.label}<strong className="ml-auto tabular-nums text-[#17353c]">{formatINR(row.amount)}</strong></span>)}</div></Panel></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Panel eyebrow="Cost drivers" title="Expense composition"><Donut rows={current.composition.expense}/><Legend rows={current.composition.expense}/><Link to="/laundry/expenses" className="mt-4 inline-flex text-xs font-bold text-[#277267]">Review expense records →</Link></Panel><Panel eyebrow="Service economics" title="Revenue by service"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={current.composition.services.slice(0,8)} layout="vertical" margin={{top:2,right:8,left:18,bottom:0}}><CartesianGrid horizontal={false} stroke="#e9efec"/><XAxis type="number" tickFormatter={(value) => compact(value)} tick={{fontSize:10,fill:'#718087'}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={110} tick={{fontSize:11,fill:'#52676c'}} axisLine={false} tickLine={false}/><Tooltip content={<MoneyTooltip/>}/><Bar dataKey="amount" name="Service revenue" radius={[0,6,6,0]}>{current.composition.services.slice(0,8).map((_: any,index: number)=><Cell key={index} fill={palette[index % palette.length]}/>)}</Bar></BarChart></ResponsiveContainer></div><p className="mt-3 text-xs text-[#718087]">Processing burden and service contribution remain unavailable until the matching cost drivers are recorded.</p></Panel></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><Panel eyebrow="Marketplace economics" title="Settlement bridge"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Customer paid','customerCollected'],['Vendor gross','vendorGross'],['Commission','commission'],['Vendor due','vendorSettlement']].map(([label,key]) => <MoneyStat key={key} label={label} value={formatINR(current.settlement[`${key}Paise`]?.amount || 0)}/>)}</div><p className="mt-5 rounded-xl bg-[#f4f8f5] p-3 text-xs leading-5 text-[#617178]">Payment fee, withholding and refunds appear only from immutable settlement records. No cloud payout is implied by this view.</p></Panel><Panel eyebrow="Tax and compliance" title="Configuration health"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><MoneyStat label="Taxable sales" value={formatINR(current.tax.taxable)}/><MoneyStat label="CGST" value={formatINR(current.tax.cgst)}/><MoneyStat label="SGST" value={formatINR(current.tax.sgst)}/><MoneyStat label="IGST" value={formatINR(current.tax.igst)}/></div><div className="mt-5 flex items-start gap-3 rounded-xl border border-[#e3ca8e] bg-[#fff9eb] p-3 text-xs leading-5 text-[#775919]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><span>{data.compliance.policyState === 'ENTITY_CONFIGURATION_REQUIRED' ? 'Complete Finance Setup before enabling compliance workflows. No demo PAN, GSTIN or legal identity is substituted.' : 'Compliance balances come from posted ledgers. Filing, payment and IRN statuses still require external evidence.'}</span></div></Panel></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel eyebrow="What needs attention" title="Deterministic executive insights"><div className="space-y-3">{data.insights.map((item: any) => <article key={item.title} className={`rounded-xl border p-4 ${item.tone === 'critical' ? 'border-rose-200 bg-rose-50' : item.tone === 'watch' ? 'border-[#e3ca8e] bg-[#fff9eb]' : 'border-[#cce2d9] bg-[#f2f8f4]'}`}><p className="font-bold text-[#17353c]">{item.title}</p><p className="mt-1 text-sm leading-5 text-[#617178]">{item.detail}</p></article>)}</div></Panel><Panel eyebrow="Data integrity" title="Trust status"><div className="space-y-3"><Status label="Financial source issues" value={current.issues.length ? `${current.issues.length} need review` : 'No period issues'} tone={current.issues.length ? 'watch' : 'good'}/><Status label="Expense classifications" value={current.classification.complete ? 'Complete' : 'Incomplete'} tone={current.classification.complete ? 'good' : 'watch'}/><Status label="Statutory policy baseline" value={data.compliance.readiness.statutoryBaseline ? 'Loaded' : 'Not installed'} tone={data.compliance.readiness.statutoryBaseline ? 'good' : 'watch'}/><Link to="/laundry/finance-setup" className="mt-2 inline-flex text-xs font-bold text-[#277267]">Open finance readiness →</Link></div></Panel></section>
  </main>
}

function RangeButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: string }) { return <button type="button" onClick={onClick} className={`rounded-lg px-2.5 py-1.5 text-xs font-bold transition ${active ? 'bg-white text-[#17353c]' : 'bg-white/10 text-[#d6e6e2] hover:bg-white/20'}`}>{children}</button> }
function Metric({ label, value, hint, comparison, icon: Icon }: { label: string; value: string; hint?: string; comparison?: any; icon: any }) { const improving = comparison ? comparison.change >= 0 : null; return <article className="rounded-[20px] border border-[#263f44]/10 bg-white p-4 shadow-[0_8px_25px_rgba(37,48,43,.04)]"><Icon className="h-4 w-4 text-[#39786f]"/><p className="mt-3 text-[10px] font-extrabold uppercase tracking-[.13em] text-[#718087]">{label}</p><p className="mt-1 truncate font-display text-2xl font-semibold tracking-[-.035em] text-[#17353c]">{value}</p>{comparison ? <p className={`mt-1 flex items-center gap-1 text-[11px] font-bold ${improving ? 'text-[#32695f]' : 'text-[#a24d44]'}`}>{improving ? <ArrowUpRight className="h-3.5 w-3.5"/> : <ArrowDownRight className="h-3.5 w-3.5"/>}{comparison.percent === null ? 'No prior-period baseline' : `${Math.abs(comparison.percent)}% vs prior period`}</p> : <p className="mt-1 truncate text-[11px] text-[#74848a]">{hint || 'Posted finance records'}</p>}</article> }
function Panel({ eyebrow, title, action, children }: any) { return <section className="rounded-[22px] border border-[#263f44]/10 bg-white p-5 shadow-[0_8px_28px_rgba(37,48,43,.04)] md:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#4d8982]">{eyebrow}</p><h2 className="mt-1 font-display text-xl font-semibold tracking-[-.025em] text-[#17353c]">{title}</h2></div>{action}</div><div className="mt-5">{children}</div></section> }
function Donut({ rows }: { rows: any[] }) { const data = rows.length ? rows : [{name:'No records',amount:1}]; return <div className="h-48"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="amount" nameKey="name" innerRadius={52} outerRadius={75} paddingAngle={3}>{data.map((_: any,index: number) => <Cell key={index} fill={rows.length ? palette[index % palette.length] : '#dce7e2'}/>)}</Pie><Tooltip formatter={(value: unknown) => formatINR(Number(value || 0))}/></PieChart></ResponsiveContainer></div> }
function Legend({ rows }: { rows: any[] }) { return <div className="space-y-2">{rows.slice(0,6).map((row,index) => <div key={row.name || row.label} className="flex items-center justify-between gap-3 text-xs"><span className="flex min-w-0 items-center gap-2 text-[#617178]"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{backgroundColor:palette[index % palette.length]}}/><span className="truncate">{row.name || row.label}</span></span><strong className="tabular-nums text-[#17353c]">{formatINR(row.amount)}</strong></div>)}{!rows.length ? <p className="text-sm text-[#718087]">No verified records in this period.</p> : null}</div> }
function Bridge({ label, value, tone }: any) { return <div className={`rounded-xl border p-4 ${tone === 'result' ? 'border-[#285d56] bg-[#123039] text-white' : tone === 'positive' ? 'border-[#cbe1d7] bg-[#f4faf6]' : 'border-[#f0d0c8] bg-[#fff6f4]'}`}><p className={`text-[10px] font-bold uppercase tracking-[.12em] ${tone === 'result' ? 'text-[#a8d8cf]' : 'text-[#718087]'}`}>{label}</p><p className={`mt-2 font-display text-xl font-semibold tabular-nums ${tone === 'result' ? 'text-white' : 'text-[#17353c]'}`}>{formatINR(value)}</p></div> }
function MoneyStat({ label, value }: {label:string;value:string}) { return <div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#718087]">{label}</p><p className="mt-1 text-sm font-bold tabular-nums text-[#17353c]">{value}</p></div> }
function Status({ label, value, tone }: {label:string;value:string;tone:'good'|'watch'}) { return <div className="flex items-center justify-between gap-3 rounded-xl bg-[#fafbf9] p-3 text-sm"><span className="text-[#617178]">{label}</span><span className={tone === 'good' ? 'font-bold text-[#32695f]' : 'font-bold text-[#a16a16]'}>{value}</span></div> }
function MoneyTooltip({ active, payload, label }: any) { if (!active || !payload?.length) return null; return <div className="rounded-xl border border-[#dbe7e1] bg-white px-3 py-2 text-xs shadow-xl"><p className="mb-1 font-bold text-[#17353c]">{label ? shortDate(label) : ''}</p>{payload.map((row:any) => <p key={row.name} className="flex justify-between gap-6 text-[#617178]"><span>{row.name}</span><strong style={{color:row.color}}>{formatINR(Number(row.value || 0))}</strong></p>)}</div> }
function ChartLegend({ rows }: { rows: [string,string][] }) { return <div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[#718087]">{rows.map(([color,label])=><span key={label} className="inline-flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:color}}/>{label}</span>)}</div> }
function Loading() { return <div className="grid min-h-96 place-items-center"><div className="text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-[#39786f]"/><p className="mt-3 text-sm text-[#718087]">Building the finance view from local records…</p></div></div> }
function Failure({ message }: { message:string }) { return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-800"><AlertTriangle className="h-5 w-5"/><p className="mt-3 font-bold">Finance command center unavailable</p><p className="mt-1 text-sm">{message}</p></div> }
function maybeMoney(value: number | null) { return value === null ? 'Not ready' : formatINR(value) }
function metricState(ready: boolean, fallback: string) { return ready ? 'Management classification policy' : fallback }
function compact(value: number) { return value >= 100000 ? `₹${Math.round(value / 100000)}L` : value >= 1000 ? `₹${Math.round(value / 1000)}k` : `₹${Math.round(value)}` }
function shortDate(value: string) { return new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short'}).format(new Date(`${value}T00:00:00`)) }
