import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, Loader2, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { apiGet, apiPost } from '@/lib/api'

type Claim = { id: string; unitId: string; tagCode: string; orderNumber: string; garment: string; state: string; category: string; severity: string; status: string; description: string; openedAt: string; openedBy: string; decision?: string | null; resolutionNote?: string; correction?: { id: string; status: string; summary: string; customerMessage: string; issuedAt: string } | null }
type QualityAnalytics = { totalClaims: number; openClaims: number; resolvedClaims: number; rejectedClaims: number; rewashClaims: number; correctionDocuments: number; averageResolutionHours: number | null; byCategory: Record<string, number>; byDecision: Record<string, number> }
type Session = { user: { roles: string[] } | null }
const categories = ['Stain', 'Damage', 'Missing', 'Rewash', 'Other']
const decisions = ['Rewash', 'Damaged', 'Missing', 'Release', 'Reject']

export default function LaundryQualityClaims() {
  const client = useQueryClient()
  const [unit, setUnit] = useState(''); const [category, setCategory] = useState('Rewash'); const [severity, setSeverity] = useState('Medium'); const [description, setDescription] = useState(''); const [notice, setNotice] = useState('')
  const session = useQuery({ queryKey: ['auth-session'], queryFn: () => apiGet<Session>('/auth/session') })
  const claims = useQuery({ queryKey: ['quality-claims'], queryFn: () => apiGet<Claim[]>('/laundry/quality-claims') })
  const analytics = useQuery({ queryKey: ['quality-analytics'], queryFn: () => apiGet<QualityAnalytics>('/laundry/quality-analytics') })
  const open = useMutation({ mutationFn: () => apiPost<Claim>('/laundry/quality-claims', { garmentUnitId: unit, category, severity, description }), onSuccess: () => { setUnit(''); setDescription(''); setNotice('Quality claim opened for supervisor review.'); client.invalidateQueries({ queryKey: ['quality-claims'] }) } })
  const resolve = useMutation({ mutationFn: ({ id, decision, note }: { id: string; decision: string; note: string }) => apiPost<Claim>(`/laundry/quality-claims/${id}/resolve`, { decision, note }), onSuccess: () => { setNotice('Claim decision recorded in the garment audit trail.'); client.invalidateQueries({ queryKey: ['quality-claims'] }) } })
  const canResolve = Boolean(session.data?.user?.roles.some((role) => role === 'owner' || role === 'processing_staff'))
  if (claims.isLoading) return <div className="grid h-80 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#3a7d78]" /></div>
  if (claims.isError || !claims.data) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-800">Quality claims could not be loaded.</div>
  return <div className="animate-in fade-in slide-in-from-bottom-2 space-y-6 duration-500"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#4d8982]">Quality control</p><h1 className="mt-1 font-serif text-3xl text-[#17353c]">Claims & exceptions</h1><p className="mt-1 max-w-2xl text-sm text-[#718087]">Record stains, damage, missing items, and rewash decisions against the physical garment. Every decision advances the tag lifecycle and remains auditable.</p></div>
    {analytics.data ? <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Open claims', analytics.data.openClaims], ['Rewash loops', analytics.data.rewashClaims], ['Resolved', analytics.data.resolvedClaims], ['Corrections', analytics.data.correctionDocuments], ['Avg resolution', analytics.data.averageResolutionHours === null ? '—' : `${analytics.data.averageResolutionHours}h`]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-[#263f44]/10 bg-white p-4 shadow-[0_8px_28px_rgba(37,48,43,.03)]"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#718087]">{label}</p><p className="mt-1 font-serif text-2xl text-[#17353c]">{value}</p></div>)}</section> : null}
    <section className="rounded-[24px] border border-[#263f44]/10 bg-white p-5 shadow-[0_8px_28px_rgba(37,48,43,.04)]"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-[#c07832]" /><h2 className="font-serif text-xl text-[#17353c]">Open a claim</h2></div><div className="mt-4 grid gap-3 md:grid-cols-4"><label className="text-xs font-bold uppercase tracking-[.12em] text-[#617178] md:col-span-2">Tag or unit code<input value={unit} onChange={(e) => setUnit(e.target.value)} placeholder="TAG-20260829-000001" className="mt-1.5 h-11 w-full rounded-xl border border-[#263f44]/15 px-3 text-sm font-semibold normal-case tracking-normal" /></label><Select label="Category" value={category} onChange={setCategory} options={categories} /><Select label="Severity" value={severity} onChange={setSeverity} options={['Low', 'Medium', 'High', 'Critical']} /><label className="text-xs font-bold uppercase tracking-[.12em] text-[#617178] md:col-span-3">Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What did the operator observe?" className="mt-1.5 min-h-20 w-full rounded-xl border border-[#263f44]/15 px-3 py-2 text-sm font-normal normal-case tracking-normal" /></label><button type="button" disabled={open.isPending || !unit.trim() || description.trim().length < 3} onClick={() => open.mutate()} className="self-end rounded-xl bg-[#123039] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{open.isPending ? 'Opening…' : 'Open claim'}</button></div>{notice ? <p className="mt-3 text-sm font-semibold text-[#2e6a60]"><CheckCircle2 className="mr-1 inline h-4 w-4" />{notice}</p> : null}</section>
    <section className="overflow-hidden rounded-[24px] border border-[#263f44]/10 bg-white shadow-[0_8px_28px_rgba(37,48,43,.04)]"><header className="flex items-center gap-2 border-b border-[#263f44]/10 bg-[#fafaf7] p-5"><ShieldCheck className="h-5 w-5 text-[#39786f]" /><div><h2 className="font-serif text-xl text-[#17353c]">Claim register</h2><p className="text-xs text-[#718087]">{claims.data.filter((claim) => ['Open', 'Under Review'].includes(claim.status)).length} awaiting decision</p></div></header>{claims.data.length ? <div className="divide-y divide-[#263f44]/8">{claims.data.map((claim) => <ClaimRow key={claim.id} claim={claim} canResolve={canResolve} pending={resolve.isPending} onResolve={(decision, note) => resolve.mutate({ id: claim.id, decision, note })} />)}</div> : <div className="p-14 text-center text-sm text-[#718087]">No quality claims have been recorded.</div>}</section>
  </div>
}
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="text-xs font-bold uppercase tracking-[.12em] text-[#617178]">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm font-medium normal-case tracking-normal">{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
function ClaimRow({ claim, canResolve, pending, onResolve }: { claim: Claim; canResolve: boolean; pending: boolean; onResolve: (decision: string, note: string) => void }) { const [decision, setDecision] = useState('Rewash'); const [note, setNote] = useState(''); const active = ['Open', 'Under Review'].includes(claim.status); return <article className="p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-[#215861]">{claim.category} · {claim.garment}</p><span className="rounded-full bg-[#fff2ce] px-2 py-0.5 text-[10px] font-bold uppercase tracking-[.1em] text-[#855815]">{claim.severity}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-[.1em] ${active ? 'bg-rose-50 text-rose-700' : 'bg-[#eaf3ef] text-[#2e6a60]'}`}>{claim.status}</span></div><p className="mt-1 text-xs text-[#819095]">{claim.orderNumber} · <span className="font-mono">{claim.tagCode}</span> · state {claim.state} · opened by {claim.openedBy}</p><p className="mt-2 max-w-3xl text-sm text-[#52676b]">{claim.description}</p>{claim.resolutionNote ? <p className="mt-1 text-xs text-[#718087]">Decision: {claim.decision} · {claim.resolutionNote}</p> : null}{claim.correction ? <div className="mt-3 max-w-3xl rounded-xl border border-[#39786f]/20 bg-[#eaf3ef] p-3"><p className="text-xs font-bold text-[#2e6a60]">Customer correction issued · {claim.correction.id}</p><p className="mt-1 text-xs leading-5 text-[#52676b]">{claim.correction.customerMessage}</p></div> : null}</div>{active && canResolve ? <div className="flex w-full flex-col gap-2 lg:w-80"><div className="flex gap-2"><select aria-label={`Resolution decision for ${claim.tagCode}`} value={decision} onChange={(e) => setDecision(e.target.value)} className="h-10 flex-1 rounded-lg border border-[#263f44]/15 px-2 text-xs">{decisions.map((item) => <option key={item}>{item}</option>)}</select><button type="button" disabled={pending || note.trim().length < 3} onClick={() => onResolve(decision, note)} className="rounded-lg bg-[#3a7d78] px-3 text-xs font-bold text-white disabled:opacity-50">Resolve</button></div><input value={note} onChange={(e) => setNote(e.target.value)} placeholder="Required resolution note" className="h-9 rounded-lg border border-[#263f44]/15 px-2 text-xs" /></div> : null}</div></article> }
