import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, BadgeCheck, Building2, CheckCircle2, Landmark, Loader2, Save, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { apiGet, apiPost, apiPut } from '@/lib/api'
import { formatINR } from '@/lib/utils'
import VisualLoadingState from '@/components/laundry/VisualLoadingState'

type FinanceProfile = { legalName?: string; pan?: string; tan?: string; gstRegistrationStatus?: 'Registered' | 'Unregistered'; marketplaceModel?: 'VENDOR_SUPPLIER' | 'PLATFORM_PRINCIPAL'; epfStatus?: 'CoveredGeneral12' | 'CoveredReduced10' | 'NotCovered' | 'Unknown'; esicStatus?: 'Covered' | 'NotCovered' | 'Unknown'; workState?: string; code?: string }
type TaxProfile = { legalName?: string; tradeName?: string; address?: string; stateCode?: string; pincode?: string; registrationStatus?: 'Registered' | 'Unregistered'; gstin?: string; invoiceSeries?: string; einvoiceState?: string; code?: string }
type RegulatoryPolicy = { id: string; policyKey: string; lawFamily: string; status: string; effectiveFrom: string; rateBps?: number; thresholdPaise?: number; sourceLabel: string; legacyReference?: string }
type Readiness = { policyCount: number; policies?: RegulatoryPolicy[]; checks: { statutoryBaseline: boolean; entityConfiguration: boolean; statePolicy: boolean; marketplaceModel: boolean }; missing: { entity: string[]; statePolicy: string[]; marketplace: string[] } }
type Preview = { status: string; reason?: string; grossEarningsPaise?: number; statutoryWagesPaise?: number; netPayablePaise?: number; employerPayrollCostPaise?: number; employeeDeductions?: { epfPaise: number; esiPaise: number; professionalTaxPaise: number; tdsPaise: number; totalPaise: number }; employerCosts?: { epfPaise: number; esiPaise: number; totalPaise: number } }
const money = (paise?: number) => formatINR((paise || 0) / 100)

export default function LaundryFinanceSetup() {
  const client = useQueryClient(); const profile = useQuery({ queryKey: ['finance-entity-profile'], queryFn: () => apiGet<FinanceProfile>('/finance/entity-profile') }); const tax = useQuery({ queryKey: ['finance-tax-profile'], queryFn: () => apiGet<TaxProfile>('/gst/tax-profile') }); const readiness = useQuery({ queryKey: ['finance-readiness'], queryFn: () => apiGet<Readiness>('/finance/readiness') })
  const [entity, setEntity] = useState<FinanceProfile>({ epfStatus: 'Unknown', esicStatus: 'Unknown', gstRegistrationStatus: 'Unregistered' }); const [taxProfile, setTaxProfile] = useState<TaxProfile>({ registrationStatus: 'Unregistered', einvoiceState: 'NotConfigured' }); const [scenario, setScenario] = useState({ basic: '0', allowances: '0', dailyWage: '0', pt: '0' })
  useEffect(() => { if (profile.data && !profile.data.code) setEntity((value) => ({ ...value, ...profile.data })); }, [profile.data]); useEffect(() => { if (tax.data && !tax.data.code) setTaxProfile((value) => ({ ...value, ...tax.data })); }, [tax.data])
  const saveEntity = useMutation({ mutationFn: () => apiPut('/finance/entity-profile', entity), onSuccess: () => { client.invalidateQueries({ queryKey: ['finance-entity-profile'] }); client.invalidateQueries({ queryKey: ['finance-readiness'] }); client.invalidateQueries({ queryKey: ['laundry-management-snapshot'] }) } })
  const installPolicies = useMutation({ mutationFn: () => apiPost('/finance/regulatory-policies/install-india-2026', {}), onSuccess: () => { client.invalidateQueries({ queryKey: ['finance-readiness'] }); client.invalidateQueries({ queryKey: ['finance-command-center'] }) } })
  const saveTax = useMutation({ mutationFn: () => apiPut('/gst/tax-profile', { ...taxProfile, legalName: taxProfile.legalName || entity.legalName || '' }), onSuccess: () => { client.invalidateQueries({ queryKey: ['finance-tax-profile'] }); client.invalidateQueries({ queryKey: ['finance-readiness'] }) } })
  const preview = useMutation({ mutationFn: () => apiPost<Preview>('/finance/payroll-preview', { components: [{ name: 'Basic pay', amountPaise: Math.round(Number(scenario.basic || 0) * 100), statutoryWage: true, taxable: true, kind: 'earning' }, { name: 'Allowances', amountPaise: Math.round(Number(scenario.allowances || 0) * 100), statutoryWage: false, taxable: true, kind: 'earning' }], policy: { epfStatus: entity.epfStatus || 'Unknown', esicStatus: entity.esicStatus || 'Unknown', taxRegime: 'NEW_2026', dailyWagePaise: Math.round(Number(scenario.dailyWage || 0) * 100), professionalTaxPaise: Math.round(Number(scenario.pt || 0) * 100), remainingPeriods: 12 } }) })
  if (profile.isLoading || tax.isLoading || readiness.isLoading) return <VisualLoadingState title="Preparing finance setup" detail="Reading entity, tax profile and compliance readiness without applying demo defaults." />
  return <div className="animate-in fade-in slide-in-from-bottom-2 space-y-6 duration-500"><header><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#4d8982]">Finance setup</p><h1 className="mt-1 font-display text-3xl font-semibold tracking-[-.035em] text-[#17353c]">Configure your own legal and statutory reality.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#617178]">These are owner-only, store-scoped inputs. Epic Laundry does not substitute sample PAN, TAN, GSTIN, state rules or employer coverage when they are missing.</p></header>
    <ReadinessStrip readiness={readiness.data} />
  <Card icon={ShieldCheck} eyebrow="Policy evidence" title="Versioned India rulebook"><div className="flex flex-col gap-3 rounded-xl border border-[#dbe7e1] bg-[#f7faf7] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-[#17353c]">{readiness.data?.policyCount || 0} policy records installed</p><p className="mt-1 text-xs leading-5 text-[#718087]">Rules are effective-dated and historical transactions retain their policy version. Installing this baseline does not activate registrations or file a return.</p></div><button type="button" disabled={installPolicies.isPending || readiness.data?.checks.statutoryBaseline} onClick={() => installPolicies.mutate()} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-[#123039] px-3 py-2.5 text-xs font-bold text-white disabled:opacity-50"><ShieldCheck className="h-4 w-4"/>{readiness.data?.checks.statutoryBaseline ? 'Baseline installed' : installPolicies.isPending ? 'Installing…' : 'Install verified baseline'}</button></div><div className="mt-4 grid gap-2 md:grid-cols-2">{(readiness.data?.policies || []).map((policy) => <div key={policy.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#263f44]/8 bg-white p-3"><div className="min-w-0"><p className="truncate text-xs font-bold text-[#17353c]">{policy.policyKey}</p><p className="mt-1 truncate text-[10px] text-[#718087]">{policy.sourceLabel} · from {policy.effectiveFrom}{policy.legacyReference ? ` · legacy ${policy.legacyReference}` : ''}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-extrabold uppercase ${policy.status.startsWith('VERIFIED') ? 'bg-[#eaf3ef] text-[#32695f]' : policy.status === 'AWAITING_NOTIFICATION' ? 'bg-[#f0ebff] text-[#665390]' : 'bg-[#fff4dc] text-[#855815]'}`}>{policy.status.replace(/_/g, ' ')}</span></div>)}</div>{installPolicies.error ? <ErrorNotice error={installPolicies.error} /> : null}</Card>
    <section className="grid gap-5 xl:grid-cols-2"><Card icon={Building2} eyebrow="Step 1 · entity" title="Legal entity & establishment"><form onSubmit={(event) => { event.preventDefault(); saveEntity.mutate() }} className="mt-5 grid gap-3 md:grid-cols-2"><Field label="Legal entity name" required value={entity.legalName || ''} onChange={(legalName) => setEntity({ ...entity, legalName })} /><Field label="PAN" placeholder="ABCDE1234F" value={entity.pan || ''} onChange={(pan) => setEntity({ ...entity, pan: pan.toUpperCase() })} /><Field label="TAN" placeholder="ABCD12345E" value={entity.tan || ''} onChange={(tan) => setEntity({ ...entity, tan: tan.toUpperCase() })} /><Select label="GST registration" value={entity.gstRegistrationStatus || 'Unregistered'} onChange={(gstRegistrationStatus) => setEntity({ ...entity, gstRegistrationStatus: gstRegistrationStatus as FinanceProfile['gstRegistrationStatus'] })} options={[['Unregistered', 'Unregistered / not liable'], ['Registered', 'Registered']]}/><Field label="Payroll work state" placeholder="e.g. West Bengal" value={entity.workState || ''} onChange={(workState) => setEntity({ ...entity, workState })} /><Select label="EPF establishment status" value={entity.epfStatus || 'Unknown'} onChange={(epfStatus) => setEntity({ ...entity, epfStatus: epfStatus as FinanceProfile['epfStatus'] })} options={[['Unknown', 'Not yet assessed'], ['CoveredGeneral12', 'Covered · general 12%'], ['CoveredReduced10', 'Covered · reduced 10%'], ['NotCovered', 'Not covered']]}/><Select label="ESIC establishment status" value={entity.esicStatus || 'Unknown'} onChange={(esicStatus) => setEntity({ ...entity, esicStatus: esicStatus as FinanceProfile['esicStatus'] })} options={[['Unknown', 'Not yet assessed'], ['Covered', 'Covered'], ['NotCovered', 'Not covered']]}/><Select label="Marketplace business model" value={entity.marketplaceModel || ''} onChange={(marketplaceModel) => setEntity({ ...entity, marketplaceModel: marketplaceModel as FinanceProfile['marketplaceModel'] })} options={[['', 'Not configured'], ['VENDOR_SUPPLIER', 'Vendor is supplier / Epic intermediary'], ['PLATFORM_PRINCIPAL', 'Epic platform is principal']]}/><p className="md:col-span-2 text-xs leading-5 text-[#718087]">Select coverage only after confirming your establishment’s actual registration and applicability. The configuration never makes a filing or a payment.</p><SaveButton pending={saveEntity.isPending} label="Save entity & establishment" />{saveEntity.error ? <ErrorNotice error={saveEntity.error} /> : null}</form></Card>
      <Card icon={Landmark} eyebrow="Step 2 · GST" title="Supplier tax registration"><form onSubmit={(event) => { event.preventDefault(); saveTax.mutate() }} className="mt-5 grid gap-3 md:grid-cols-2"><Field label="Trade name" value={taxProfile.tradeName || ''} onChange={(tradeName) => setTaxProfile({ ...taxProfile, tradeName })}/><Field label="GSTIN" placeholder="15-character GSTIN" value={taxProfile.gstin || ''} onChange={(gstin) => setTaxProfile({ ...taxProfile, gstin: gstin.toUpperCase() })}/><Field label="Registered address" required value={taxProfile.address || ''} onChange={(address) => setTaxProfile({ ...taxProfile, address })}/><Field label="State code" required placeholder="e.g. 19" value={taxProfile.stateCode || ''} onChange={(stateCode) => setTaxProfile({ ...taxProfile, stateCode })}/><Field label="Pincode" required value={taxProfile.pincode || ''} onChange={(pincode) => setTaxProfile({ ...taxProfile, pincode })}/><Field label="Invoice series" value={taxProfile.invoiceSeries || ''} onChange={(invoiceSeries) => setTaxProfile({ ...taxProfile, invoiceSeries })}/><Select label="Registration state" value={taxProfile.registrationStatus || 'Unregistered'} onChange={(registrationStatus) => setTaxProfile({ ...taxProfile, registrationStatus: registrationStatus as TaxProfile['registrationStatus'] })} options={[['Unregistered','Unregistered'],['Registered','Registered']]}/><Select label="E-invoice environment" value={taxProfile.einvoiceState || 'NotConfigured'} onChange={(einvoiceState) => setTaxProfile({ ...taxProfile, einvoiceState })} options={[['NotConfigured','Not configured'],['NotApplicable','Not applicable'],['Sandbox','Sandbox'],['Ready','Ready']]}/><p className="md:col-span-2 text-xs leading-5 text-[#718087]">A saved GSTIN enables configuration only. An IRN, acknowledgement and signed e-invoice QR still require real provider/IRP evidence.</p><SaveButton pending={saveTax.isPending} label="Save GST registration" />{saveTax.error ? <ErrorNotice error={saveTax.error} /> : null}</form></Card></section>
    <Card icon={ShieldCheck} eyebrow="Scenario calculator" title="Payroll preview — fixed scale"><div className="mt-5 grid gap-3 md:grid-cols-4"><Money label="Monthly basic pay" value={scenario.basic} onChange={(basic) => setScenario({ ...scenario, basic })}/><Money label="Monthly allowances" value={scenario.allowances} onChange={(allowances) => setScenario({ ...scenario, allowances })}/><Money label="Daily wage" value={scenario.dailyWage} onChange={(dailyWage) => setScenario({ ...scenario, dailyWage })}/><Money label="Professional Tax" value={scenario.pt} onChange={(pt) => setScenario({ ...scenario, pt })}/></div><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" onClick={() => preview.mutate()} disabled={preview.isPending} className="inline-flex items-center gap-2 rounded-xl bg-[#123039] px-4 py-2.5 text-sm font-bold text-white"><BadgeCheck className="h-4 w-4" />{preview.isPending ? 'Calculating…' : 'Calculate scenario'}</button><p className="text-xs text-[#718087]">New-regime TY 2026–27 preview. It is not a payslip or filing.</p></div>{preview.data ? <PreviewPanel preview={preview.data} /> : null}{preview.error ? <ErrorNotice error={preview.error} /> : null}</Card>
  </div>
}
function Card({ icon: Icon, eyebrow, title, children }: { icon: typeof Building2; eyebrow: string; title: string; children: React.ReactNode }) { return <section className="rounded-[24px] border border-[#263f44]/10 bg-white p-5 shadow-[0_8px_28px_rgba(37,48,43,.04)]"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf3ef] text-[#39786f]"><Icon className="h-5 w-5"/></span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#4d8982]">{eyebrow}</p><h2 className="mt-1 font-display text-xl font-semibold text-[#17353c]">{title}</h2></div></div>{children}</section> }
function Field({ label, value, onChange, required, placeholder }: { label: string; value: string; onChange: (v: string) => void; required?: boolean; placeholder?: string }) { return <label className="text-xs font-bold text-[#617178]">{label}<input required={required} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm font-medium outline-none focus:ring-2 focus:ring-[#3a7d78]"/></label> }
function Money({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <label className="text-xs font-bold text-[#617178]">{label}<input min="0" step="0.01" type="number" value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm font-medium outline-none focus:ring-2 focus:ring-[#3a7d78]"/></label> }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: Array<[string,string]> }) { return <label className="text-xs font-bold text-[#617178]">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm font-medium outline-none focus:ring-2 focus:ring-[#3a7d78]">{options.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label> }
function SaveButton({ pending, label }: { pending: boolean; label: string }) { return <button disabled={pending} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#3a7d78] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{pending ? 'Saving…' : label}</button> }
function ErrorNotice({ error }: { error: unknown }) { return <p className="md:col-span-2 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error instanceof Error ? error.message : 'The configuration could not be saved.'}</p> }
function ReadinessStrip({ readiness }: { readiness?: Readiness }) { if (!readiness) return null; const checks = [['Policy baseline', readiness.checks.statutoryBaseline], ['Entity', readiness.checks.entityConfiguration], ['Work state', readiness.checks.statePolicy], ['Marketplace model', readiness.checks.marketplaceModel]]; return <section className="flex flex-wrap gap-2 rounded-2xl border border-[#d5e6dd] bg-[#f4faf5] p-3">{checks.map(([label, ready]) => <span key={String(label)} className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ${ready ? 'bg-[#dcefe5] text-[#32695f]' : 'bg-[#fff1cf] text-[#855815]'}`}>{ready ? <CheckCircle2 className="h-3.5 w-3.5"/> : <AlertTriangle className="h-3.5 w-3.5"/>}{label}: {ready ? 'ready' : 'input needed'}</span>)}</section> }
function PreviewPanel({ preview }: { preview: Preview }) { if (preview.status !== 'CALCULATED') return <div className="mt-5 rounded-xl border border-[#e2c482]/45 bg-[#fff8e8] p-4 text-sm text-[#775919]"><strong>{preview.status}</strong><p className="mt-1">{preview.reason}</p></div>; return <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Mini label="Gross earnings" value={money(preview.grossEarningsPaise)}/><Mini label="Statutory wages" value={money(preview.statutoryWagesPaise)}/><Mini label="Net payable" value={money(preview.netPayablePaise)}/><Mini label="Employer payroll cost" value={money(preview.employerPayrollCostPaise)}/><div className="sm:col-span-2 xl:col-span-4 rounded-xl bg-[#f7f8f5] p-3 text-xs text-[#617178]">Employee deductions: EPF {money(preview.employeeDeductions?.epfPaise)} · ESI {money(preview.employeeDeductions?.esiPaise)} · PT {money(preview.employeeDeductions?.professionalTaxPaise)} · planned TDS {money(preview.employeeDeductions?.tdsPaise)}. Employer statutory cost: EPF {money(preview.employerCosts?.epfPaise)} · ESI {money(preview.employerCosts?.esiPaise)}.</div></div> }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#263f44]/10 bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#718087]">{label}</p><p className="mt-1 font-display text-lg font-semibold text-[#17353c]">{value}</p></div> }
