import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronRight, Loader2, Search, Tag, Truck, X } from 'lucide-react'
import { useState } from 'react'
import { apiGet, apiPost } from '@/lib/api'
import { nextLaundryState, stateTone, type LaundryOrder, type LaundryState } from '@/lib/laundry'
import { cn, formatINR } from '@/lib/utils'

const states: Array<LaundryState | 'all'> = ['all', 'Booked', 'Picked Up', 'In Process', 'Ready', 'Out for Delivery', 'Delivered', 'Cancelled']

export default function LaundryOrders() {
  const queryClient = useQueryClient()
  const [search, setSearch] = useState('')
  const [state, setState] = useState<LaundryState | 'all'>('all')
  const [selected, setSelected] = useState<string | null>(null)
  const ordersQuery = useQuery({ queryKey: ['laundry-orders', search, state], queryFn: () => apiGet<LaundryOrder[]>(`/laundry/orders?search=${encodeURIComponent(search)}${state === 'all' ? '' : `&state=${encodeURIComponent(state)}`}`) })
  const detailQuery = useQuery({ queryKey: ['laundry-order', selected], queryFn: () => apiGet<LaundryOrder & { timeline: Array<{ id: string; ts: string; action: string }> }>(`/laundry/orders/${selected}`), enabled: Boolean(selected) })
  const transition = useMutation({ mutationFn: ({ id, next }: { id: string; next: LaundryState }) => apiPost<LaundryOrder>(`/laundry/orders/${id}/transition`, { state: next }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['laundry-orders'] }); queryClient.invalidateQueries({ queryKey: ['laundry-order'] }); queryClient.invalidateQueries({ queryKey: ['laundry-dashboard'] }) } })

  return <div className="animate-in fade-in slide-in-from-bottom-2 duration-500"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#4d8982]">Operations</p><h1 className="mt-1 font-serif text-3xl text-[#17353c]">Store orders</h1><p className="mt-1 text-sm text-[#718087]">Search, inspect, and move orders through the laundry floor.</p></div><div className="rounded-xl border border-[#6ba39a]/25 bg-[#eef7f2] px-3 py-2 text-sm text-[#32695f]"><span className="font-bold">{ordersQuery.data?.length || 0}</span> matching orders</div></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_370px]"><section className="overflow-hidden rounded-[22px] border border-[#263f44]/10 bg-white shadow-[0_8px_28px_rgba(37,48,43,.04)]"><div className="flex flex-col gap-3 border-b border-[#263f44]/10 p-4 md:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#7e8d90]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Order no, invoice, customer or phone" className="h-10 w-full rounded-xl border border-[#263f44]/15 bg-[#fbfbf9] pl-9 pr-3 text-sm outline-none focus:border-[#438b82]" /></div><select value={state} onChange={(event) => setState(event.target.value as LaundryState | 'all')} className="h-10 rounded-xl border border-[#263f44]/15 bg-[#fbfbf9] px-3 text-sm outline-none focus:border-[#438b82]">{states.map((option) => <option key={option} value={option}>{option === 'all' ? 'All statuses' : option}</option>)}</select></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-[#fafaf7] text-[10px] font-bold uppercase tracking-[.14em] text-[#718087]"><tr><th className="px-5 py-3">Invoice / order</th><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Dates</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody>{ordersQuery.isLoading ? <tr><td colSpan={6} className="py-16 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-[#3a7d78]" /></td></tr> : ordersQuery.data?.length ? ordersQuery.data.map((order) => { const next = nextLaundryState[order.state]; return <tr key={order.id} className={cn('border-t border-[#263f44]/8 transition hover:bg-[#f7f8f4]', selected === order.id && 'bg-[#eff7f3]')}><td className="cursor-pointer px-5 py-4" onClick={() => setSelected(order.id)}><span className="block font-bold text-[#205660]">{order.invoiceNumber || '—'}</span><span className="text-xs text-[#718087]">{order.orderNumber} · {order.itemCount} items</span></td><td className="cursor-pointer px-3 py-4" onClick={() => setSelected(order.id)}><span className="block font-medium">{order.customer.name}</span><span className="text-xs text-[#718087]">{order.customer.phone}</span></td><td className="cursor-pointer px-3 py-4 text-xs text-[#617178]" onClick={() => setSelected(order.id)}><span className="block">Booked {date(order.orderDate)}</span><span className="mt-1 block">Due {date(order.expectedDeliveryDate)}</span></td><td className="px-3 py-4 font-bold tabular-nums">{formatINR(order.grandTotal)}</td><td className="px-3 py-4"><StatePill state={order.state} /></td><td className="px-5 py-4 text-right">{next ? <button disabled={transition.isPending} onClick={() => transition.mutate({ id: order.id, next })} className="inline-flex items-center gap-1 rounded-lg bg-[#123039] px-2.5 py-1.5 text-xs font-bold text-white hover:bg-[#1d4a53]">{next}<ChevronRight className="h-3.5 w-3.5" /></button> : <button onClick={() => setSelected(order.id)} className="text-xs font-bold text-[#39786f]">View</button>}</td></tr> }) : <tr><td colSpan={6} className="py-16 text-center text-[#718087]">No orders match this view.</td></tr>}</tbody></table></div></section>
      <OrderDetail order={detailQuery.data} loading={detailQuery.isLoading} onClose={() => setSelected(null)} /></div></div>
}

function OrderDetail({ order, loading, onClose }: { order?: LaundryOrder & { timeline: Array<{ id: string; ts: string; action: string }> }; loading: boolean; onClose: () => void }) { if (!order && !loading) return <aside className="rounded-[22px] border border-dashed border-[#99afa8] bg-[#fbfcf8] p-6 text-center text-sm text-[#718087]"><Tag className="mx-auto mb-3 h-5 w-5 text-[#55938a]" />Select an order to review its garments, payment and audit trail.</aside>; if (loading || !order) return <aside className="grid h-80 place-items-center rounded-[22px] border border-[#263f44]/10 bg-white"><Loader2 className="h-5 w-5 animate-spin text-[#3a7d78]" /></aside>; return <aside className="h-fit rounded-[22px] border border-[#263f44]/10 bg-[#fffdf8] p-5 shadow-[0_8px_28px_rgba(37,48,43,.05)] xl:sticky xl:top-24"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#4d8982]">Order work card</p><h2 className="mt-1 font-serif text-xl text-[#17353c]">{order.orderNumber}</h2></div><button onClick={onClose} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-[#f0eee9]" aria-label="Close order details"><X className="h-4 w-4" /></button></div><div className="mt-4 flex items-center justify-between rounded-xl bg-white p-3"><div><p className="font-semibold">{order.customer.name}</p><p className="text-xs text-[#718087]">{order.customer.phone}</p></div><StatePill state={order.state} /></div><div className="mt-4 space-y-2">{order.items.map((item, index) => <div key={`${item.garmentName}:${index}`} className="flex justify-between rounded-xl border border-[#263f44]/8 bg-white p-3 text-sm"><span><span className="block font-medium">{item.garmentName}</span><span className="text-xs text-[#718087]">{item.serviceName} · {item.qty} {item.unit.toLowerCase()}</span></span><span className="font-bold tabular-nums">{formatINR(item.amount)}</span></div>)}</div><div className="mt-4 flex justify-between border-t border-[#263f44]/10 pt-4"><span className="text-sm text-[#617178]">{order.paymentStatus} · {order.paymentMode}</span><span className="font-serif text-xl">{formatINR(order.grandTotal)}</span></div><div className="mt-5 border-t border-[#263f44]/10 pt-4"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#648077]">Timeline</p><div className="mt-3 space-y-3">{order.timeline.map((entry) => <div key={entry.id} className="flex gap-2 text-xs"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#65a298]" /><span><span className="font-semibold text-[#40565a]">{entry.action.replace('laundry:', '').replace(':', ' ')}</span><span className="block text-[#819094]">{new Date(entry.ts).toLocaleString('en-IN')}</span></span></div>)}</div></div><div className="mt-5 rounded-xl bg-[#eaf3ef] p-3 text-xs text-[#32695f]"><Truck className="mr-1.5 inline h-4 w-4" />{order.fulfillmentMode} · delivery due {date(order.expectedDeliveryDate)}</div></aside> }
function StatePill({ state }: { state: LaundryState }) { return <span className={cn('inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-bold ring-1 ring-inset', stateTone[state])}>{state}</span> }
function date(value: string) { return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short' }).format(new Date(`${value}T00:00:00`)) }
