import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, Download, FileSpreadsheet, Loader2, Upload, UsersRound } from 'lucide-react'
import { useState } from 'react'
import { apiGet, apiPost } from '@/lib/api'

type ImportMode = 'customers' | 'prices'
type ImportRow = Record<string, string | number>
type ImportResult = { created: number; updated: number; skipped: number; errors: Array<{ row: number; message: string }> }
type ImportJob = { id: string; importType: ImportMode; status: string; totalRows: number; createdRows: number; updatedRows: number; skippedRows: number; errors: Array<{ row: number; message: string }>; completedAt: string; actor: string }

const CUSTOMER_TEMPLATE = [
  ['Customer Name', 'Phone', 'Email', 'Address'],
  ['Priya Verma', '9876543210', 'priya@example.com', '42 Lake Road, Bengaluru'],
]
const PRICE_TEMPLATE = [
  ['Garment', 'Category', 'Service', 'Rate', 'Unit', 'HSN', 'GST Rate', 'Customer Phone'],
  ['Blazer', "Men's Wear", 'Dry Cleaning', 450, 'Piece', '9997', 0, ''],
]

export default function LaundryImport({ mode }: { mode: ImportMode }) {
  const client = useQueryClient()
  const [rows, setRows] = useState<ImportRow[]>([])
  const [fileName, setFileName] = useState('')
  const [parseError, setParseError] = useState('')
  const [result, setResult] = useState<ImportResult | null>(null)
  const label = mode === 'customers' ? 'Import customers' : 'Import garment price'
  const jobs = useQuery({ queryKey: ['laundry-import-jobs', mode], queryFn: () => apiGet<ImportJob[]>(`/laundry/import/jobs?type=${mode}`) })
  const mutation = useMutation({
    mutationFn: (payload: ImportRow[]) => apiPost<ImportResult>(`/laundry/import/${mode}`, { rows: payload }),
    onSuccess: (next) => {
      setResult(next)
      client.invalidateQueries({ queryKey: ['laundry-catalogue'] })
      client.invalidateQueries({ queryKey: ['laundry-customers'] })
      client.invalidateQueries({ queryKey: ['laundry-dashboard'] })
      client.invalidateQueries({ queryKey: ['laundry-import-jobs', mode] })
    },
  })

  async function handleFile(file: File) {
    setParseError(''); setResult(null); setRows([]); setFileName(file.name)
    try {
      const sourceRows = await readSpreadsheet(file)
      const parsed = sourceRows.map((row) => mode === 'customers' ? customerRow(row) : priceRow(row)).filter((row) => Object.values(row).some((value) => String(value).trim()))
      if (parsed.length === 0) throw new Error('No data rows were found. Use the downloaded template headers.')
      if (parsed.length > 2_000) throw new Error('A maximum of 2,000 rows can be imported at one time.')
      setRows(parsed)
    } catch (error) { setParseError(error instanceof Error ? error.message : 'The spreadsheet could not be read.') }
  }

  return <div className="animate-in fade-in slide-in-from-bottom-2 duration-500"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#4d8982]">Controlled bulk update</p><h1 className="mt-1 font-serif text-3xl text-[#17353c]">{label}</h1><p className="mt-1 max-w-2xl text-sm text-[#718087]">Download the Excel template, keep the header row, then review the file before writing its changes to the local desk.</p></div><button type="button" onClick={() => void downloadTemplate(mode)} className="inline-flex w-fit items-center gap-2 rounded-xl border border-[#2c655f]/25 bg-white px-4 py-2.5 text-sm font-bold text-[#215851]"><Download className="h-4 w-4" /> Download Excel template</button></div>
    <section className="mt-6 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-[24px] border border-dashed border-[#4d8982]/40 bg-[#f6faf7] p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#dceee8] text-[#276e65]"><FileSpreadsheet className="h-5 w-5" /></span><h2 className="mt-4 font-serif text-2xl text-[#17353c]">Choose a completed spreadsheet</h2><p className="mt-1 text-sm text-[#718087]">Accepts .xlsx, .xls, and Excel-compatible .csv files. {mode === 'prices' ? 'Rows update the existing garment × service rule when it already exists.' : 'A matching phone updates the existing customer; a new phone creates one.'}</p><label className="mt-5 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#123039] px-4 py-2.5 text-sm font-bold text-white"><Upload className="h-4 w-4" /> Select spreadsheet<input aria-label="Select spreadsheet" type="file" accept=".xlsx,.xls,.csv" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void handleFile(file) }} /></label>{fileName ? <p className="mt-4 text-sm font-semibold text-[#315f5b]">{fileName} · {rows.length} row{rows.length === 1 ? '' : 's'} ready</p> : null}{parseError ? <Message tone="error" text={parseError} /> : null}{mutation.isError ? <Message tone="error" text={mutation.error instanceof Error ? mutation.error.message : 'The import could not be saved.'} /> : null}</div><Instructions mode={mode} /></section>
    {rows.length > 0 ? <section className="mt-5 overflow-hidden rounded-[24px] border border-[#263f44]/10 bg-white shadow-[0_8px_28px_rgba(37,48,43,.04)]"><div className="flex flex-col gap-3 border-b border-[#263f44]/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-serif text-xl text-[#17353c]">Review {rows.length} row{rows.length === 1 ? '' : 's'}</p><p className="mt-1 text-xs text-[#718087]">Only the rows shown in this selected file will be imported.</p></div><button type="button" disabled={mutation.isPending} onClick={() => mutation.mutate(rows)} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#3a7d78] px-4 text-sm font-bold text-white disabled:bg-[#a8b7b2]">{mutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}{mutation.isPending ? 'Importing…' : `Import ${rows.length} row${rows.length === 1 ? '' : 's'}`}</button></div><Preview rows={rows} /></section> : null}
    {result ? <ImportOutcome result={result} /> : null}
    <ImportHistory jobs={jobs.data || []} loading={jobs.isLoading} />
  </div>
}

function Instructions({ mode }: { mode: ImportMode }) { const heading = mode === 'customers' ? 'Customer columns' : 'Price columns'; const columns = mode === 'customers' ? ['Customer Name*', 'Phone*', 'Email', 'Address'] : ['Garment*', 'Category', 'Service*', 'Rate*', 'Unit', 'HSN', 'GST Rate', 'Customer Phone']; return <aside className="rounded-[24px] bg-[#123039] p-6 text-[#edf3ec]"><UsersRound className="h-5 w-5 text-[#f1ca75]" /><p className="mt-4 font-serif text-xl">{heading}</p><ul className="mt-3 grid gap-2 text-sm text-[#c8dcd4]">{columns.map((column) => <li key={column} className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#f1ca75]" />{column}</li>)}</ul><p className="mt-5 border-t border-white/15 pt-4 text-xs leading-5 text-[#b8d3c8]">Rows with invalid required fields are skipped and returned with their worksheet row number. Correct only those rows, then upload again.</p></aside> }
function Preview({ rows }: { rows: ImportRow[] }) { const headings = Object.keys(rows[0] || {}); return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#fafaf7] text-[10px] font-bold uppercase tracking-[.14em] text-[#718087]"><tr>{headings.map((heading) => <th key={heading} className="px-5 py-3">{heading}</th>)}</tr></thead><tbody>{rows.slice(0, 5).map((row, index) => <tr key={index} className="border-t border-[#263f44]/8">{headings.map((heading) => <td key={heading} className="px-5 py-3.5 text-[#43565a]">{String(row[heading] ?? '—')}</td>)}</tr>)}</tbody></table>{rows.length > 5 ? <p className="border-t border-[#263f44]/8 px-5 py-3 text-xs text-[#718087]">Previewing the first 5 rows.</p> : null}</div> }
function ImportOutcome({ result }: { result: ImportResult }) { const clean = result.errors.length === 0; return <section className="mt-5 rounded-[24px] border border-[#263f44]/10 bg-white p-5 shadow-[0_8px_28px_rgba(37,48,43,.04)]"><div className="flex items-center gap-2 text-[#17353c]">{clean ? <CheckCircle2 className="h-5 w-5 text-[#3a7d78]" /> : <AlertTriangle className="h-5 w-5 text-[#b77928]" />}<h2 className="font-serif text-xl">Import result</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Outcome label="Created" value={result.created} tone="green" /><Outcome label="Updated" value={result.updated} tone="blue" /><Outcome label="Skipped" value={result.skipped} tone="amber" /></div>{result.errors.length ? <div className="mt-4 rounded-xl bg-[#fff7e9] p-4 text-sm text-[#815411]"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-bold">Correct and re-upload these rows</p><button type="button" onClick={() => downloadRejectedRows(result.errors)} className="inline-flex items-center gap-1.5 rounded-lg border border-[#b77928]/25 bg-white px-2.5 py-1.5 text-xs font-bold text-[#815411]"><Download className="h-3.5 w-3.5" />Download rejected rows</button></div><ul className="mt-2 list-disc space-y-1 pl-5">{result.errors.slice(0, 10).map((error) => <li key={`${error.row}-${error.message}`}>Row {error.row}: {error.message}</li>)}</ul></div> : <p className="mt-4 text-sm text-[#42706a]">Every reviewed row has been saved.</p>}</section> }
function ImportHistory({ jobs, loading }: { jobs: ImportJob[]; loading: boolean }) { return <section className="mt-5 overflow-hidden rounded-[24px] border border-[#263f44]/10 bg-white shadow-[0_8px_28px_rgba(37,48,43,.04)]"><div className="border-b border-[#263f44]/10 p-5"><p className="font-serif text-xl text-[#17353c]">Recent import jobs</p><p className="mt-1 text-xs text-[#718087]">Local audit evidence of each completed spreadsheet write.</p></div>{loading ? <div className="p-5 text-sm text-[#718087]">Loading import history…</div> : jobs.length ? <div className="divide-y divide-[#263f44]/8">{jobs.slice(0, 6).map((job) => <div key={job.id} className="flex flex-wrap items-center gap-x-5 gap-y-2 p-4 text-sm"><span className="min-w-44 font-semibold text-[#31484d]">{new Date(job.completedAt || Date.now()).toLocaleString()}</span><span className={job.errors.length ? 'rounded-full bg-[#fff4dc] px-2 py-1 text-xs font-bold text-[#8a5a14]' : 'rounded-full bg-[#e9f5ed] px-2 py-1 text-xs font-bold text-[#287061]'}>{job.status}</span><span className="text-[#617178]">{job.createdRows} created · {job.updatedRows} updated · {job.skippedRows} skipped</span>{job.errors.length ? <button type="button" onClick={() => downloadRejectedRows(job.errors)} className="ml-auto text-xs font-bold text-[#39786f]">Download errors</button> : null}</div>)}</div> : <div className="p-5 text-sm text-[#718087]">No completed import jobs for this data type yet.</div>}</section> }
function Outcome({ label, value, tone }: { label: string; value: number; tone: 'green' | 'blue' | 'amber' }) { const color = tone === 'green' ? 'bg-[#e9f5ed] text-[#287061]' : tone === 'blue' ? 'bg-[#e9f2f8] text-[#276582]' : 'bg-[#fff4dc] text-[#8a5a14]'; return <div className={`rounded-xl p-4 ${color}`}><p className="text-xs font-bold uppercase tracking-[.13em]">{label}</p><p className="mt-1 font-serif text-3xl">{value}</p></div> }
function Message({ tone, text }: { tone: 'error'; text: string }) { return <p className={tone === 'error' ? 'mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700' : ''}>{text}</p> }
function key(value: string) { return value.toLowerCase().replace(/[^a-z0-9]/g, '') }
function value(row: Record<string, unknown>, names: string[]) { const entries = new Map(Object.entries(row).map(([name, cell]) => [key(name), cell])); for (const name of names) { const found = entries.get(key(name)); if (found !== undefined) return String(found).trim() } return '' }
function customerRow(row: Record<string, unknown>): ImportRow { return { name: value(row, ['Customer Name', 'Name']), phone: value(row, ['Phone', 'Mobile', 'Phone Number']), email: value(row, ['Email', 'Email Address']), address: value(row, ['Address']) } }
function priceRow(row: Record<string, unknown>): ImportRow { return { garmentName: value(row, ['Garment', 'Garment Name']), categoryName: value(row, ['Category', 'Category Name']), serviceName: value(row, ['Service', 'Service Name']), rate: value(row, ['Rate', 'Price']), unit: value(row, ['Unit']), hsn: value(row, ['HSN']), gstRate: value(row, ['GST Rate', 'GST']), customerPhone: value(row, ['Customer Phone', 'Phone']) } }
async function readSpreadsheet(file: File): Promise<Record<string, unknown>[]> { const XLSX = await import('xlsx'); const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; if (!sheet) throw new Error('The spreadsheet has no worksheet.'); return XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: '', raw: false }) }
async function downloadTemplate(mode: ImportMode) { const XLSX = await import('xlsx'); const worksheet = XLSX.utils.aoa_to_sheet(mode === 'customers' ? CUSTOMER_TEMPLATE : PRICE_TEMPLATE); worksheet['!cols'] = (mode === 'customers' ? [22, 16, 28, 34] : [22, 18, 22, 12, 14, 12, 12, 20]).map((width) => ({ wch: width })); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, mode === 'customers' ? 'Customers' : 'Garment Prices'); XLSX.writeFile(workbook, mode === 'customers' ? 'laundry-customer-import-template.xlsx' : 'laundry-price-import-template.xlsx', { compression: true }) }
function downloadRejectedRows(errors: Array<{ row: number; message: string }>) { const body = ['Worksheet row,Reason', ...errors.map((error) => `${error.row},"${error.message.replace(/"/g, '""')}"`)].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([body], { type: 'text/csv;charset=utf-8' })); link.download = 'laundry-import-rejections.csv'; link.click(); URL.revokeObjectURL(link.href) }
