import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, Cloud, RefreshCw, X } from 'lucide-react'
import { useState } from 'react'
import { apiGet, apiPost, operatorErrorMessage } from '@/lib/api'

type OnlineOrder = { id: string; externalOrderId: string; orderNumber: string; channel: string; state: string; sourceVersion: number; customer: Record<string, unknown>; pickup: Record<string, unknown>; request: Record<string, unknown>; paymentState: string; acceptanceDeadline?: string; preferences: string; notes: string; syncState: string; updatedAt: string }
type QueuePage = { items: OnlineOrder[]; nextCursor?: string }
type SyncStatus = { configured: boolean; version: number; device: { id: string; vendorId: string; storeId: string; station: string; status: string; rotationRequired: boolean } | null; outbox: { pending: number; retry: number; deadLetter: number }; inbox: { held: number; failed: number }; onlineOrders: number }

const stateTone = (state: string) => state === 'AwaitingAcceptance' ? 'bg-amber-100 text-amber-800' : state === 'Accepted' ? 'bg-emerald-100 text-emerald-800' : state === 'Rejected' || state === 'Cancelled' ? 'bg-rose-100 text-rose-800' : 'bg-slate-100 text-slate-700'

export default function LaundryOnlineOrders() {
  const client = useQueryClient(); const [cursor, setCursor] = useState<string | undefined>(); const [items, setItems] = useState<OnlineOrder[]>([])
  const queue = useQuery({ queryKey: ['marketplace-online-orders', cursor], queryFn: () => apiGet<QueuePage>(`/marketplace/orders?limit=50${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`), staleTime: 10_000 })
  const sync = useQuery({ queryKey: ['marketplace-sync-status'], queryFn: () => apiGet<SyncStatus>('/marketplace/sync/status'), staleTime: 10_000 })
  const action = useMutation({ mutationFn: ({ id, action, reason }: { id: string; action: 'accept' | 'reject'; reason?: string }) => apiPost(`/marketplace/orders/${encodeURIComponent(id)}/${action}`, action === 'reject' ? { reason } : {}), onSuccess: () => { setCursor(undefined); setItems([]); void client.invalidateQueries({ queryKey: ['marketplace-online-orders'] }); void client.invalidateQueries({ queryKey: ['marketplace-sync-status'] }) } })
  const shown = cursor ? [...items, ...(queue.data?.items || [])] : (queue.data?.items || [])
  const reject = (order: OnlineOrder) => { const reason = window.prompt(`Reason for rejecting ${order.orderNumber}:`); if (reason?.trim()) action.mutate({ id: order.externalOrderId, action: 'reject', reason: reason.trim() }) }
  const loadMore = () => { if (!queue.data?.nextCursor) return; setItems(shown); setCursor(queue.data.nextCursor) }
  const refresh = () => { setCursor(undefined); setItems([]); void queue.refetch(); void sync.refetch() }
  return <div className="animate-in fade-in slide-in-from-bottom-2 duration-500"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#4d8982]">Marketplace edge</p><h1 className="mt-1 font-serif text-3xl text-[#17353c]">Online orders</h1><p className="mt-1 max-w-2xl text-sm text-[#718087]">Cloud-originated requests projected into this store. Acceptance is a durable outbound command; it is not a claim of remote completion.</p></div><button type="button" onClick={refresh} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-[#263f44]/15 bg-white px-3 text-xs font-bold text-[#315d57]"><RefreshCw className="h-3.5 w-3.5" />Refresh</button></header>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{sync.isLoading ? <p className="col-span-full text-sm text-[#718087]">Checking local sync state…</p> : sync.isError || !sync.data ? <p className="col-span-full rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Sync diagnostics are unavailable. No connection state is assumed.</p> : <><Metric label="Connection" value={sync.data.configured ? 'Configured' : 'Not configured'} /><Metric label="Online queue" value={String(sync.data.onlineOrders)} /><Metric label="Pending push" value={String(sync.data.outbox.pending + sync.data.outbox.retry)} /><Metric label="Dead letters" value={String(sync.data.outbox.deadLetter)} danger={sync.data.outbox.deadLetter > 0} /><Metric label="Held inbound" value={String(sync.data.inbox.held)} danger={sync.data.inbox.held > 0} /></>}</section>
    {action.isError ? <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{operatorErrorMessage(action.error, 'Online order action failed.')}</p> : null}
    <section className="mt-5 overflow-hidden rounded-[22px] border border-[#263f44]/10 bg-white shadow-[0_8px_28px_rgba(37,48,43,.04)]"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-[#fbfbf8] text-[10px] font-bold uppercase tracking-[.13em] text-[#718087]"><tr><th className="px-4 py-3">Order</th><th className="px-4 py-3">Channel</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Request</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{queue.isLoading && !shown.length ? <tr><td colSpan={7} className="p-12 text-center text-[#718087]">Loading online order queue…</td></tr> : shown.map((order) => <tr key={order.id} className="border-t border-[#263f44]/8"><td className="px-4 py-3"><p className="font-bold text-[#27454c]">{order.orderNumber}</p><p className="mt-0.5 font-mono text-[10px] text-[#718087]">{order.externalOrderId}</p></td><td className="px-4 py-3 text-xs text-[#617178]">{order.channel.replace('_', ' ')}</td><td className="px-4 py-3"><p className="font-semibold text-[#40565a]">{String(order.customer.name || 'Customer')}</p><p className="mt-0.5 max-w-48 truncate text-xs text-[#718087]">{String(order.pickup.address || order.pickup.slot || '')}</p></td><td className="px-4 py-3 text-xs text-[#617178]">{String(order.request.estimatedBags || order.request.estimatedItems || 'Assessment pending')}</td><td className="px-4 py-3 text-xs text-[#617178]">{order.paymentState}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${stateTone(order.state)}`}>{order.state}</span></td><td className="px-4 py-3">{order.state === 'AwaitingAcceptance' ? <div className="flex gap-1"><button disabled={action.isPending} onClick={() => action.mutate({ id: order.externalOrderId, action: 'accept' })} className="inline-flex items-center gap-1 rounded-lg bg-[#39786f] px-2 py-1.5 text-[10px] font-bold text-white disabled:opacity-50"><Check className="h-3 w-3" />Accept</button><button disabled={action.isPending} onClick={() => reject(order)} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 px-2 py-1.5 text-[10px] font-bold text-rose-700 disabled:opacity-50"><X className="h-3 w-3" />Reject</button></div> : <span className="text-xs text-[#718087]">{order.syncState}</span>}</td></tr>)}{!queue.isLoading && !shown.length ? <tr><td colSpan={7} className="p-12 text-center text-[#718087]">No online orders are currently projected into this store.</td></tr> : null}</tbody></table></div>{queue.data?.nextCursor ? <div className="border-t border-[#263f44]/10 p-3 text-center"><button type="button" onClick={loadMore} disabled={queue.isFetching} className="rounded-lg border border-[#263f44]/15 px-3 py-2 text-xs font-bold text-[#315d57]">Load next page</button></div> : null}</section></div>
}
function Metric({ label, value, danger = false }: { label: string; value: string; danger?: boolean }) { return <div className="rounded-xl border border-[#263f44]/10 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#718087]">{label}</p><p className={`mt-1 flex items-center gap-2 text-lg font-bold tabular-nums ${danger ? 'text-rose-700' : 'text-[#27454c]'}`}>{label === 'Connection' ? <Cloud className="h-4 w-4 text-[#39786f]" /> : null}{value}</p></div> }
