import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Loader2, Plus, ReceiptText, Search, WalletCards, X } from 'lucide-react'
import { useState } from 'react'
import { apiGet, apiPost } from '@/lib/api'
import { formatINR } from '@/lib/utils'

type Expense = { id: string; reference: string; expenseName: string; expenseDate: string; amount: number; paymentReceiver: string; invoiceNumber: string; isTaxPaid: boolean; paymentMode: string; notes: string }

export default function LaundryExpenses() {
  const client = useQueryClient(); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false)
  const expenses = useQuery({ queryKey: ['laundry-expenses', search], queryFn: () => apiGet<Expense[]>(`/laundry/expenses?search=${encodeURIComponent(search)}`) })
  const create = useMutation({ mutationFn: (body: Record<string, unknown>) => apiPost<Expense>('/laundry/expenses', body), onSuccess: () => { client.invalidateQueries({ queryKey: ['laundry-expenses'] }); client.invalidateQueries({ queryKey: ['laundry-reports'] }); setOpen(false) } })
  const total = expenses.data?.reduce((sum, expense) => sum + expense.amount, 0) || 0
  return <div className="animate-in fade-in slide-in-from-bottom-2 duration-500"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#4d8982]">Store ledger</p><h1 className="mt-1 font-serif text-3xl text-[#17353c]">Store expense</h1><p className="mt-1 text-sm text-[#718087]">Every expense writes through to the accounting journal.</p></div><button onClick={() => setOpen(true)} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#123039] px-4 py-2.5 text-sm font-bold text-white"><Plus className="h-4 w-4" /> Add expense</button></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><Metric label="Filtered expenses" value={formatINR(total)} icon={WalletCards} /><Metric label="Recorded entries" value={String(expenses.data?.length || 0)} icon={ReceiptText} /></div>
    <section className="mt-5 overflow-hidden rounded-[22px] border border-[#263f44]/10 bg-white shadow-[0_8px_28px_rgba(37,48,43,.04)]"><div className="border-b border-[#263f44]/10 p-4"><div className="relative max-w-md"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#7e8d90]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Expense name, receiver, invoice no." className="h-10 w-full rounded-xl border border-[#263f44]/15 bg-[#fbfbf9] pl-9 pr-3 text-sm outline-none focus:border-[#438b82]" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#fafaf7] text-[10px] font-bold uppercase tracking-[.14em] text-[#718087]"><tr><th className="px-5 py-3">Expense</th><th className="px-3 py-3">Date</th><th className="px-3 py-3">Receiver</th><th className="px-3 py-3">Reference</th><th className="px-5 py-3 text-right">Amount</th></tr></thead><tbody>{expenses.isLoading ? <tr><td colSpan={5} className="py-16 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-[#3a7d78]" /></td></tr> : expenses.data?.length ? expenses.data.map((expense) => <tr key={expense.id} className="border-t border-[#263f44]/8"><td className="px-5 py-3.5"><span className="block font-semibold">{expense.expenseName}</span><span className="text-xs text-[#718087]">{expense.paymentMode} · {expense.isTaxPaid ? 'Tax paid' : 'No tax'}</span></td><td className="px-3 py-3.5 text-[#617178]">{date(expense.expenseDate)}</td><td className="px-3 py-3.5">{expense.paymentReceiver || '—'}</td><td className="px-3 py-3.5 text-[#617178]">{expense.invoiceNumber || expense.reference}</td><td className="px-5 py-3.5 text-right font-bold tabular-nums">{formatINR(expense.amount)}</td></tr>) : <tr><td colSpan={5} className="py-16 text-center text-[#718087]">No store expenses recorded.</td></tr>}</tbody></table></div></section>{open && <ExpenseDialog pending={create.isPending} error={create.error} onClose={() => setOpen(false)} onSave={(body) => create.mutate(body)} />}</div>
}
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof WalletCards }) { return <div className="rounded-[20px] border border-[#263f44]/10 bg-white p-5 shadow-[0_8px_28px_rgba(37,48,43,.04)]"><Icon className="h-5 w-5 text-[#3a7d78]" /><p className="mt-4 text-xs font-bold uppercase tracking-[.13em] text-[#718087]">{label}</p><p className="mt-1 font-serif text-3xl text-[#17353c]">{value}</p></div> }
function ExpenseDialog({ pending, error, onClose, onSave }: { pending: boolean; error: unknown; onClose: () => void; onSave: (body: Record<string, unknown>) => void }) { const [name, setName] = useState(''); const [expenseDate, setExpenseDate] = useState(new Date().toISOString().slice(0, 10)); const [amount, setAmount] = useState(''); const [receiver, setReceiver] = useState(''); const [invoice, setInvoice] = useState(''); const [paymentMode, setPaymentMode] = useState('Cash'); const [tax, setTax] = useState(false); return <div className="fixed inset-0 z-50 grid place-items-center bg-[#102b33]/55 p-4 backdrop-blur-sm"><form onSubmit={(event) => { event.preventDefault(); onSave({ expenseName: name, expenseDate, amount: Number(amount), paymentReceiver: receiver, invoiceNumber: invoice, paymentMode, isTaxPaid: tax }) }} className="w-full max-w-md rounded-[24px] bg-[#fffdf8] p-5 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#4d8982]">New accounting record</p><h2 className="mt-1 font-serif text-2xl text-[#17353c]">Add expense</h2></div><button type="button" onClick={onClose} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-[#f0eee9]"><X className="h-4 w-4" /></button></div><div className="mt-5 grid gap-3"><Field label="Expense name" value={name} onChange={setName} required /><label className="text-xs font-semibold text-[#617178]">Expense date<input required type="date" value={expenseDate} onChange={(event) => setExpenseDate(event.target.value)} className="mt-1 h-10 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm" /></label><Field label="Amount paid" value={amount} onChange={setAmount} type="number" required /><Field label="Payment receiver" value={receiver} onChange={setReceiver} /><Field label="Invoice number" value={invoice} onChange={setInvoice} /><select aria-label="Payment mode" value={paymentMode} onChange={(event) => setPaymentMode(event.target.value)} className="h-10 rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm">{['Cash', 'UPI', 'Card', 'Bank'].map((mode) => <option key={mode}>{mode}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={tax} onChange={(event) => setTax(event.target.checked)} /> Tax paid</label></div>{Boolean(error) && <p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error instanceof Error ? error.message : 'Could not save expense.'}</p>}<button disabled={pending} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#3a7d78] text-sm font-bold text-white disabled:bg-[#a8b7b2]">{pending && <Loader2 className="h-4 w-4 animate-spin" />}{pending ? 'Saving…' : 'Save expense'}</button></form></div> }
function Field({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="text-xs font-semibold text-[#617178]">{label}<input required={required} type={type} min={type === 'number' ? '0.01' : undefined} step={type === 'number' ? '0.01' : undefined} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-10 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm" /></label> }
function date(value: string) { return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) }
