import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Bike, CheckCircle2, Clock3, Loader2, MapPin, PackageCheck, Plus, Truck, UserRoundPlus, X } from 'lucide-react'
import { useState } from 'react'
import { apiGet, apiPost } from '@/lib/api'
import type { LaundryOrder, LaundryState } from '@/lib/laundry'
import { formatINR } from '@/lib/utils'

type Rider = { id: string; name: string; phone: string }
type DispatchData = { riders: Rider[]; pickups: LaundryOrder[]; deliveries: LaundryOrder[] }
type QueueStage = 'pickup' | 'delivery'

export default function LaundryDispatch() {
  const client = useQueryClient()
  const [adding, setAdding] = useState(false)
  const dispatch = useQuery({ queryKey: ['laundry-dispatch'], queryFn: () => apiGet<DispatchData>('/laundry/dispatch') })
  const refresh = () => { client.invalidateQueries({ queryKey: ['laundry-dispatch'] }); client.invalidateQueries({ queryKey: ['laundry-dashboard'] }); client.invalidateQueries({ queryKey: ['laundry-orders'] }) }
  const assign = useMutation({ mutationFn: ({ id, stage, riderId }: { id: string; stage: QueueStage; riderId?: string }) => apiPost<LaundryOrder>(`/laundry/orders/${id}/assign`, { stage, riderId }), onSuccess: refresh })
  const transition = useMutation({ mutationFn: ({ id, state }: { id: string; state: LaundryState }) => apiPost<LaundryOrder>(`/laundry/orders/${id}/transition`, { state }), onSuccess: refresh })
  const rider = useMutation({ mutationFn: (body: { name: string; phone: string }) => apiPost<Rider>('/laundry/riders', body), onSuccess: () => { refresh(); setAdding(false) } })
  if (dispatch.isLoading) return <div className="grid h-80 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#3a7d78]" /></div>
  if (dispatch.isError || !dispatch.data) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-800">The dispatch board could not be loaded.</div>
  const data = dispatch.data
  return <div className="animate-in fade-in slide-in-from-bottom-2 duration-500"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#4d8982]">Operations control</p><h1 className="mt-1 font-serif text-3xl text-[#17353c]">Pickup & delivery desk</h1><p className="mt-1 text-sm text-[#718087]">Assign a rider before a garment leaves the store, then record each handoff in the order timeline.</p></div><button onClick={() => setAdding(true)} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#123039] px-4 py-2.5 text-sm font-bold text-white"><UserRoundPlus className="h-4 w-4" /> Add rider</button></div>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Pickup queue" value={data.pickups.length} note="Booked pickup orders" icon={PackageCheck} /><Metric label="Delivery queue" value={data.deliveries.length} note="Ready or dispatched" icon={Truck} /><Metric label="Active riders" value={data.riders.length} note="Available for assignment" icon={Bike} /></section>
    <div className="mt-5 grid gap-5 2xl:grid-cols-2"><Queue title="Pickup queue" eyebrow="Collect from customer" stage="pickup" orders={data.pickups} riders={data.riders} assigning={assign.isPending} transitioning={transition.isPending} onAssign={(id, riderId) => assign.mutate({ id, stage: 'pickup', riderId })} onTransition={(id, state) => transition.mutate({ id, state })} empty="No pickup orders are waiting." /><Queue title="Delivery queue" eyebrow="Return clean garments" stage="delivery" orders={data.deliveries} riders={data.riders} assigning={assign.isPending} transitioning={transition.isPending} onAssign={(id, riderId) => assign.mutate({ id, stage: 'delivery', riderId })} onTransition={(id, state) => transition.mutate({ id, state })} empty="No orders are ready for delivery." /></div>
    {assign.isError ? <InlineError text={assign.error instanceof Error ? assign.error.message : 'The rider assignment could not be saved.'} /> : null}{transition.isError ? <InlineError text={transition.error instanceof Error ? transition.error.message : 'The order status could not be updated.'} /> : null}{adding ? <RiderDialog pending={rider.isPending} error={rider.error} onClose={() => setAdding(false)} onSave={(body) => rider.mutate(body)} /> : null}</div>
}

function Queue({ title, eyebrow, stage, orders, riders, assigning, transitioning, onAssign, onTransition, empty }: { title: string; eyebrow: string; stage: QueueStage; orders: LaundryOrder[]; riders: Rider[]; assigning: boolean; transitioning: boolean; onAssign: (id: string, riderId?: string) => void; onTransition: (id: string, state: LaundryState) => void; empty: string }) { return <section className="overflow-hidden rounded-[24px] border border-[#263f44]/10 bg-white shadow-[0_8px_28px_rgba(37,48,43,.04)]"><header className="border-b border-[#263f44]/10 bg-[#fafaf7] p-5"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#4d8982]">{eyebrow}</p><h2 className="mt-1 font-serif text-2xl text-[#17353c]">{title}</h2></header><div className="divide-y divide-[#263f44]/8">{orders.length ? orders.map((order) => <DispatchCard key={order.id} order={order} riders={riders} stage={stage} assigning={assigning} transitioning={transitioning} onAssign={onAssign} onTransition={onTransition} />) : <p className="p-10 text-center text-sm text-[#718087]">{empty}</p>}</div></section> }
function DispatchCard({ order, riders, stage, assigning, transitioning, onAssign, onTransition }: { order: LaundryOrder; riders: Rider[]; stage: QueueStage; assigning: boolean; transitioning: boolean; onAssign: (id: string, riderId?: string) => void; onTransition: (id: string, state: LaundryState) => void }) { const assigned = stage === 'pickup' ? order.pickupRider : order.deliveryRider; const slot = stage === 'pickup' ? order.pickupSlot : order.deliverySlot; const next = stage === 'pickup' ? 'Picked Up' : order.state === 'Ready' ? 'Out for Delivery' : 'Delivered'; const canMove = Boolean(assigned) || next === 'Delivered'; return <article className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-bold text-[#215861]">{order.orderNumber}</p><p className="mt-0.5 text-sm font-medium text-[#253c40]">{order.customer.name} <span className="font-normal text-[#718087]">· {order.customer.phone}</span></p></div><p className="font-serif text-xl tabular-nums text-[#17353c]">{formatINR(order.grandTotal)}</p></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-[#617178]"><span><Clock3 className="mr-1 inline h-3.5 w-3.5" />Due {date(order.expectedDeliveryDate)}</span><span><MapPin className="mr-1 inline h-3.5 w-3.5" />{order.fulfillmentMode}</span><span>{order.itemCount} item{order.itemCount === 1 ? '' : 's'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><label className="text-xs font-bold uppercase tracking-[.12em] text-[#617178]">{stage} rider<select aria-label={`Assign ${stage} rider for ${order.orderNumber}`} value={assigned?.id || ''} onChange={(event) => onAssign(order.id, event.target.value || undefined)} disabled={assigning} className="mt-1.5 block h-10 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm font-medium normal-case tracking-normal text-[#253c40]"><option value="">Unassigned</option>{riders.map((rider) => <option key={rider.id} value={rider.id}>{rider.name}{rider.phone ? ` · ${rider.phone}` : ''}</option>)}</select></label><button disabled={!canMove || transitioning} onClick={() => onTransition(order.id, next)} className="mt-5 h-10 rounded-xl bg-[#3a7d78] px-4 text-sm font-bold text-white disabled:cursor-not-allowed disabled:bg-[#a8b7b2] sm:mt-5">{transitioning ? <Loader2 className="mx-auto h-4 w-4 animate-spin" /> : next}</button></div>{slot ? <p className="mt-3 text-xs text-[#52716c]">Scheduled: {slot}</p> : null}{!assigned && next !== 'Delivered' ? <p className="mt-3 text-xs text-[#9a6518]">Assign a rider to enable the next handoff.</p> : null}</article> }
function RiderDialog({ pending, error, onClose, onSave }: { pending: boolean; error: unknown; onClose: () => void; onSave: (body: { name: string; phone: string }) => void }) { const [name, setName] = useState(''); const [phone, setPhone] = useState(''); return <div className="fixed inset-0 z-50 grid place-items-center bg-[#102b33]/55 p-4 backdrop-blur-sm"><form onSubmit={(event) => { event.preventDefault(); onSave({ name, phone }) }} className="w-full max-w-md rounded-[24px] bg-[#fffdf8] p-5 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#4d8982]">Operations team</p><h2 className="mt-1 font-serif text-2xl text-[#17353c]">Add rider</h2></div><button type="button" aria-label="Close rider dialog" onClick={onClose} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-[#f0eee9]"><X className="h-4 w-4" /></button></div><label className="mt-5 block text-xs font-semibold text-[#617178]">Rider name<input autoFocus required value={name} onChange={(event) => setName(event.target.value)} className="mt-1 h-10 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm" /></label><label className="mt-3 block text-xs font-semibold text-[#617178]">Phone<input value={phone} onChange={(event) => setPhone(event.target.value)} inputMode="tel" className="mt-1 h-10 w-full rounded-xl border border-[#263f44]/15 bg-white px-3 text-sm" /></label>{error ? <p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error instanceof Error ? error.message : 'Could not save rider.'}</p> : null}<button disabled={pending} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#3a7d78] text-sm font-bold text-white disabled:bg-[#a8b7b2]">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : null}{pending ? 'Saving…' : 'Save rider'}</button></form></div> }
function Metric({ label, value, note, icon: Icon }: { label: string; value: number; note: string; icon: typeof Bike }) { return <div className="rounded-[20px] border border-[#263f44]/10 bg-white p-5 shadow-[0_8px_28px_rgba(37,48,43,.04)]"><Icon className="h-5 w-5 text-[#3a7d78]" /><p className="mt-4 text-xs font-bold uppercase tracking-[.13em] text-[#718087]">{label}</p><p className="mt-1 font-serif text-3xl text-[#17353c]">{value}</p><p className="mt-1 text-xs text-[#718087]">{note}</p></div> }
function InlineError({ text }: { text: string }) { return <p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{text}</p> }
function date(value: string) { return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short' }).format(new Date(`${value}T00:00:00`)) }
