import type { CanonicalInvoiceSnapshot } from './invoice-snapshot.js';

const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character] || character));
const rupees = (paise: number) => `₹${(paise / 100).toFixed(2)}`;
const quantity = (milli: number) => (milli % 1000 === 0 ? String(milli / 1000) : (milli / 1000).toFixed(3).replace(/0+$/, '').replace(/\.$/, ''));

export function renderCanonicalTaxInvoice(snapshot: CanonicalInvoiceSnapshot): string {
  const rows = snapshot.tax.lines.map((item, index) => `<tr><td>${index + 1}</td><td>${escapeHtml(item.description)}</td><td>${escapeHtml(item.classificationType)}/${escapeHtml(item.classificationCode)}</td><td>${quantity(item.quantityMilli)} ${escapeHtml(item.unit)}</td><td class="r">${rupees(item.unitPricePaise)}</td><td class="r">${rupees(item.taxablePaise)}</td><td class="r">${item.taxRateBps / 100}%</td><td class="r">${rupees(item.cgstPaise)}</td><td class="r">${rupees(item.sgstPaise)}</td><td class="r">${rupees(item.igstPaise)}</td><td class="r">${rupees(item.totalPaise)}</td></tr>`).join('');
  const tax = snapshot.tax.totals;
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(snapshot.documentType)} ${escapeHtml(snapshot.invoiceNumber)}</title><style>
  :root{color-scheme:light}body{font:13px Arial,sans-serif;color:#17353c;margin:0;padding:32px;background:#fffdf8}main{max-width:1120px;margin:auto;background:white;border:1px solid #d9e3de;padding:28px}header{display:flex;justify-content:space-between;gap:24px;border-bottom:3px solid #39786f;padding-bottom:20px}h1{font-size:24px;margin:0 0 8px}h2{font-size:16px;margin:0 0 8px}.muted{color:#617178}.right{text-align:right}.box{border:1px solid #d9e3de;border-radius:8px;padding:12px;margin-top:18px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border-bottom:1px solid #e4ebe7;padding:8px 6px;text-align:left;vertical-align:top}th{background:#f3f8f5;color:#315d57;font-size:11px;text-transform:uppercase;letter-spacing:.04em}.r{text-align:right}.totals{margin:18px 0 0 auto;width:320px}.totals div{display:flex;justify-content:space-between;padding:4px 0}.grand{border-top:2px solid #39786f;margin-top:6px;padding-top:8px;font-size:16px;font-weight:700}.notice{background:#f5f8f6;border-left:4px solid #9bad9f;padding:10px;margin-top:18px}</style></head><body><main>
  <header><div><h1>${escapeHtml(snapshot.supplier.tradeName || snapshot.supplier.legalName)}</h1><div>${escapeHtml(snapshot.supplier.legalName)}</div><div class="muted">${escapeHtml(snapshot.supplier.address)} · State code ${escapeHtml(snapshot.supplier.stateCode)} · ${escapeHtml(snapshot.supplier.pincode)}</div>${snapshot.supplier.gstin ? `<div>GSTIN: ${escapeHtml(snapshot.supplier.gstin)}</div>` : ''}</div><div class="right"><h2>${escapeHtml(snapshot.documentType === 'TaxInvoice' ? 'TAX INVOICE' : snapshot.documentType === 'CreditNote' ? 'CREDIT NOTE' : 'BILL OF SUPPLY')}</h2><div>${snapshot.documentType === 'CreditNote' ? 'Credit note' : 'Invoice'} <b>${escapeHtml(snapshot.invoiceNumber)}</b></div><div class="muted">${escapeHtml(snapshot.financialYear)} · ${escapeHtml(snapshot.issuedAt.slice(0, 10))}</div>${snapshot.referenceInvoiceNumber ? `<div>Against invoice <b>${escapeHtml(snapshot.referenceInvoiceNumber)}</b></div>` : ''}</div></header>
  <section class="box"><b>Bill to</b><br>${escapeHtml(snapshot.customer.name)}${snapshot.customer.gstin ? ` · GSTIN: ${escapeHtml(snapshot.customer.gstin)}` : ''}<br><span class="muted">${escapeHtml(snapshot.customer.address || '')}${snapshot.customer.stateCode ? ` · State code ${escapeHtml(snapshot.customer.stateCode)}` : ''}</span></section>
  <table><thead><tr><th>#</th><th>Description</th><th>Classification</th><th>Qty / unit</th><th class="r">Rate</th><th class="r">Taxable</th><th class="r">GST</th><th class="r">CGST</th><th class="r">SGST</th><th class="r">IGST</th><th class="r">Total</th></tr></thead><tbody>${rows}</tbody></table>
  <div class="totals"><div><span>Taxable value</span><b>${rupees(tax.taxablePaise)}</b></div><div><span>CGST</span><b>${rupees(tax.cgstPaise)}</b></div><div><span>SGST</span><b>${rupees(tax.sgstPaise)}</b></div><div><span>IGST</span><b>${rupees(tax.igstPaise)}</b></div><div><span>Rounding</span><b>${rupees(tax.roundingPaise)}</b></div><div class="grand"><span>Grand total</span><b>${rupees(tax.totalPaise)}</b></div><div><span>Paid</span><b>${rupees(snapshot.paidPaise)}</b></div><div><span>Outstanding</span><b>${rupees(snapshot.outstandingPaise)}</b></div></div>
  <div class="notice"><b>Place of supply:</b> State code ${escapeHtml(snapshot.tax.placeOfSupplyStateCode)} · ${snapshot.tax.intraState ? 'Intra-state GST (CGST + SGST)' : 'Inter-state GST (IGST)'}${snapshot.reason ? `<br><b>Reason:</b> ${escapeHtml(snapshot.reason)}` : ''}<br><b>Signed e-invoice QR:</b> Not generated in this local snapshot. No IRP evidence is claimed.</div>
  </main></body></html>`;
}
