export type TaxLineInput = { id: string; description: string; classificationType: 'SAC' | 'HSN'; classificationCode: string; quantityMilli: number; unit: string; unitPricePaise: number; discountPaise?: number; taxRateBps: number };
export type CanonicalTaxLine = TaxLineInput & { grossPaise: number; taxablePaise: number; cgstPaise: number; sgstPaise: number; igstPaise: number; cessPaise: number; totalPaise: number };
export type CanonicalTaxSnapshot = { placeOfSupplyStateCode: string; supplierStateCode: string; intraState: boolean; lines: CanonicalTaxLine[]; totals: { taxablePaise: number; cgstPaise: number; sgstPaise: number; igstPaise: number; cessPaise: number; roundingPaise: number; totalPaise: number } };
const money = (value: unknown, label: string) => { if (!Number.isSafeInteger(value) || Number(value) < 0) throw new Error(`${label} must be non-negative integer paise`); return Number(value); };
const roundTax = (numerator: number) => Math.floor((numerator + 5_000) / 10_000);
export function calculateCanonicalTax(input: { supplierStateCode: string; placeOfSupplyStateCode: string; lines: TaxLineInput[]; roundingPaise?: number }): CanonicalTaxSnapshot {
  const supplierStateCode = String(input.supplierStateCode || '').trim(); const placeOfSupplyStateCode = String(input.placeOfSupplyStateCode || '').trim(); if (!/^\d{2}$/.test(supplierStateCode) || !/^\d{2}$/.test(placeOfSupplyStateCode)) throw new Error('TAX_PROFILE_INCOMPLETE');
  const intraState = supplierStateCode === placeOfSupplyStateCode; const lines = input.lines.map((line) => { if (!line.id || !line.description || !['SAC', 'HSN'].includes(line.classificationType) || !/^[A-Za-z0-9.-]{2,20}$/.test(line.classificationCode) || !Number.isSafeInteger(line.quantityMilli) || line.quantityMilli <= 0 || !line.unit || !Number.isSafeInteger(line.unitPricePaise) || line.unitPricePaise < 0 || !Number.isSafeInteger(line.taxRateBps) || line.taxRateBps < 0 || line.taxRateBps > 10_000) throw new Error('TAX_CLASSIFICATION_MISSING'); const grossPaise = money(Math.floor(line.quantityMilli * line.unitPricePaise / 1000), 'gross'); const discountPaise = money(line.discountPaise || 0, 'discount'); if (discountPaise > grossPaise) throw new Error('line discount exceeds gross'); const taxablePaise = grossPaise - discountPaise; const tax = roundTax(taxablePaise * line.taxRateBps); const cgstPaise = intraState ? Math.floor(tax / 2) : 0; const sgstPaise = intraState ? tax - cgstPaise : 0; const igstPaise = intraState ? 0 : tax; return { ...line, grossPaise, taxablePaise, cgstPaise, sgstPaise, igstPaise, cessPaise: 0, totalPaise: taxablePaise + tax }; });
  const totals = lines.reduce((sum, line) => ({ taxablePaise: sum.taxablePaise + line.taxablePaise, cgstPaise: sum.cgstPaise + line.cgstPaise, sgstPaise: sum.sgstPaise + line.sgstPaise, igstPaise: sum.igstPaise + line.igstPaise, cessPaise: 0, roundingPaise: 0, totalPaise: sum.totalPaise + line.totalPaise }), { taxablePaise: 0, cgstPaise: 0, sgstPaise: 0, igstPaise: 0, cessPaise: 0, roundingPaise: 0, totalPaise: 0 }); const roundingPaise = Number.isSafeInteger(input.roundingPaise) ? input.roundingPaise! : 0; totals.roundingPaise = roundingPaise; totals.totalPaise += roundingPaise; if (totals.totalPaise !== totals.taxablePaise + totals.cgstPaise + totals.sgstPaise + totals.igstPaise + totals.cessPaise + totals.roundingPaise) throw new Error('TAX_RECONCILIATION_FAILED'); return { supplierStateCode, placeOfSupplyStateCode, intraState, lines, totals };
}
