import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const tempDir = mkdtempSync(join(tmpdir(), 'epic-e2e-test-'));
process.env.EPIC_DATA_FILE = join(tempDir, 'legacy.json');
process.env.EPIC_DB_FILE = join(tempDir, 'epic.sqlite');
process.env.EPIC_LEGACY_JSON_FILE = join(tempDir, 'legacy.json');

let closeStore: (() => void) | undefined;

async function waitForExport(app: any, id: string, headers: Record<string, string>) {
  const deadline = Date.now() + 5_000;
  let job: any;
  do {
    job = (await app.inject({ method: 'GET', url: `/api/laundry/report-exports/${id}`, headers })).json();
    if (['Completed', 'Failed', 'Expired'].includes(job.status)) return job;
    await new Promise((resolve) => setTimeout(resolve, 25));
  } while (Date.now() < deadline);
  return job;
}
try {
  const Fastify = (await import('fastify')).default;
  const { store } = await import('./kernel/store.js');
  const { registerApi } = await import('./api.js');
  const { seedLaundryDefaults } = await import('./modules/laundry/domain.js');
  closeStore = () => store.close();
  const app = Fastify(); registerApi(app);
  store.withStoreScope('E2E', 'STORE-DEFAULT', () => seedLaundryDefaults('E2E'));
  const boot = await app.inject({ method: 'POST', url: '/api/auth/bootstrap', payload: { username: 'e2e-owner', password: 'StrongE2EPassword!26', tenant: 'E2E', storeId: 'STORE-DEFAULT', businessName: 'E2E Laundry', phone: '9000000000', address: 'E2E Street', taxMode: 'gst', gstin: '22AAAAA0000A1Z5', currency: 'INR', timezone: 'Asia/Kolkata', printerProfile: 'system-default' } });
  assert.equal(boot.statusCode, 200, 'E2E owner bootstrap succeeds');
  assert.equal(boot.json().user.tenant, 'E2E', 'E2E bootstrap preserves the requested tenant scope');
  const cookie = String(boot.headers['set-cookie'] || '').split(';')[0];
  const sessionHeaders = { cookie };
  const catalogue = await app.inject({ method: 'GET', url: '/api/laundry/catalogue', headers: sessionHeaders });
  assert.equal(catalogue.statusCode, 200, 'E2E catalogue loads through the authenticated API');
  const garmentBackfillPreview = await app.inject({ method: 'GET', url: '/api/laundry/garment-backfill', headers: sessionHeaders });
  assert.equal(garmentBackfillPreview.statusCode, 200, 'E2E owner can preview historic garment-unit backfill');
  const garmentBackfillApply = await app.inject({ method: 'POST', url: '/api/laundry/garment-backfill', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-garment-backfill-001' }, payload: {} });
  assert.equal(garmentBackfillApply.statusCode, 200, 'E2E owner can apply an idempotent reviewed garment-unit backfill');
  const reportPlan = store.withStoreScope('E2E', 'STORE-DEFAULT', () => store.explainRowsOfReportDate('E2E', 'laundry_order', 'order_date', '2026-08-01', '2026-08-31'));
  assert.ok(reportPlan.some((detail) => /entity_rows_laundry_order_date/i.test(detail)), 'E2E report date query uses the dedicated SQLite expression index');
  const zone = await app.inject({ method: 'POST', url: '/api/laundry/service-zone-master', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-zone-create-001' }, payload: { name: 'North', code: 'NORTH', pickupWindow: '09:00-12:00', deliveryWindow: '16:00-20:00' } });
  assert.equal(zone.statusCode, 201, 'E2E owner can create a service-zone master row');
  const zoneRetry = await app.inject({ method: 'POST', url: '/api/laundry/service-zone-master', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-zone-create-001' }, payload: { name: 'North', code: 'NORTH', pickupWindow: '09:00-12:00', deliveryWindow: '16:00-20:00' } });
  assert.equal(zoneRetry.json().id, zone.json().id, 'E2E service-zone creation is idempotent');
  const zoneMaster = await app.inject({ method: 'GET', url: '/api/laundry/service-zone-master', headers: sessionHeaders });
  assert.ok(zoneMaster.json().some((entry: any) => entry.name === 'North' && entry.code === 'NORTH'), 'E2E owner can read the branch service-zone master');
  const zoneDisabled = await app.inject({ method: 'PATCH', url: `/api/laundry/service-zone-master/${zone.json().id}`, headers: sessionHeaders, payload: { active: false } });
  assert.equal(zoneDisabled.statusCode, 200, 'E2E owner can deactivate a service zone');
  const zoneSuggestions = await app.inject({ method: 'GET', url: '/api/laundry/service-zones', headers: sessionHeaders });
  assert.equal(zoneSuggestions.json().includes('North'), false, 'E2E inactive service zones are excluded from new suggestions');
  const zoneReenabled = await app.inject({ method: 'PATCH', url: `/api/laundry/service-zone-master/${zone.json().id}`, headers: sessionHeaders, payload: { active: true } });
  assert.equal(zoneReenabled.json().active, true, 'E2E service zone can be re-enabled');
  const rack = await app.inject({ method: 'POST', url: '/api/laundry/rack-profiles', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-rack-create-001' }, payload: { name: 'RACK-A-01', code: 'A01', capacity: 20 } });
  assert.equal(rack.statusCode, 201, 'E2E owner can create a rack capacity profile');
  const rackRetry = await app.inject({ method: 'POST', url: '/api/laundry/rack-profiles', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-rack-create-001' }, payload: { name: 'RACK-A-01', code: 'A01', capacity: 20 } });
  assert.equal(rackRetry.json().id, rack.json().id, 'E2E rack profile creation is idempotent');
  const rackMaster = await app.inject({ method: 'GET', url: '/api/laundry/rack-profiles', headers: sessionHeaders });
  assert.equal(rackMaster.json().find((entry: any) => entry.code === 'A01').capacity, 20, 'E2E rack master returns the configured physical capacity');
  const rackDisabled = await app.inject({ method: 'PATCH', url: `/api/laundry/rack-profiles/${rack.json().id}`, headers: sessionHeaders, payload: { active: false } });
  assert.equal(rackDisabled.statusCode, 200, 'E2E owner can deactivate a rack profile');
  const rackReenabled = await app.inject({ method: 'PATCH', url: `/api/laundry/rack-profiles/${rack.json().id}`, headers: sessionHeaders, payload: { active: true } });
  assert.equal(rackReenabled.json().active, true, 'E2E rack profile can be re-enabled');
  const printSettings = await app.inject({ method: 'GET', url: '/api/laundry/print-settings', headers: sessionHeaders });
  assert.equal(printSettings.statusCode, 200, 'E2E print settings are available to operational staff permissions');
  assert.equal(typeof printSettings.json().qrOnPrint, 'boolean', 'E2E print settings expose the QR toggle safely');
  assert.equal(printSettings.json().taxMode, 'gst', 'E2E bootstrap persists tax mode');
  assert.equal(printSettings.json().gstin, '22AAAAA0000A1Z5', 'E2E bootstrap persists GSTIN');
  assert.equal(printSettings.json().printerProfile, 'system-default', 'E2E bootstrap persists printer profile');
  const initialSetupProgress = await app.inject({ method: 'GET', url: '/api/settings/setup-progress', headers: sessionHeaders });
  assert.equal(initialSetupProgress.statusCode, 200, 'E2E owner can read persisted setup progress');
  assert.equal(initialSetupProgress.json().operations, true, 'E2E bootstrap records completed operational setup');
  assert.equal(initialSetupProgress.json().catalogue, false, 'E2E catalogue review remains an explicit owner action');
  const catalogueReview = await app.inject({ method: 'POST', url: '/api/settings/setup-progress', headers: sessionHeaders, payload: { catalogue: true } });
  assert.equal(catalogueReview.statusCode, 200, 'E2E owner can explicitly complete catalogue review');
  const persistedSetupProgress = await app.inject({ method: 'GET', url: '/api/settings/setup-progress', headers: sessionHeaders });
  assert.equal(persistedSetupProgress.json().catalogue, true, 'E2E setup progress survives a read boundary');
  const cat = catalogue.json();
  const catalogueImport = await app.inject({ method: 'POST', url: '/api/laundry/catalogue/import', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-catalogue-import-001' }, payload: { categories: [{ name: 'E2E Specialty', color: '#123456' }], services: [{ name: 'E2E Care', units: ['Piece'] }], garments: [{ name: 'E2E Coat', code: 'E2E-COAT', category: 'E2E Specialty', unit: 'Piece', photo: '/ui/app/garments/lndry-folded-blazer-v1.png' }], prices: [{ garment: 'E2E Coat', service: 'E2E Care', rate: 275 }] } });
  assert.equal(catalogueImport.statusCode, 201, 'E2E owner can import a reviewed master catalogue');
  const catalogueImportRetry = await app.inject({ method: 'POST', url: '/api/laundry/catalogue/import', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-catalogue-import-001' }, payload: { categories: [{ name: 'E2E Specialty', color: '#123456' }], services: [{ name: 'E2E Care', units: ['Piece'] }], garments: [{ name: 'E2E Coat', code: 'E2E-COAT', category: 'E2E Specialty', unit: 'Piece', photo: '/ui/app/garments/lndry-folded-blazer-v1.png' }], prices: [{ garment: 'E2E Coat', service: 'E2E Care', rate: 275 }] } });
  assert.equal(catalogueImportRetry.json().job.id, catalogueImport.json().job.id, 'E2E catalogue import is idempotent');
  const holdPayload = { cart: { [`${cat.garments[0].id}:${cat.services[0].id}`]: { garment: cat.garments[0].id, service: cat.services[0].id, qty: 1 } }, newCustomerName: 'Held Customer', newCustomerPhone: '9000000788', deliveryMode: 'Home Delivery', expectedDeliveryDate: '2026-09-06', paymentMode: 'Pay Later', notes: 'Held at counter' };
  const held = await app.inject({ method: 'POST', url: '/api/laundry/order-holds', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-order-hold-001' }, payload: holdPayload });
  assert.equal(held.statusCode, 201, 'E2E counter can persist an audited order hold');
  const heldDuplicate = await app.inject({ method: 'POST', url: '/api/laundry/order-holds', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-order-hold-001' }, payload: holdPayload });
  assert.equal(heldDuplicate.json().id, held.json().id, 'E2E order hold creation is idempotent');
  const activeHolds = await app.inject({ method: 'GET', url: '/api/laundry/order-holds', headers: sessionHeaders });
  assert.ok(activeHolds.json().some((entry: any) => entry.id === held.json().id && entry.status === 'Held'), 'E2E active hold is visible to the same store');
  const ownerPresence = await app.inject({ method: 'GET', url: '/api/laundry/order-holds/presence', headers: sessionHeaders });
  assert.equal(ownerPresence.statusCode, 200, 'E2E counter hold presence endpoint is available');
  assert.equal(ownerPresence.json().mineActive, 1, 'E2E hold presence attributes the active lease to its counter');
  const holdHeartbeat = await app.inject({ method: 'POST', url: `/api/laundry/order-holds/${held.json().id}/heartbeat`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-order-hold-heartbeat-001' }, payload: {} });
  assert.equal(holdHeartbeat.statusCode, 200, 'E2E owning counter can renew an active hold lease');
  assert.equal(holdHeartbeat.json().ownership, 'mine', 'E2E hold heartbeat preserves ownership');
  const secondCounter = await app.inject({ method: 'POST', url: '/api/settings/staff', headers: sessionHeaders, payload: { username: 'e2e-counter-2', password: 'StrongCounterPassword!26', roles: ['counter_staff'], firstName: 'Second', lastName: 'Counter' } });
  assert.equal(secondCounter.statusCode, 201, 'E2E owner can provision a second counter identity');
  const secondCounterLogin = await app.inject({ method: 'POST', url: '/api/auth/sign-in', payload: { username: 'e2e-counter-2', password: 'StrongCounterPassword!26' } });
  assert.equal(secondCounterLogin.statusCode, 200, 'E2E second counter can sign in');
  const secondCounterHeaders = { cookie: String(secondCounterLogin.headers['set-cookie'] || '').split(';')[0] };
  const otherCounterView = await app.inject({ method: 'GET', url: '/api/laundry/order-holds', headers: secondCounterHeaders });
  assert.equal(otherCounterView.json().find((entry: any) => entry.id === held.json().id).ownership, 'other', 'E2E hold ownership is visible to another counter');
  const otherPresence = await app.inject({ method: 'GET', url: '/api/laundry/order-holds/presence', headers: secondCounterHeaders });
  assert.equal(otherPresence.json().otherActive, 1, 'E2E hold presence exposes another counter lease without transferring it');
  const blockedResume = await app.inject({ method: 'POST', url: `/api/laundry/order-holds/${held.json().id}/resume`, headers: { ...secondCounterHeaders, 'idempotency-key': 'e2e-order-hold-blocked-resume-001' }, payload: {} });
  assert.equal(blockedResume.statusCode, 400, 'E2E a different counter cannot resume an owned hold without claiming it');
  const claimedHold = await app.inject({ method: 'POST', url: `/api/laundry/order-holds/${held.json().id}/claim`, headers: { ...secondCounterHeaders, 'idempotency-key': 'e2e-order-hold-claim-001' }, payload: {} });
  assert.equal(claimedHold.statusCode, 200, 'E2E another counter can explicitly claim a held order');
  assert.equal(claimedHold.json().ownership, 'mine', 'E2E claim transfers hold ownership to the second counter');
  const resumedHold = await app.inject({ method: 'POST', url: `/api/laundry/order-holds/${held.json().id}/resume`, headers: { ...secondCounterHeaders, 'idempotency-key': 'e2e-order-hold-resume-001' }, payload: {} });
  assert.equal(resumedHold.statusCode, 200, 'E2E the claiming counter can resume an order hold');
  assert.equal(resumedHold.json().status, 'Resumed', 'E2E hold resume is an explicit terminal state');
  const closedHolds = await app.inject({ method: 'GET', url: '/api/laundry/order-holds?includeClosed=true', headers: sessionHeaders });
  assert.equal(closedHolds.json().find((entry: any) => entry.id === held.json().id).status, 'Resumed', 'E2E closed hold history remains queryable');
  const holdAudit = await app.inject({ method: 'GET', url: '/api/ledger/audit', headers: sessionHeaders });
  assert.equal(holdAudit.json().some((entry: any) => entry.action === 'laundry:order-held' && entry.row_id === held.json().id), true, 'E2E hold and resume actions are auditable');
  const addressCustomer = await app.inject({ method: 'POST', url: '/api/laundry/customers', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-address-customer-001' }, payload: { name: 'Address Customer', phone: '9000000890', address: 'Primary Street' } });
  assert.equal(addressCustomer.statusCode, 201, 'E2E customer with a primary address succeeds');
  const addressCustomerId = addressCustomer.json().id;
  const primaryAddresses = await app.inject({ method: 'GET', url: `/api/laundry/customers/${addressCustomerId}/addresses`, headers: sessionHeaders });
  assert.equal(primaryAddresses.json().length, 1, 'E2E customer creation materializes a default address record');
  const editedPrimary = await app.inject({ method: 'PATCH', url: `/api/laundry/customers/${addressCustomerId}/addresses/${primaryAddresses.json()[0].id}`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-address-edit-001' }, payload: { label: 'Primary', line1: 'Primary Street Updated', isDefault: false } });
  assert.equal(editedPrimary.json().isDefault, true, 'E2E editing the only default cannot leave the address book without a default');
  const secondAddress = await app.inject({ method: 'POST', url: `/api/laundry/customers/${addressCustomerId}/addresses`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-address-001' }, payload: { label: 'Work', line1: 'Work Street', city: 'Bengaluru', isDefault: true } });
  assert.equal(secondAddress.statusCode, 200, 'E2E customer can add a second address');
  const addressProfile = await app.inject({ method: 'GET', url: `/api/laundry/customers/${addressCustomerId}`, headers: sessionHeaders });
  assert.equal(addressProfile.json().addresses.filter((address: any) => address.isDefault).length, 1, 'E2E address book keeps exactly one default address');
  const archivedAddress = await app.inject({ method: 'POST', url: `/api/laundry/customers/${addressCustomerId}/addresses/${secondAddress.json().id}/archive`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-address-archive-001' }, payload: {} });
  assert.equal(archivedAddress.statusCode, 200, 'E2E customer can archive an address');
  const restoredDefault = await app.inject({ method: 'GET', url: `/api/laundry/customers/${addressCustomerId}/addresses`, headers: sessionHeaders });
  assert.equal(restoredDefault.json().find((address: any) => address.active).isDefault, true, 'E2E archiving the default promotes an active replacement');
  const body = { customer: { name: 'E2E Customer', phone: '9000000777', address: 'E2E Street' }, items: [{ garment: cat.garments[0].id, service: cat.services[0].id, qty: 2 }], expectedDeliveryDate: '2026-09-04', fulfillmentMode: 'Home Delivery', paymentMode: 'Pay Later' };
  const headers = { ...sessionHeaders, 'idempotency-key': 'e2e-booking-001' };
  const booked = await app.inject({ method: 'POST', url: '/api/laundry/orders', headers, payload: body });
  const duplicate = await app.inject({ method: 'POST', url: '/api/laundry/orders', headers, payload: body });
  assert.equal(booked.statusCode, 201, 'E2E booking succeeds');
  assert.equal(duplicate.json().order.id, booked.json().order.id, 'E2E duplicate booking is idempotent');
  const unauthenticatedPrintJobs = await app.inject({ method: 'GET', url: '/api/laundry/print-jobs' });
  assert.equal(unauthenticatedPrintJobs.statusCode, 401, 'E2E print history requires an authenticated session');
  const bookedUnits = booked.json().garmentUnits;
  const bookedUnit = bookedUnits[0];
  const printJob = await app.inject({ method: 'POST', url: '/api/laundry/print-jobs', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-print-job-001' }, payload: { orderId: booked.json().order.id, documentType: 'garment-tags', tagIds: [bookedUnit.tagCode], requestedCopies: 1, status: 'Printed', evidence: 'E2E native print accepted' } });
  assert.equal(printJob.statusCode, 201, 'E2E authenticated operator can record a tag print job');
  assert.equal(printJob.json().tagIds[0], bookedUnit.id, 'E2E print history stores the durable garment-unit identity');
  const printHistory = await app.inject({ method: 'GET', url: `/api/laundry/print-jobs?orderId=${encodeURIComponent(booked.json().order.id)}`, headers: sessionHeaders });
  assert.ok(printHistory.json().some((job: any) => job.id === printJob.json().id && job.status === 'Printed'), 'E2E print history returns the recorded job for its order');
  const malformedScan = await app.inject({ method: 'POST', url: '/api/laundry/garment-units/scan', headers: sessionHeaders, payload: { tagCode: bookedUnit.tagCode, nextState: 'not-a-garment-state' } });
  assert.equal(malformedScan.statusCode, 400, 'E2E schema validation rejects an unknown garment state before domain execution');
  const batchPrintJob = await app.inject({ method: 'POST', url: '/api/laundry/print-jobs', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-print-job-batch-001' }, payload: { orderId: booked.json().order.id, documentType: 'garment-tags', tagIds: bookedUnits.map((unit: any) => unit.tagCode), status: 'Printed' } });
  assert.equal(batchPrintJob.statusCode, 201, 'E2E batch print job accepts multiple distinct garment tags');
  assert.equal(batchPrintJob.json().tagIds.length, bookedUnits.length, 'E2E batch print job preserves physical tag count separately');
  assert.equal(batchPrintJob.json().requestedCopies, 1, 'E2E batch print job records one document copy, not one copy per tag');
  const unknownPrintTag = await app.inject({ method: 'POST', url: '/api/laundry/print-jobs', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-print-job-unknown-001' }, payload: { orderId: booked.json().order.id, documentType: 'garment-tags', tagIds: ['ELT-UNKNOWN'], requestedCopies: 1 } });
  assert.equal(unknownPrintTag.statusCode, 400, 'E2E print job rejects an unknown tag reference');
  assert.equal(unknownPrintTag.json().code, 'PRINT_JOB_INVALID', 'E2E print job rejection exposes a stable domain code');
  const bulkGarment = cat.garments.find((garment: any) => garment.unit === 'Kilogram');
  const bulkPrice = bulkGarment && cat.prices.find((price: any) => price.garment === bulkGarment.id);
  if (bulkGarment && bulkPrice) {
    const bulkBooking = await app.inject({ method: 'POST', url: '/api/laundry/orders', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-bulk-booking-001' }, payload: { customer: { name: 'E2E Bulk Customer', phone: '9000000799' }, items: [{ garment: bulkGarment.id, service: bulkPrice.service, qty: 4.5 }], containerCount: 2, expectedDeliveryDate: '2026-09-04', fulfillmentMode: 'Home Delivery', paymentMode: 'Pay Later' } });
    assert.equal(bulkBooking.statusCode, 201, 'E2E weighted booking accepts an explicit container count');
    assert.equal(bulkBooking.json().garmentUnits.length, 0, 'E2E weighted booking does not fabricate garment-piece tags');
    assert.equal(bulkBooking.json().containerTags.length, 2, 'E2E weighted booking returns explicit bag/container tags');
    const containerTag = bulkBooking.json().containerTags[0].tagNumber;
    const containerDetail = await app.inject({ method: 'GET', url: `/api/laundry/containers/${encodeURIComponent(containerTag)}`, headers: sessionHeaders });
    assert.equal(containerDetail.statusCode, 200, 'E2E container tag resolves through the authenticated detail route');
    const containerSearch = await app.inject({ method: 'GET', url: `/api/laundry/search?q=${encodeURIComponent(containerTag)}`, headers: sessionHeaders });
    assert.ok(containerSearch.json().some((result: any) => result.kind === 'container' && result.path.includes('kind=container')), 'E2E global search resolves a bag tag into container tracking');
    const containerScan = await app.inject({ method: 'POST', url: '/api/laundry/containers/scan', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-container-scan-001' }, payload: { tagCode: containerTag, nextState: 'Processing', location: 'Bulk wash' } });
    assert.equal(containerScan.statusCode, 201, 'E2E container scan advances the bulk lifecycle');
    const bagJob = await app.inject({ method: 'POST', url: '/api/laundry/print-jobs', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-bag-print-001' }, payload: { orderId: bulkBooking.json().order.id, documentType: 'bag-tags', containerIds: [containerTag], status: 'Printed' } });
    assert.equal(bagJob.statusCode, 201, 'E2E bag-tag print history accepts explicit containers');
    assert.equal(bagJob.json().tagIds[0], containerDetail.json().id, 'E2E bag-tag print history stores the durable container identity');
  }
  const customerNormalizationPreview = await app.inject({ method: 'GET', url: '/api/ops/entity-normalization?entity=party', headers: sessionHeaders });
  assert.equal(customerNormalizationPreview.statusCode, 200, 'E2E owner can preview customer normalization');
  assert.equal(customerNormalizationPreview.json().invalid, 0, 'E2E customer normalization preflight is clean');
  let customerNormalization: any;
  for (let attempt = 0; attempt < 20; attempt += 1) {
    customerNormalization = (await app.inject({ method: 'POST', url: '/api/ops/entity-normalization', headers: { ...sessionHeaders, 'idempotency-key': `e2e-entity-party-${attempt}` }, payload: { entity: 'party', batchSize: 2 } })).json();
    if (customerNormalization.done) break;
  }
  assert.equal(customerNormalization.status, 'completed', 'E2E customer normalization completes in bounded batches');
  const orderNormalizationPreview = await app.inject({ method: 'GET', url: '/api/ops/entity-normalization?entity=laundry_order', headers: sessionHeaders });
  assert.equal(orderNormalizationPreview.statusCode, 200, 'E2E owner can preview order normalization');
  assert.equal(orderNormalizationPreview.json().invalid, 0, 'E2E order normalization preflight is clean');
  let orderNormalization: any;
  for (let attempt = 0; attempt < 20; attempt += 1) {
    orderNormalization = (await app.inject({ method: 'POST', url: '/api/ops/entity-normalization', headers: { ...sessionHeaders, 'idempotency-key': `e2e-entity-order-${attempt}` }, payload: { entity: 'laundry_order', batchSize: 2 } })).json();
    if (orderNormalization.done) break;
  }
  assert.equal(orderNormalization.status, 'completed', 'E2E order normalization completes in bounded batches');
  const globalSearch = await app.inject({ method: 'GET', url: '/api/laundry/search?q=E2E%20Customer', headers: sessionHeaders });
  assert.equal(globalSearch.statusCode, 200, 'E2E authenticated global search succeeds');
  assert.ok(globalSearch.json().some((result: any) => result.kind === 'customer' && result.label === 'E2E Customer'), 'E2E global search finds the customer record');
  const orderSearch = await app.inject({ method: 'GET', url: `/api/laundry/search?q=${encodeURIComponent(booked.json().order.orderNumber)}`, headers: sessionHeaders });
  assert.ok(orderSearch.json().some((result: any) => result.kind === 'order' && result.id === booked.json().order.id), 'E2E global search finds the order record');
  const invoiceSearch = await app.inject({ method: 'GET', url: `/api/laundry/search?q=${encodeURIComponent(booked.json().order.invoiceNumber || booked.json().order.invoice || '')}`, headers: sessionHeaders });
  assert.ok(invoiceSearch.json().some((result: any) => result.kind === 'invoice' && result.path.includes(booked.json().order.id)), 'E2E global search resolves an invoice to its order workflow');
  const offlineOrderBody = { ...body, customer: { name: 'Offline Order', phone: '9000000889', address: 'Offline Street' }, paymentMode: 'Pay Later' };
  const offlineOrder = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'laundry_order', clientId: 'offline-order-001', data: offlineOrderBody }] } });
  assert.equal(offlineOrder.json().applied, 1, 'E2E offline order replay applies the authoritative booking command');
  const offlineOrderRetry = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'laundry_order', clientId: 'offline-order-001', data: { ...offlineOrderBody, notes: 'changed on retry' } }] } });
  assert.equal(offlineOrderRetry.json().results[0].ok, false, 'E2E offline replay rejects a reused key with a different payload');
  assert.match(offlineOrderRetry.json().results[0].error, /different command payload/, 'E2E offline conflict includes an actionable message');
  const conflictAudit = await app.inject({ method: 'GET', url: '/api/ledger/audit', headers: sessionHeaders });
  assert.equal(conflictAudit.json().some((entry: any) => entry.action === 'ops:idempotency-conflict'), true, 'E2E offline idempotency conflicts are auditable');
  const offlineOrderSameRetry = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'laundry_order', clientId: 'offline-order-001', data: offlineOrderBody }] } });
  assert.equal(offlineOrderSameRetry.json().results[0].id, offlineOrder.json().results[0].id, 'E2E identical offline retry returns the original booking');
  const offlineCustomer = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'party', clientId: 'offline-customer-001', data: { name: 'Offline Replay', phone: '9000000888', is_customer: true } }] } });
  assert.equal(offlineCustomer.statusCode, 200, 'E2E authenticated offline replay succeeds');
  assert.equal(offlineCustomer.json().applied, 1, 'E2E offline replay applies one customer command');
  const offlineDuplicate = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'party', clientId: 'offline-customer-001', data: { name: 'Offline Replay Changed', phone: '9000000888', is_customer: true } }] } });
  assert.equal(offlineDuplicate.json().applied, 0, 'E2E offline replay rejects a changed customer payload');
  assert.match(offlineDuplicate.json().results[0].error, /different command payload/, 'E2E customer conflict includes an actionable message');
  const offlineCustomerRetry = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'party', clientId: 'offline-customer-001', data: { name: 'Offline Replay', phone: '9000000888', is_customer: true } }] } });
  assert.equal(offlineCustomerRetry.json().results[0].id, offlineCustomer.json().results[0].id, 'E2E identical offline retry returns the original customer');
  const replayAudit = await app.inject({ method: 'GET', url: '/api/sync/replay-audit', headers: sessionHeaders });
  assert.equal(replayAudit.statusCode, 200, 'E2E offline replay audit view is available to reports users');
  assert.equal(replayAudit.json().some((entry: any) => entry.action === 'ops:offline-replay-applied'), true, 'E2E successful offline replay is visible in the audit view');
  const unsupportedSync = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'sales_invoice', clientId: 'offline-invoice-001', data: {} }] } });
  assert.equal(unsupportedSync.json().applied, 0, 'E2E offline replay rejects unsupported generic documents');
  const orderId = booked.json().order.id;
  assert.equal(booked.json().order.version, 0, 'E2E booking starts at order version zero');
  const versionedTransition = await app.inject({ method: 'POST', url: `/api/laundry/orders/${orderId}/transition`, headers: sessionHeaders, payload: { state: 'In Process', note: 'E2E versioned transition', expectedVersion: 0 } });
  assert.equal(versionedTransition.statusCode, 200, 'E2E transition accepts the current expected version');
  assert.equal(versionedTransition.json().version, 1, 'E2E transition increments the order version');
  const staleTransition = await app.inject({ method: 'POST', url: `/api/laundry/orders/${orderId}/transition`, headers: sessionHeaders, payload: { state: 'Ready', expectedVersion: 0 } });
  assert.equal(staleTransition.statusCode, 400, 'E2E stale transition is rejected instead of overwriting newer state');
  assert.equal(staleTransition.json().code, 'STALE_ORDER_VERSION', 'E2E stale transition exposes a stable domain code');
  assert.match(staleTransition.json().error, /stale order version/, 'E2E stale transition explains the concurrency conflict');
  const assemblyFixture = await app.inject({ method: 'POST', url: '/api/laundry/orders', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-assembly-fixture-001' }, payload: { ...body, customer: { name: 'E2E Assembly', phone: '9000000788' }, paymentMode: 'Pay Later' } });
  assert.equal(assemblyFixture.statusCode, 201, 'E2E assembly guard fixture booking succeeds');
  const assemblyOrderId = assemblyFixture.json().order.id;
  const assemblyInProcess = await app.inject({ method: 'POST', url: `/api/laundry/orders/${assemblyOrderId}/transition`, headers: sessionHeaders, payload: { state: 'In Process' } });
  assert.equal(assemblyInProcess.statusCode, 200, 'E2E assembly guard fixture enters processing');
  const incompleteAssembly = await app.inject({ method: 'POST', url: `/api/laundry/orders/${assemblyOrderId}/transition`, headers: sessionHeaders, payload: { state: 'Ready', expectedVersion: 1 } });
  assert.equal(incompleteAssembly.statusCode, 400, 'E2E final Ready transition rejects incomplete tracked-piece assembly');
  assert.equal(incompleteAssembly.json().code, 'ASSEMBLY_INCOMPLETE', 'E2E assembly guard exposes a stable domain code');
  assert.match(incompleteAssembly.json().error, /assembly incomplete/, 'E2E assembly guard explains the blocked completion');
  for (const [index, unit] of assemblyFixture.json().garmentUnits.entries()) {
    for (const [stateIndex, nextState] of ['Sorted', 'Processing', 'QC', 'Assembly', 'Racked'].entries()) {
      const scan = await app.inject({ method: 'POST', url: '/api/laundry/garment-units/scan', headers: { ...sessionHeaders, 'idempotency-key': `e2e-assembly-scan-${index}-${stateIndex}` }, payload: { tagCode: unit.tagCode, nextState, location: nextState === 'Racked' ? `E2E-RACK-${index}` : `${nextState} station`, note: 'E2E assembly completion' } });
      assert.equal(scan.statusCode, 201, `E2E assembly scan advances unit ${index + 1} to ${nextState}`);
    }
  }
  const offlineTransition = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'laundry_order_transition', clientId: 'offline-transition-001', data: { orderId: assemblyOrderId, state: 'Ready', expectedVersion: 1, note: 'Offline floor completion' } }] } });
  assert.equal(offlineTransition.json().applied, 1, 'E2E offline replay accepts a versioned order transition');
  assert.equal(offlineTransition.json().results[0].id, assemblyOrderId, 'E2E offline transition returns the order identity');
  const staleOfflineTransition = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'laundry_order_transition', clientId: 'offline-transition-stale-001', data: { orderId: assemblyOrderId, state: 'Out for Delivery', expectedVersion: 1 } }] } });
  assert.equal(staleOfflineTransition.json().applied, 0, 'E2E offline replay rejects a stale versioned transition');
  assert.match(staleOfflineTransition.json().results[0].error, /stale order version/, 'E2E offline stale transition explains the conflict');
  const productionQueue = await app.inject({ method: 'GET', url: '/api/laundry/production-queue?status=Open', headers: sessionHeaders });
  assert.equal(productionQueue.statusCode, 200, 'E2E production queue is available to the authenticated operator');
  assert.ok(productionQueue.json().length >= 1, 'E2E booking creates intake station work');
  const productionLoad = await app.inject({ method: 'GET', url: '/api/laundry/production-load', headers: sessionHeaders });
  assert.equal(productionLoad.statusCode, 200, 'E2E production station load is available');
  assert.ok(productionLoad.json().stations.some((station: any) => station.station === 'Intake' && station.open >= 1), 'E2E station load reflects durable intake work');
  const productionWorkload = await app.inject({ method: 'GET', url: '/api/laundry/production-workload', headers: sessionHeaders });
  assert.equal(productionWorkload.statusCode, 200, 'E2E production workload guidance loads');
  assert.equal(Array.isArray(productionWorkload.json().recommendations), true, 'E2E workload guidance returns deterministic recommendations');
  const productionMetrics = await app.inject({ method: 'GET', url: '/api/laundry/production-supervisor-metrics', headers: sessionHeaders });
  assert.equal(productionMetrics.statusCode, 200, 'E2E supervisor production metrics are available');
  assert.ok(productionMetrics.json().total >= 1, 'E2E supervisor metrics include durable task totals');
  assert.equal(Array.isArray(productionMetrics.json().stations), true, 'E2E supervisor metrics include station breakdowns');
  assert.equal(typeof productionMetrics.json().completionRatePercent, 'number', 'E2E supervisor metrics include completion rate');
  assert.equal(typeof productionMetrics.json().cycleSamples, 'number', 'E2E supervisor metrics expose valid cycle sample count');
  const filteredProductionMetrics = await app.inject({ method: 'GET', url: '/api/laundry/production-supervisor-metrics?from=2026-09-04&to=2026-09-04', headers: sessionHeaders });
  assert.equal(filteredProductionMetrics.statusCode, 200, 'E2E supervisor metrics accept a created-date window');
  const productionSchedule = await app.inject({ method: 'GET', url: '/api/laundry/production-schedule', headers: sessionHeaders });
  assert.equal(productionSchedule.statusCode, 200, 'E2E forward production schedule loads');
  assert.ok(productionSchedule.json().totalTasks >= 1, 'E2E forward schedule includes durable open work');
  assert.equal(productionSchedule.json().scheduledTasks + productionSchedule.json().unscheduledTasks, productionSchedule.json().totalTasks, 'E2E forward schedule reconciles dated and undated work');
  const filteredProductionSchedule = await app.inject({ method: 'GET', url: '/api/laundry/production-schedule?from=2026-09-04&to=2026-09-04', headers: sessionHeaders });
  assert.equal(filteredProductionSchedule.statusCode, 200, 'E2E forward schedule accepts a delivery-date window');
  assert.ok(filteredProductionSchedule.json().scheduledTasks >= 1, 'E2E date-window schedule retains commitments in range');
  const hardwareStatus = await app.inject({ method: 'GET', url: '/api/ops/hardware-status', headers: sessionHeaders });
  assert.equal(hardwareStatus.statusCode, 200, 'E2E hardware status projection is available to support users');
  assert.equal(hardwareStatus.json().some((item: any) => item.kind === 'receipt-printer'), true, 'E2E hardware status includes the native print boundary');
  const cashCloseDrill = await app.inject({ method: 'GET', url: '/api/laundry/cash-close-drill', headers: sessionHeaders });
  assert.equal(cashCloseDrill.statusCode, 200, 'E2E cash-close drill endpoint is available to reports users');
  assert.equal(cashCloseDrill.json().currency, 'INR', 'E2E cash-close drill declares its fixed currency');
  const packageLiability = await app.inject({ method: 'GET', url: '/api/laundry/package-liability', headers: sessionHeaders });
  assert.equal(packageLiability.statusCode, 200, 'E2E package liability control is available to package readers');
  assert.equal(packageLiability.json().currency, 'INR', 'E2E package liability control declares its fixed currency');
  const capacitySave = await app.inject({ method: 'POST', url: '/api/settings/store', headers: sessionHeaders, payload: { stationCapacities: { Intake: 1 } } });
  assert.equal(capacitySave.statusCode, 200, 'E2E owner can persist station capacity targets');
  const capacityLoad = await app.inject({ method: 'GET', url: '/api/laundry/production-load', headers: sessionHeaders });
  const intakeLoad = capacityLoad.json().stations.find((station: any) => station.station === 'Intake');
  assert.equal(intakeLoad.capacity, 1, 'E2E station load returns the configured capacity target');
  assert.equal(intakeLoad.atCapacity, intakeLoad.open >= 1, 'E2E station load truthfully flags a reached target');
  const overdueDate = new Date(Date.now() - 86_400_000).toISOString().slice(0, 10);
  const overdueBooking = await app.inject({ method: 'POST', url: '/api/laundry/orders', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-booking-overdue-001' }, payload: { ...body, customer: { name: 'E2E Overdue', phone: '9000000779' }, expectedDeliveryDate: overdueDate } });
  assert.equal(overdueBooking.statusCode, 201, 'E2E overdue fixture booking succeeds');
  const outOfOrderPrintTag = await app.inject({ method: 'POST', url: '/api/laundry/print-jobs', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-print-job-out-of-order-001' }, payload: { orderId: booked.json().order.id, documentType: 'garment-tags', tagIds: [overdueBooking.json().garmentUnits[0].tagCode], requestedCopies: 1 } });
  assert.equal(outOfOrderPrintTag.statusCode, 400, 'E2E print job rejects a tag belonging to another order');
  const overdueQueue = await app.inject({ method: 'GET', url: '/api/laundry/production-queue?overdue=true', headers: sessionHeaders });
  assert.ok(overdueQueue.json().some((task: any) => task.orderId === overdueBooking.json().order.id && task.overdue === true), 'E2E production queue identifies an SLA-overdue task');
  const overdueTask = overdueQueue.json().find((task: any) => task.orderId === overdueBooking.json().order.id);
  const workloadAssignment = await app.inject({ method: 'POST', url: '/api/laundry/production-workload/assign', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-production-workload-assign-001' }, payload: { taskIds: [overdueTask.id] } });
  assert.equal(workloadAssignment.statusCode, 200, 'E2E supervised workload assignment command succeeds');
  assert.equal(workloadAssignment.json().assigned.length, 1, 'E2E workload assignment selects an eligible branch operator');
  const workloadAssignmentReplay = await app.inject({ method: 'POST', url: '/api/laundry/production-workload/assign', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-production-workload-assign-001' }, payload: { taskIds: [overdueTask.id] } });
  assert.equal(workloadAssignmentReplay.statusCode, 200, 'E2E workload assignment retry is idempotent');
  const productionTaskId = productionQueue.json()[0].id;
  const assignedTask = await app.inject({ method: 'POST', url: `/api/laundry/production-tasks/${productionTaskId}/assign`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-production-assign-001' }, payload: { assignedTo: 'E2E Operator' } });
  assert.equal(assignedTask.statusCode, 200, 'E2E processing operator can assign a production task');
  const assignedTaskReplay = await app.inject({ method: 'POST', url: `/api/laundry/production-tasks/${productionTaskId}/assign`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-production-assign-001' }, payload: { assignedTo: 'E2E Operator' } });
  assert.equal(assignedTaskReplay.statusCode, 200, 'E2E production assignment replay is idempotent');
  const startedTask = await app.inject({ method: 'POST', url: `/api/laundry/production-tasks/${productionTaskId}/start`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-production-start-001' } });
  assert.equal(startedTask.statusCode, 200, 'E2E production operator can start an intake task');
  const startedTaskReplay = await app.inject({ method: 'POST', url: `/api/laundry/production-tasks/${productionTaskId}/start`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-production-start-001' } });
  assert.equal(startedTaskReplay.statusCode, 200, 'E2E production start replay is idempotent');
  const tag = booked.json().garmentUnits[0].tagCode;
  for (const [index, state] of ['Sorted', 'Processing', 'QC'].entries()) {
    const scan = await app.inject({ method: 'POST', url: '/api/laundry/garment-units/scan', headers: { ...sessionHeaders, 'idempotency-key': `e2e-qc-scan-${index}` }, payload: { tagCode: tag, nextState: state, location: `${state} station`, note: `E2E handoff to ${state}` } });
    assert.equal(scan.statusCode, 201, `E2E garment scan advances to ${state}`);
  }
  const claim = await app.inject({ method: 'POST', url: '/api/laundry/quality-claims', headers: sessionHeaders, payload: { garmentUnitId: tag, category: 'Stain', severity: 'High', description: 'E2E stain observed during QC' } });
  assert.equal(claim.statusCode, 201, 'E2E QC claim opens against a physical tag');
  const claimDecision = await app.inject({ method: 'POST', url: `/api/laundry/quality-claims/${claim.json().id}/resolve`, headers: sessionHeaders, payload: { decision: 'Rewash', note: 'E2E rewash disposition recorded' } });
  assert.equal(claimDecision.statusCode, 200, 'E2E supervisor resolves QC claim and records disposition');
  assert.equal(claimDecision.json().state, 'Rewash', 'E2E rewash disposition advances garment state');
  const corrections = await app.inject({ method: 'GET', url: '/api/laundry/customer-corrections', headers: sessionHeaders });
  assert.equal(corrections.statusCode, 200, 'E2E customer correction register loads for print delivery');
  assert.ok(corrections.json().some((entry: any) => entry.claimId === claim.json().id && entry.status === 'Issued'), 'E2E terminal quality decision exposes its immutable customer correction document');
  const qualityTelemetry = await app.inject({ method: 'GET', url: '/api/laundry/quality-analytics', headers: sessionHeaders });
  assert.equal(qualityTelemetry.statusCode, 200, 'E2E quality analytics loads from durable claims');
  assert.equal(qualityTelemetry.json().rewashClaims >= 1, true, 'E2E quality analytics counts rewash dispositions');
  const collected = await app.inject({ method: 'POST', url: `/api/laundry/orders/${orderId}/payments`, headers: { ...sessionHeaders, 'idempotency-key': 'e2e-payment-001' }, payload: { amount: 10, mode: 'UPI', reference: 'E2E-UPI-001' } });
  assert.equal(collected.statusCode, 201, 'E2E partial payment collection succeeds');
  const progress = await app.inject({ method: 'POST', url: `/api/laundry/orders/${orderId}/fulfillment`, headers: sessionHeaders, payload: { itemIndex: 0, stage: 'Picked Up', quantity: 1 } });
  assert.equal(progress.statusCode, 201, 'E2E partial fulfilment event succeeds');
  const rider = await app.inject({ method: 'POST', url: '/api/laundry/riders', headers: sessionHeaders, payload: { name: 'E2E Rider', phone: '9000000780' } });
  assert.equal(rider.statusCode, 201, 'E2E rider creation succeeds');
  const settlementHeaders = { ...sessionHeaders, 'idempotency-key': 'e2e-settlement-001' };
  const settlement = await app.inject({ method: 'POST', url: '/api/laundry/rider-settlements', headers: settlementHeaders, payload: { rider: rider.json().id, amount: 10, method: 'Cash' } });
  const duplicateSettlement = await app.inject({ method: 'POST', url: '/api/laundry/rider-settlements', headers: settlementHeaders, payload: { rider: rider.json().id, amount: 10, method: 'Cash' } });
  assert.equal(settlement.statusCode, 201, 'E2E rider settlement succeeds');
  assert.equal(duplicateSettlement.json().id, settlement.json().id, 'E2E duplicate rider settlement is idempotent');
  const stats = await app.inject({ method: 'GET', url: '/api/laundry/statistics?period=week', headers: sessionHeaders });
  assert.equal(stats.statusCode, 200, 'E2E statistics overview loads');
  assert.equal(stats.json().collection.daily.length, 7, 'E2E statistics returns a seven-day collection series');
  const report = await app.inject({ method: 'GET', url: '/api/laundry/reports/collection', headers: sessionHeaders });
  assert.equal(report.statusCode, 200, 'E2E collection report loads');
  assert.equal(report.json().kind, 'collection', 'E2E report response identifies its requested view');
  const pagedReport = await app.inject({ method: 'GET', url: '/api/laundry/reports/collection?page=1&pageSize=1', headers: sessionHeaders });
  assert.equal(pagedReport.statusCode, 200, 'E2E paginated collection report loads');
  assert.equal(pagedReport.json().page, 1, 'E2E report returns the requested page');
  assert.equal(pagedReport.json().pageSize, 1, 'E2E report enforces the requested bounded page size');
  assert.equal(pagedReport.json().totalRows >= pagedReport.json().rows.length, true, 'E2E report exposes total rows separately from the page');
  const exportedReport = await app.inject({ method: 'GET', url: '/api/laundry/reports/collection/export', headers: sessionHeaders });
  assert.equal(exportedReport.statusCode, 200, 'E2E capped report export loads');
  assert.equal(exportedReport.json().exportAll, true, 'E2E report export is explicitly marked as export-all');
  assert.equal(exportedReport.json().rows.length <= 5000, true, 'E2E report export enforces the five-thousand-row safety cap');
  assert.equal(exportedReport.json().totalRows >= exportedReport.json().rows.length, true, 'E2E report export preserves the untruncated total row count');
  const queuedExport = await app.inject({ method: 'POST', url: '/api/laundry/report-exports', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-report-export-001' }, payload: { kind: 'collection' } });
  assert.equal(queuedExport.statusCode, 202, 'E2E large report export can be queued');
  const exportJob = await waitForExport(app, queuedExport.json().id, sessionHeaders);
  assert.equal(exportJob.status, 'Completed', 'E2E queued report export completes asynchronously');
  assert.equal(exportJob.executor, 'worker_thread', 'E2E report export is executed in a dedicated worker thread');
  assert.equal(typeof exportJob.fileName, 'string', 'E2E completed report export persists a safe file name');
  const queuedDownload = await app.inject({ method: 'GET', url: `/api/laundry/report-exports/${exportJob.id}/download`, headers: sessionHeaders });
  assert.equal(queuedDownload.statusCode, 200, 'E2E completed report export can be downloaded');
  assert.match(String(queuedDownload.headers['content-type']), /text\/csv/, 'E2E report export download is CSV');
  assert.match(queuedDownload.body, /^\uFEFF[^\r\n]+\r\n/, 'E2E report export preserves a BOM-prefixed CSV header');
  assert.equal(queuedDownload.body.endsWith('\r\n'), true, 'E2E report export uses deterministic CRLF termination');
  const cursorExport = await app.inject({ method: 'POST', url: '/api/laundry/report-exports', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-report-export-cursor-001' }, payload: { kind: 'invoice' } });
  assert.equal(cursorExport.statusCode, 202, 'E2E row-oriented report export can be queued for cursor execution');
  const cursorJob = await waitForExport(app, cursorExport.json().id, sessionHeaders);
  assert.equal(cursorJob.status, 'Completed', 'E2E cursor-backed report export completes asynchronously');
  assert.equal(cursorJob.executor, 'worker_thread_cursor', 'E2E row-oriented export records cursor-backed worker execution');
  assert.equal(cursorJob.totalRows >= 1, true, 'E2E cursor-backed export reports rows written from the iterator');
  const savedView = await app.inject({ method: 'POST', url: '/api/laundry/report-views', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-report-view-001' }, payload: { name: 'Weekly collections', kind: 'collection', from: '2026-08-01', to: '2026-08-31', search: 'UPI', shared: true } });
  assert.equal(savedView.statusCode, 201, 'E2E owner can save a report view');
  assert.equal(savedView.json().shared, true, 'E2E owner can share a report view');
  const savedViewRetry = await app.inject({ method: 'POST', url: '/api/laundry/report-views', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-report-view-001' }, payload: { name: 'Weekly collections', kind: 'collection', from: '2026-08-01', to: '2026-08-31', search: 'UPI', shared: true } });
  assert.equal(savedViewRetry.json().id, savedView.json().id, 'E2E saved report view creation is idempotent');
  const savedViews = await app.inject({ method: 'GET', url: '/api/laundry/report-views', headers: sessionHeaders });
  assert.ok(savedViews.json().some((view: any) => view.id === savedView.json().id && view.from === '2026-08-01'), 'E2E owner can list saved report views');
  const deletedView = await app.inject({ method: 'DELETE', url: `/api/laundry/report-views/${savedView.json().id}`, headers: sessionHeaders });
  assert.equal(deletedView.statusCode, 200, 'E2E saved report view can be archived by its owner');
  assert.equal((await app.inject({ method: 'GET', url: '/api/laundry/report-views', headers: sessionHeaders })).json().some((view: any) => view.id === savedView.json().id), false, 'E2E archived saved view is not listed');
  const normalization = await app.inject({ method: 'GET', url: '/api/ops/financial-normalization', headers: sessionHeaders });
  assert.equal(normalization.statusCode, 200, 'E2E owner can preview financial normalization');
  assert.equal(normalization.json().invalid, 0, 'E2E healthy financial sources have valid paise amounts');
  const normalizationApply = await app.inject({ method: 'POST', url: '/api/ops/financial-normalization', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-financial-normalization-001' }, payload: {} });
  assert.equal(normalizationApply.statusCode, 200, 'E2E owner can apply an idempotent financial normalization pass');
  assert.equal(normalizationApply.json().certified, true, 'E2E normalization response carries a clean reconciliation certificate');
  assert.match(normalizationApply.json().runId, /^norm:/, 'E2E normalization response carries a durable evidence run id');
  const normalizationEvidence = await app.inject({ method: 'GET', url: '/api/ops/financial-normalization', headers: sessionHeaders });
  assert.equal(normalizationEvidence.json().latestCertifiedRun?.id, normalizationApply.json().runId, 'E2E normalization preview exposes the latest certified evidence run');
  const compatibilityAudit = await app.inject({ method: 'GET', url: '/api/ops/compatibility-audit', headers: sessionHeaders });
  assert.equal(compatibilityAudit.statusCode, 200, 'E2E owner can inspect compatibility-retirement readiness');
  assert.equal(compatibilityAudit.json().format, 'epic-laundry-compatibility-retirement-audit', 'E2E compatibility audit has a stable evidence format');
  assert.equal(Array.isArray(compatibilityAudit.json().items), true, 'E2E compatibility audit returns entity-level rows');
  assert.equal(compatibilityAudit.json().items.some((item: any) => Object.prototype.hasOwnProperty.call(item, 'data_json')), false, 'E2E compatibility audit excludes generic payload contents');
  const editable = await app.inject({ method: 'POST', url: '/api/laundry/orders', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-booking-editable-001' }, payload: { ...body, customer: { name: 'E2E Offline Edit', phone: '9000000776' } } });
  const offlineEdit = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'laundry_order_edit', clientId: 'offline-edit-001', data: { orderId: editable.json().order.id, items: body.items, expectedDeliveryDate: editable.json().order.expectedDeliveryDate, fulfillmentMode: editable.json().order.fulfillmentMode, charges: 0, discounts: 0, taxRate: 0, notes: 'Edited after counter restart', deliveryAddress: 'Offline edit street', expectedVersion: editable.json().order.version } }] } });
  assert.equal(offlineEdit.json().applied, 1, 'E2E offline replay accepts a versioned controlled order edit');
  assert.equal(offlineEdit.json().results[0].id, editable.json().order.id, 'E2E offline edit returns the order identity');
  const cancellable = await app.inject({ method: 'POST', url: '/api/laundry/orders', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-booking-002' }, payload: { ...body, customer: { name: 'E2E Cancellation', phone: '9000000778' }, paymentMode: 'Cash' } });
  const cancelled = await app.inject({ method: 'POST', url: '/api/sync/push', headers: sessionHeaders, payload: { docs: [{ entity: 'laundry_order_cancel', clientId: 'offline-cancel-001', data: { orderId: cancellable.json().order.id, reason: 'E2E customer cancellation', expectedVersion: cancellable.json().order.version } }] } });
  assert.equal(cancelled.json().applied, 1, 'E2E offline versioned cancellation succeeds');
  assert.equal(cancelled.json().results[0].id, cancellable.json().order.id, 'E2E offline cancellation returns the order identity');
  const backup = await app.inject({ method: 'GET', url: '/api/ops/backup', headers: sessionHeaders });
  assert.equal(backup.statusCode, 200, 'E2E owner backup succeeds');
  const backupBody = backup.json();
  assert.ok(backupBody.rows.length > 0, 'E2E backup contains operational rows');
  assert.ok(backupBody.financialEntries.length >= 1, 'E2E backup contains canonical integer-paise financial entries');
  assert.ok(backupBody.financialDocuments.length >= 2, 'E2E backup contains normalized financial documents');
  assert.ok(Array.isArray(backupBody.cashShiftCloses), 'E2E backup carries normalized cash-close records');
  assert.equal(backupBody.backupFormat, 'epic-laundry-backup', 'E2E backup carries a versioned envelope');
  assert.match(backupBody.checksum, /^[a-f0-9]{64}$/, 'E2E backup carries a SHA-256 checksum');
  const verifiedBackup = await app.inject({ method: 'POST', url: '/api/ops/restore/verify', headers: sessionHeaders, payload: backupBody });
  assert.equal(verifiedBackup.statusCode, 200, 'E2E valid backup can be verified without mutation');
  assert.equal(verifiedBackup.json().rows, backupBody.rows.length, 'E2E backup verification reports the source row count');
  assert.equal(verifiedBackup.json().cashShiftCloses, backupBody.cashShiftCloses.length, 'E2E backup verification reports normalized cash-close count');
  const restored = await app.inject({ method: 'POST', url: '/api/ops/restore', headers: sessionHeaders, payload: backupBody });
  assert.equal(restored.statusCode, 200, 'E2E versioned backup restores into the same workspace');
  const postRestoreReplay = await app.inject({ method: 'POST', url: '/api/laundry/orders', headers: { ...sessionHeaders, 'idempotency-key': 'e2e-booking-001' }, payload: body });
  assert.equal(postRestoreReplay.statusCode, 201, 'E2E restore clears stale idempotency commands before accepting new work');
  assert.notEqual(postRestoreReplay.json().order.id, booked.json().order.id, 'E2E post-restore reuse of an old key cannot return a pre-restore result');
  const encrypted = await app.inject({ method: 'POST', url: '/api/ops/backup/encrypted', headers: sessionHeaders, payload: { passphrase: 'E2E Correct Horse 2026' } });
  assert.equal(encrypted.statusCode, 200, 'E2E encrypted backup succeeds');
  const encryptedBody = encrypted.json();
  assert.equal(encryptedBody.backupFormat, 'epic-laundry-encrypted-backup', 'E2E encrypted backup carries its format');
  assert.equal(typeof encryptedBody.ciphertext, 'string', 'E2E encrypted backup contains ciphertext');
  assert.equal('rows' in encryptedBody, false, 'E2E encrypted backup never exposes plaintext rows');
  const encryptedVerification = await app.inject({ method: 'POST', url: '/api/ops/restore/encrypted/verify', headers: sessionHeaders, payload: { backup: encryptedBody, passphrase: 'E2E Correct Horse 2026' } });
  assert.equal(encryptedVerification.statusCode, 200, 'E2E encrypted backup can be verified without mutation');
  const encryptedRestored = await app.inject({ method: 'POST', url: '/api/ops/restore/encrypted', headers: sessionHeaders, payload: { backup: encryptedBody, passphrase: 'E2E Correct Horse 2026' } });
  assert.equal(encryptedRestored.statusCode, 200, 'E2E encrypted backup restores into the same workspace');
  const tampered = await app.inject({ method: 'POST', url: '/api/ops/restore', headers: sessionHeaders, payload: { ...backupBody, rows: backupBody.rows.slice(1) } });
  assert.equal(tampered.statusCode, 400, 'E2E tampered backup is rejected by checksum validation');
  const tamperedVerification = await app.inject({ method: 'POST', url: '/api/ops/restore/verify', headers: sessionHeaders, payload: { ...backupBody, rows: backupBody.rows.slice(1) } });
  assert.equal(tamperedVerification.statusCode, 400, 'E2E tampered backup is rejected before restore confirmation');
  await app.close();
  console.log('PASS  authenticated laundry API E2E workflow self-test complete');
} finally {
  closeStore?.();
  rmSync(tempDir, { recursive: true, force: true });
}
