import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const tempDir = mkdtempSync(join(tmpdir(), 'epic-routes-'));
process.env.EPIC_DATA_FILE = join(tempDir, 'legacy.json'); process.env.EPIC_DB_FILE = join(tempDir, 'epic.sqlite'); process.env.EPIC_LEGACY_JSON_FILE = join(tempDir, 'legacy.json');
let closeStore: (() => void) | undefined;
try {
  const { store } = await import('./kernel/store.js'); closeStore = () => store.close();
  const { seedLaundryDefaults, laundryCatalogue, bookLaundryOrder, createLaundryRider, assignLaundryOrder, getLaundryOrder } = await import('./modules/laundry/domain.js');
  const { createRouteRun, createServiceZone, startRouteRun, completeRouteStop, listRouteRuns, listServiceZoneMaster, listServiceZones, routeCoverageAnalytics } = await import('./modules/laundry/routes.js');
  const tenant = 'ROUTES'; const actor = 'route-owner'; store.withStoreScope(tenant, 'STORE-DEFAULT', () => seedLaundryDefaults(tenant));
  const catalogue = store.withStoreScope(tenant, 'STORE-DEFAULT', () => laundryCatalogue(tenant)); const garment = catalogue.garments.find((item: any) => item.unit === 'Piece')!; const service = catalogue.services[0];
  const rider = store.withStoreScope(tenant, 'STORE-DEFAULT', () => createLaundryRider(tenant, actor, { name: 'Route Rider', phone: '9000000999' }));
  const otherRider = store.withStoreScope(tenant, 'STORE-DEFAULT', () => createLaundryRider(tenant, actor, { name: 'Other Route Rider', phone: '9000000997' }));
  const zoneMaster = store.withStoreScope(tenant, 'STORE-DEFAULT', () => createServiceZone(tenant, actor, { name: 'North', code: 'NORTH', pickupWindow: '09:00-12:00', deliveryWindow: '16:00-20:00' }));
  assert.equal(zoneMaster.active, true, 'service-zone master starts active');
  assert.deepEqual(store.withStoreScope(tenant, 'STORE-DEFAULT', () => listServiceZoneMaster(tenant)), [zoneMaster], 'service-zone master is persisted in the branch scope');
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => createServiceZone(tenant, actor, { name: 'Northern', code: 'NORTH' })), /code already exists/, 'service-zone master codes are unique within a branch');
  const order = store.withStoreScope(tenant, 'STORE-DEFAULT', () => bookLaundryOrder(tenant, actor, { customer: { name: 'Route Customer', phone: '9000000998', address: '12 Route Street' }, items: [{ garment: garment.id, service: service.id, qty: 1 }], expectedDeliveryDate: '2026-09-07', fulfillmentMode: 'Pickup Order', serviceZone: 'North' }));
  assert.equal(order.order.serviceZone, 'North', 'booking persists the service zone for dispatch planning');
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => assignLaundryOrder(tenant, actor, order.order.id, { stage: 'pickup', riderId: rider.id, slot: '09:00-10:00' }));
  const run = store.withStoreScope(tenant, 'STORE-DEFAULT', () => createRouteRun(tenant, actor, { riderId: rider.id, stage: 'Pickup', routeDate: '2026-09-01', zone: 'north', startTime: '09:30', minutesPerStop: 20, orderIds: [order.order.id] }));
  assert.equal(run.stopCount, 1, 'route run contains one validated stop');
  assert.equal(run.zone, 'North', 'route run resolves the requested zone through the active master');
  assert.equal(run.startTime, '09:30', 'route run persists the planned start time');
  assert.equal(run.minutesPerStop, 20, 'route run persists the ETA cadence');
  assert.equal(run.stops[0].estimatedAt, '2026-09-01T09:30:00', 'route stop exposes a deterministic planned ETA');
  const plannedAnalytics = store.withStoreScope(tenant, 'STORE-DEFAULT', () => routeCoverageAnalytics(tenant));
  assert.deepEqual(plannedAnalytics.totals, { orders: 1, zones: 1, routes: 1, activeRoutes: 1, stops: 1, completedStops: 0, completionPercent: 0 }, 'route analytics summarizes scoped order and run workload');
  assert.deepEqual(plannedAnalytics.zones[0], { zone: 'North', orders: 1, pickupReady: 1, deliveryReady: 0, assigned: 1, activeRuns: 1 }, 'route analytics groups service-zone readiness and assignments');
  assert.deepEqual(store.withStoreScope(tenant, 'STORE-DEFAULT', () => listServiceZones(tenant)), ['North'], 'service-zone suggestions include the scoped master data');
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => createRouteRun(tenant, actor, { riderId: rider.id, stage: 'Pickup', routeDate: '2026-09-01', zone: 'Unknown', orderIds: [order.order.id] })), /active service-zone master/, 'route creation rejects unknown zones once a master is configured');
  const otherOrder = store.withStoreScope(tenant, 'STORE-DEFAULT', () => bookLaundryOrder(tenant, actor, { customer: { name: 'Other Route Customer', phone: '9000000996', address: 'East Route Street' }, items: [{ garment: garment.id, service: service.id, qty: 1 }], expectedDeliveryDate: '2026-09-07', fulfillmentMode: 'Pickup Order', serviceZone: 'East' }));
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => assignLaundryOrder(tenant, actor, otherOrder.order.id, { stage: 'pickup', riderId: otherRider.id }));
  assert.deepEqual(store.withStoreScope(tenant, 'STORE-DEFAULT', () => listServiceZones(tenant, rider.id)), ['North'], 'rider zone suggestions exclude another rider\'s assigned area');
  assert.equal(store.withStoreScope(tenant, 'STORE-DEFAULT', () => listRouteRuns(tenant, { zone: 'NORTH' }).length), 1, 'route history filters service zones case-insensitively');
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => startRouteRun(tenant, actor, run.id, 'different-rider')), /assigned route/, 'rider ownership is enforced when starting a route');
  const started = store.withStoreScope(tenant, 'STORE-DEFAULT', () => startRouteRun(tenant, actor, run.id, rider.id)); assert.equal(started.status, 'In Progress', 'assigned rider can start the planned route');
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => completeRouteStop(tenant, actor, run.id, run.stops[0].id, { status: 'Completed' }, 'different-rider')), /assigned route/, 'rider ownership is enforced when completing a stop');
  const completed = store.withStoreScope(tenant, 'STORE-DEFAULT', () => completeRouteStop(tenant, actor, run.id, run.stops[0].id, { status: 'Completed' }, rider.id));
  assert.equal(completed.status, 'Completed', 'last stop closes the route');
  const completedAnalytics = store.withStoreScope(tenant, 'STORE-DEFAULT', () => routeCoverageAnalytics(tenant, rider.id));
  assert.equal(completedAnalytics.totals.completionPercent, 100, 'route analytics reports completed stop coverage for a rider');
  assert.equal(completedAnalytics.totals.activeRoutes, 0, 'completed route is removed from active workload');
  assert.equal(store.withStoreScope(tenant, 'STORE-DEFAULT', () => getLaundryOrder(tenant, order.order.id).state), 'Picked Up', 'completed pickup stop advances the order lifecycle');
  assert.equal(store.withStoreScope(tenant, 'STORE-DEFAULT', () => listRouteRuns(tenant, { status: 'Completed' }).length), 1, 'completed route remains in the route history');
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => createRouteRun(tenant, actor, { riderId: rider.id, stage: 'Pickup', routeDate: '2026-09-01', orderIds: [order.order.id] })), /not eligible/, 'route creation rejects an order no longer eligible for pickup');
  console.log('PASS  route planning, stop completion, lifecycle transition, and duplicate protection self-test complete');
} finally { closeStore?.(); rmSync(tempDir, { recursive: true, force: true }); }
