import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const tempDir = mkdtempSync(join(tmpdir(), 'epic-cash-shift-'));
process.env.EPIC_DATA_FILE = join(tempDir, 'legacy.json'); process.env.EPIC_DB_FILE = join(tempDir, 'epic.sqlite'); process.env.EPIC_LEGACY_JSON_FILE = join(tempDir, 'legacy.json');
let closeStore: (() => void) | undefined;
try {
  const { store } = await import('./kernel/store.js'); closeStore = () => store.close();
  const { openCashShift, closeCashShift, getCurrentCashShift, listCashShifts } = await import('./modules/laundry/cash.js');
  const { bookLaundryOrder, createLaundryExpense, laundryCatalogue, seedLaundryDefaults } = await import('./modules/laundry/domain.js');
  const tenant = 'CASH-SHIFT'; const actor = 'cash-owner';
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => seedLaundryDefaults(tenant));
  const catalogue = store.withStoreScope(tenant, 'STORE-DEFAULT', () => laundryCatalogue(tenant));
  const garment = catalogue.garments[0]; const service = catalogue.services.find((candidate: any) => catalogue.prices.some((price: any) => price.garment === garment.id && price.service === candidate.id))!;
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => openCashShift(tenant, actor, { openingCash: '100.00', register: 'Main counter' }));
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => closeCashShift(tenant, actor, {})), /counted cash is required/, 'a shift cannot close without a physical count');
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => openCashShift(tenant, actor, { openingCash: 1 })), /already open/, 'a store cannot open two concurrent cash shifts');
  const order = store.withStoreScope(tenant, 'STORE-DEFAULT', () => bookLaundryOrder(tenant, actor, { customer: { name: 'Cash Customer', phone: '9000000998' }, items: [{ garment: garment.id, service: service.id, qty: 1 }], expectedDeliveryDate: '2026-09-08', fulfillmentMode: 'Home Delivery', paymentMode: 'Cash' }));
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => createLaundryExpense(tenant, actor, { expenseName: 'Cash supplies', expenseDate: '2026-09-08', amount: '5.00', paymentMode: 'Cash' }));
  const beforeClose = store.withStoreScope(tenant, 'STORE-DEFAULT', () => getCurrentCashShift(tenant));
  assert.equal(beforeClose?.expectedCash, 100 + order.order.grandTotal - 5, 'expected cash includes only this shift cash movements');
  const closed = store.withStoreScope(tenant, 'STORE-DEFAULT', () => closeCashShift(tenant, actor, { countedCash: beforeClose?.expectedCash, note: 'Counted and matched' }));
  assert.equal(closed?.status, 'Closed', 'cash close is persisted as a terminal shift'); assert.equal(closed?.variance, 0, 'matching count produces zero variance');
  const closeRows = store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.listCashShiftCloses(tenant));
  assert.equal(closeRows.length, 1, 'every closed shift has one normalized close record');
  assert.equal(closeRows[0].countedCashPaise, Math.round(Number(beforeClose?.expectedCash || 0) * 100), 'normalized close keeps fixed-scale counted cash');
  assert.equal(closeRows[0].expectedCashPaise, closeRows[0].openingCashPaise + closeRows[0].collectionsPaise - closeRows[0].expensesPaise - closeRows[0].refundsPaise, 'normalized close preserves the reconciliation equation');
  assert.equal(store.withStoreScope(tenant, 'STORE-DEFAULT', () => getCurrentCashShift(tenant)), null, 'closed shift is no longer current');
  assert.equal(store.withStoreScope(tenant, 'STORE-DEFAULT', () => listCashShifts(tenant).filter((row) => row?.status === 'Closed').length), 1, 'closed shift remains in immutable history');
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => openCashShift(tenant, actor, { openingCash: '20.00', register: 'Main counter' }));
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => closeCashShift(tenant, actor, { countedCash: '19.00', note: 'Short till' })), /supervisor approval/, 'non-zero variance requires explicit supervisor approval');
  const approved = store.withStoreScope(tenant, 'STORE-DEFAULT', () => closeCashShift(tenant, actor, { countedCash: '19.00', note: 'Short till investigated', supervisorApproved: true, supervisorActor: 'owner-supervisor' }));
  assert.equal(approved?.variance, -1, 'approved cash variance is persisted in paise-backed arithmetic');
  assert.equal(approved?.varianceApprovedBy, 'owner-supervisor', 'variance approval actor is retained for audit');
  assert.equal(store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.listCashShiftCloses(tenant).find((close) => close.shiftId === approved?.id)?.variancePaise), -100, 'normalized close records preserve negative variance in paise');
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => openCashShift(tenant, actor, { openingCash: '20.00', register: 'Main counter' }));
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => openCashShift(tenant, actor, { openingCash: '30.00', register: 'Side counter' }));
  const sideOrder = store.withStoreScope(tenant, 'STORE-DEFAULT', () => bookLaundryOrder(tenant, actor, { customer: { name: 'Side Counter Customer', phone: '9000000997' }, items: [{ garment: garment.id, service: service.id, qty: 1 }], expectedDeliveryDate: '2026-09-08', fulfillmentMode: 'Pickup Order', paymentMode: 'Cash', cashRegister: 'Side counter' }));
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => createLaundryExpense(tenant, actor, { expenseName: 'Side counter supplies', expenseDate: '2026-09-08', amount: '5.00', paymentMode: 'Cash', cashRegister: 'Side counter' }));
  const mainOpen = store.withStoreScope(tenant, 'STORE-DEFAULT', () => getCurrentCashShift(tenant, 'Main counter'));
  const sideOpen = store.withStoreScope(tenant, 'STORE-DEFAULT', () => getCurrentCashShift(tenant, 'Side counter'));
  assert.equal(mainOpen?.expectedCash, 20, 'main register remains isolated from side-register movements');
  assert.equal(sideOpen?.expectedCash, 30 + sideOrder.order.grandTotal - 5, 'side-register cash movements are attributed to the named shift');
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => bookLaundryOrder(tenant, actor, { customer: { name: 'Ambiguous Cash Customer', phone: '9000000996' }, items: [{ garment: garment.id, service: service.id, qty: 1 }], expectedDeliveryDate: '2026-09-08', fulfillmentMode: 'Pickup Order', paymentMode: 'Cash' })), /register is required/, 'cash booking requires a register when multiple shifts are open');
  assert.throws(() => store.withStoreScope(tenant, 'STORE-DEFAULT', () => closeCashShift(tenant, actor, { countedCash: '20.00', note: 'Ambiguous close' })), /register is required/, 'cash close requires a register when multiple shifts are open');
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => closeCashShift(tenant, actor, { register: 'Side counter', countedCash: sideOpen?.expectedCash, note: 'Side counter counted' }));
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => closeCashShift(tenant, actor, { register: 'Main counter', countedCash: mainOpen?.expectedCash, note: 'Main counter counted' }));
  console.log('PASS  cash shift opening, movement capture, and closing reconciliation self-test complete');
} finally { closeStore?.(); rmSync(tempDir, { recursive: true, force: true }); }
