import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const dir = mkdtempSync(join(tmpdir(), 'epic-marketplace-pickup-')); process.env.EPIC_DB_FILE = join(dir, 'epic.sqlite'); let close: (() => void) | undefined;
try {
  const { store } = await import('./kernel/store.js'); const { createDeviceEnrollment, registerMarketplaceDevice, receiveMarketplaceOrder } = await import('./modules/marketplace/edge-sync.js'); const { scheduleMarketplacePickup, completeMarketplacePickup } = await import('./modules/marketplace/pickup.js'); const { customerFacingOrderStatus } = await import('./modules/marketplace/customer-status.js');
  close = () => store.close(); const tenant = 'PICKUP'; const storeId = 'STORE-PICKUP'; const run = <T>(work: () => T) => store.withStoreScope(tenant, storeId, work); const enrollment = run(() => createDeviceEnrollment()); run(() => registerMarketplaceDevice(tenant, 'owner', { deviceId: enrollment.deviceId, vendorId: 'VENDOR-PICKUP', publicKey: enrollment.publicKey, credentialRef: 'sim://pickup', status: 'Registered' }));
  run(() => receiveMarketplaceOrder(tenant, 'owner', { eventId: 'pickup-inbound-1', source: 'simulator', tenantId: tenant, vendorId: 'VENDOR-PICKUP', storeId, deviceId: enrollment.deviceId, aggregateType: 'marketplace_order', aggregateId: 'EXT-PICKUP-1', aggregateVersion: 1, eventType: 'marketplace.order.assigned.v1', eventVersion: 1, occurredAt: new Date().toISOString(), payload: { externalOrderId: 'EXT-PICKUP-1', channel: 'MARKETPLACE', state: 'Accepted', orderNumber: 'PICKUP-1', customer: { name: 'Pickup Customer' }, pickup: { address: '12 Offline Lane', requestedSlot: '10:00-12:00' }, request: {} } }));
  const scheduled = run(() => scheduleMarketplacePickup(tenant, 'owner', { externalOrderId: 'EXT-PICKUP-1', scheduledDate: '2026-09-04', window: '10:00-12:00', riderId: 'rider-1', serviceZone: 'Central' })); assert.equal(scheduled.task.state, 'Assigned', 'pickup task is assigned when a rider is provided'); assert.equal(scheduled.projection.state, 'PickupScheduled', 'order projection advances to pickup scheduled'); assert.ok(scheduled.event?.eventId, 'pickup scheduling emits a durable outbound event');
  const retry = run(() => scheduleMarketplacePickup(tenant, 'owner', { externalOrderId: 'EXT-PICKUP-1', scheduledDate: '2026-09-04', window: '10:00-12:00', riderId: 'rider-1', serviceZone: 'Central' })); assert.equal(retry.idempotent, true, 'repeated scheduling does not create another pickup task or event'); assert.equal(run(() => customerFacingOrderStatus(tenant, 'EXT-PICKUP-1').status), 'PickupScheduled', 'customer status reflects the scheduled pickup task');
  const collected = run(() => completeMarketplacePickup(tenant, 'rider-1', { externalOrderId: 'EXT-PICKUP-1', state: 'Collected' })); assert.equal(collected.task.state, 'Collected', 'collection is recorded as a local physical event'); assert.ok(collected.projection); assert.equal(collected.projection.state, 'IntakeRequired', 'collected pickup enters physical intake'); assert.equal(run(() => customerFacingOrderStatus(tenant, 'EXT-PICKUP-1').status), 'Received', 'customer status reflects physical pickup collection');
  assert.equal(run(() => completeMarketplacePickup(tenant, 'rider-1', { externalOrderId: 'EXT-PICKUP-1', state: 'Collected' })).idempotent, true, 'collection retry is idempotent'); console.log('PASS marketplace pickup scheduling, rider assignment, collection, projection transition, and retry self-test complete');
} finally { close?.(); rmSync(dir, { recursive: true, force: true }); }
