import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const tempDir = mkdtempSync(join(tmpdir(), 'epic-reconciliation-'));
process.env.EPIC_DATA_FILE = join(tempDir, 'legacy.json');
process.env.EPIC_DB_FILE = join(tempDir, 'epic.sqlite');
process.env.EPIC_LEGACY_JSON_FILE = join(tempDir, 'legacy.json');
let closeStore: (() => void) | undefined;
try {
  const { store } = await import('./kernel/store.js');
  closeStore = () => store.close();
  const { bookLaundryOrder, laundryCatalogue, laundryStatistics, presentOrder, seedLaundryDefaults } = await import('./modules/laundry/domain.js');
  const { closeCashShift, getCurrentCashShift, openCashShift } = await import('./modules/laundry/cash.js');
  const { cashCloseDrill, laundryFinancialReconciliation } = await import('./modules/laundry/reconciliation.js');
  const tenant = 'RECON';
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => seedLaundryDefaults(tenant));
  const catalogue = store.withStoreScope(tenant, 'STORE-DEFAULT', () => laundryCatalogue(tenant));
  const garment = catalogue.garments[0];
  const service = catalogue.services.find((candidate: any) => catalogue.prices.some((price: any) => price.garment === garment.id && price.service === candidate.id))!;
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => openCashShift(tenant, 'recon-owner', { openingCash: '100.00', register: 'Main' }));
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => bookLaundryOrder(tenant, 'recon-owner', { customer: { name: 'Reconciliation Customer', phone: '9000000999' }, items: [{ garment: garment.id, service: service.id, qty: 1 }], expectedDeliveryDate: '2026-09-07', fulfillmentMode: 'Home Delivery', paymentMode: 'Cash' }));
  const currentShift = store.withStoreScope(tenant, 'STORE-DEFAULT', () => getCurrentCashShift(tenant, 'Main'))!;
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => closeCashShift(tenant, 'recon-owner', { countedCash: currentShift.expectedCash, register: 'Main' }));
  const healthy = store.withStoreScope(tenant, 'STORE-DEFAULT', () => laundryFinancialReconciliation(tenant));
  assert.equal(healthy.status, 'Reconciled', 'healthy invoice, payment, and journal records reconcile');
  assert.equal(healthy.journals.balanced, true, 'posted journals balance in integer paise');
  assert.equal(healthy.cash.closedShiftCount, 1, 'reconciliation reports closed cash shifts');
  assert.equal(healthy.cash.normalizedCloseCount, 1, 'reconciliation includes normalized cash close evidence');
  assert.equal(healthy.cash.totals.expectedPaise, Math.round(currentShift.expectedCash * 100), 'cash reconciliation totals remain fixed-scale');
  const drill = store.withStoreScope(tenant, 'STORE-DEFAULT', () => cashCloseDrill(tenant));
  assert.equal(drill.passed, true, 'cash-close drill proves the normalized drawer equation');
  assert.equal(drill.totalShifts, 1, 'cash-close drill includes the closed shift');
  const canonical = store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.listFinancialEntries(tenant));
  assert.equal(canonical.length, 1, 'cash collection is persisted as one canonical integer-paise entry');
  assert.equal(canonical[0].amountPaise, Math.round(healthy.totals.collected * 100), 'canonical amount matches the reconciled collection');
  const order = store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.rowsOf(tenant, 'laundry_order')[0]);
  const canonicalTotal = store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.financialDocumentAmountPaise(tenant, 'invoice', 'sales_invoice', String(order.data.invoice)));
  assert.ok(canonicalTotal !== undefined, 'invoice has a normalized canonical amount');
  const invoiceSource = store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.getRow(tenant, String(order.data.invoice)));
  assert.equal(invoiceSource?.amountPaise, canonicalTotal, 'invoice source row stores the constrained paise amount');
  const paymentSource = store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.rowsOf(tenant, 'payment_entry')[0]);
  assert.equal(paymentSource?.amountPaise, canonical[0].amountPaise, 'payment source row stores the constrained paise amount');
  order.data.grand_total = 999.99;
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.updateRow(order));
  const authorityView = store.withStoreScope(tenant, 'STORE-DEFAULT', () => presentOrder(tenant, order));
  assert.equal(authorityView.grandTotal, canonicalTotal! / 100, 'order presentation reads the normalized invoice amount instead of mutable compatibility JSON');
  const authorityStats = store.withStoreScope(tenant, 'STORE-DEFAULT', () => laundryStatistics(tenant, 'lifetime'));
  assert.equal(authorityStats.revenue.total, canonicalTotal! / 100, 'overview revenue reads the normalized invoice amount');
  const drift = store.withStoreScope(tenant, 'STORE-DEFAULT', () => laundryFinancialReconciliation(tenant));
  assert.equal(drift.issues.some((issue) => issue.code === 'INVOICE_ORDER_MISMATCH'), true, 'reconciliation flags compatibility JSON drift without changing the canonical amount');
  order.data.grand_total = 12.345;
  store.withStoreScope(tenant, 'STORE-DEFAULT', () => store.updateRow(order));
  const invalid = store.withStoreScope(tenant, 'STORE-DEFAULT', () => laundryFinancialReconciliation(tenant));
  assert.equal(invalid.issues.some((issue) => issue.code === 'INVALID_MONEY'), true, 'reconciliation surfaces over-precise persisted money instead of hiding it');
  console.log('PASS  financial reconciliation and exception reporting self-test complete');
} finally {
  closeStore?.();
  rmSync(tempDir, { recursive: true, force: true });
}
