import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const tempDir = mkdtempSync(join(tmpdir(), 'epic-management-'));
process.env.EPIC_DATA_FILE = join(tempDir, 'legacy.json'); process.env.EPIC_DB_FILE = join(tempDir, 'epic.sqlite');
let closeStore: (() => void) | undefined;
try {
  const { store } = await import('./kernel/store.js'); closeStore = () => store.close();
  const { createRow } = await import('./kernel/entity-service.js');
  const { seedLaundryDefaults, laundryCatalogue, bookLaundryOrder, createLaundryExpense } = await import('./modules/laundry/domain.js');
  const { laundryWorkforceDashboard, markLaundryAttendance, laundryManagementSnapshot } = await import('./modules/laundry/management.js');
  const { requestLaundryReturn, listLaundryReturns } = await import('./modules/laundry/returns.js');
  const { financePolicyReadiness, installIndia2026Baseline, saveEntityFinanceProfile } = await import('./modules/finance/regulatory-policy.js');
  const { calculatePayrollPreview, newRegimeTax2026 } = await import('./modules/finance/payroll-engine.js');
  const { financeCommandCenter } = await import('./modules/finance/intelligence.js');
  const { saveFinancePlanningTarget } = await import('./modules/finance/planning.js');
  const tenant = 'MANAGEMENT'; const actor = 'owner';
  seedLaundryDefaults(tenant);
  const employee = createRow(tenant, actor, 'employee', { name: 'Anita Operator', department: 'Production', designation: 'Press operator', is_active: true });
  const first = markLaundryAttendance(tenant, actor, { employee: employee.id, date: '2026-09-03', status: 'Present', shift: 'Day', workingHours: 8 });
  assert.equal(first.attendance.status, 'Submitted', 'Laundry attendance is submitted evidence, not a draft');
  assert.equal(laundryWorkforceDashboard(tenant, '2026-09-03').statusCounts.Present, 1, 'workforce dashboard derives current capacity from submitted attendance');
  assert.equal(markLaundryAttendance(tenant, actor, { employee: employee.id, date: '2026-09-03', status: 'Present' }).duplicate, true, 'same attendance retry is idempotent');
  assert.throws(() => markLaundryAttendance(tenant, actor, { employee: employee.id, date: '2026-09-03', status: 'Absent' }), /ALREADY_MARKED/, 'conflicting daily attendance cannot silently overwrite evidence');
  const catalogue = laundryCatalogue(tenant); const garment = catalogue.garments[0]; const service = catalogue.services.find((candidate: any) => catalogue.prices.some((price: any) => price.garment === garment.id && price.service === candidate.id))!;
  const booking = bookLaundryOrder(tenant, actor, { customer: { name: 'Return Customer', phone: '9000000123' }, items: [{ garment: garment.id, service: service.id, qty: 1 }], expectedDeliveryDate: '2026-09-05', fulfillmentMode: 'Pickup Order', paymentMode: 'Pay Later' });
  createLaundryExpense(tenant, actor, { expenseName: 'Processing chemicals', expenseDate: '2026-09-03', amount: 10, financeCategory: 'PROCESSING', paymentMode: 'Bank' });
  store.insertRow({ id: 'tax-test-snapshot', entity: 'canonical_invoice_snapshot', tenant, status: 'Submitted', version: 1, created_by: actor, created_at: '2026-09-03T10:00:00.000Z', updated_at: '2026-09-03T10:00:00.000Z', data: { documentType: 'TaxInvoice', issuedAt: '2026-09-03T10:00:00.000Z', tax: { totals: { taxablePaise: 10_000, cgstPaise: 900, sgstPaise: 900, igstPaise: 0 } } } });
  const finance = financeCommandCenter(tenant, { from: '2026-09-03', to: '2026-09-03' });
  assert.equal(finance.current.classification.complete, true, 'executive finance only calculates a margin after every expense has a management category');
  assert.notEqual(finance.current.kpis.ebitdaPaise, null, 'executive finance produces an evidence-backed fixed-scale EBITDA bridge for classified records');
  assert.equal(finance.current.kpis.operatingCashFlowPaise, finance.current.kpis.cashInPaise - finance.current.kpis.cashOutPaise, 'executive cash flow reconciles its canonical in and out entries exactly');
  assert.equal(finance.current.unitEconomics.revenuePerOrderPaise, finance.current.kpis.netRevenuePaise, 'unit economics revenue per order is derived from the canonical net revenue');
  assert.equal(finance.forecast.state, 'RUN_RATE', 'forecast is explicitly labelled as a deterministic run-rate when posted evidence exists');
  assert.ok(finance.health.some((item: { key: string; state: string }) => item.key === 'margin' && item.state === 'Healthy'), 'financial health reports the classified margin signal');
  saveFinancePlanningTarget(tenant, actor, { periodStart: '2026-09-03', periodEnd: '2026-09-03', revenuePaise: finance.current.kpis.netRevenuePaise, collectionPaise: finance.current.kpis.collectedPaise, marginBps: 5000 });
  const plannedFinance = financeCommandCenter(tenant, { from: '2026-09-03', to: '2026-09-03' });
  assert.equal(plannedFinance.planning.state, 'CONFIGURED', 'finance planning targets are scoped to the selected period');
  assert.equal(plannedFinance.planning.metrics.find((item: { key: string }) => item.key === 'revenue')?.variance, 0, 'actual-vs-target variance reconciles in fixed paise');
  const request = requestLaundryReturn(tenant, actor, { orderId: booking.order.id, amount: 1, reason: 'Quality issue', note: 'Counter evidence' });
  assert.equal(request.returnCase.data.status, 'Requested', 'return request does not fabricate a completed refund');
  assert.equal(requestLaundryReturn(tenant, actor, { orderId: booking.order.id, amount: 1, reason: 'Quality issue' }).duplicate, true, 'same return retry does not duplicate a case');
  assert.throws(() => requestLaundryReturn(tenant, actor, { orderId: booking.order.id, amount: booking.order.grandTotal + 1, reason: 'Quality issue' }), /EXCEEDS/, 'return request cannot exceed the original order value');
  assert.equal(listLaundryReturns(tenant).length, 1, 'return case is durable and queryable');
  const financeWithReturn = financeCommandCenter(tenant, { from: '2026-09-03', to: '2026-09-03' });
  assert.equal(financeWithReturn.current.returns.cases, 1, 'finance return analytics counts the durable request without treating it as a paid refund');
  assert.ok(financeWithReturn.current.composition.services[0].orderCount >= 1, 'service economics includes order volume alongside revenue');
  assert.equal(financeWithReturn.current.tax.trend.length, 1, 'tax trend is gap-filled for every selected day');
  assert.equal(financeWithReturn.current.tax.trend[0].cgstPaise, 900, 'tax trend preserves canonical paise without applying rupee conversion twice');
  const snapshot = laundryManagementSnapshot(tenant);
  assert.equal(snapshot.ebitda.state, 'NOT_READY', 'management dashboard never invents EBITDA without classified costs');
  assert.equal(snapshot.withholding.state, 'NOT_CONFIGURED', 'TDS/TCS starts visibly unconfigured until a CA-approved policy exists');
  assert.equal(financePolicyReadiness(tenant).checks.statutoryBaseline, false, 'finance readiness does not pretend verified policies are installed');
  assert.equal(installIndia2026Baseline(tenant, actor).installed >= 8, true, 'verified India 2026 statutory policy records install once per tenant');
  assert.equal(installIndia2026Baseline(tenant, actor).installed, 0, 'statutory baseline installation is replay-safe');
  assert.equal(financePolicyReadiness(tenant).checks.statutoryBaseline, true, 'readiness recognises the versioned statutory baseline');
  assert.throws(() => saveEntityFinanceProfile(tenant, actor, { pan: 'invalid' }), /ENTITY_PAN_INVALID/, 'owner-entered PAN values are validated before storage');
  assert.throws(() => saveEntityFinanceProfile(tenant, actor, { tan: 'invalid' }), /ENTITY_TAN_INVALID/, 'owner-entered TAN values are validated before storage');
  saveEntityFinanceProfile(tenant, actor, { legalName: 'Epic Laundry Test', pan: 'ABCDE1234F', tan: 'ABCD12345E', gstRegistrationStatus: 'Registered', epfStatus: 'CoveredGeneral12', esicStatus: 'Covered', workState: 'West Bengal', marketplaceModel: 'VENDOR_SUPPLIER' });
  assert.equal(financePolicyReadiness(tenant).checks.entityConfiguration, true, 'entity-specific facts are recorded separately from statutory rates');
  const payroll = calculatePayrollPreview([{ name: 'Basic', amountPaise: 2_000_000, statutoryWage: true, taxable: true, kind: 'earning' }, { name: 'HRA', amountPaise: 1_000_000, statutoryWage: false, taxable: true, kind: 'earning' }], { epfStatus: 'CoveredGeneral12', esicStatus: 'NotCovered', taxRegime: 'NEW_2026', remainingPeriods: 12 });
  assert.equal(payroll.status, 'CALCULATED', 'configured payroll produces a fixed-scale preview');
  if (payroll.status === 'CALCULATED') assert.equal(payroll.grossEarningsPaise - payroll.employeeDeductions.totalPaise, payroll.netPayablePaise, 'employee payroll invariant reconciles exactly in paise');
  assert.equal(calculatePayrollPreview([], { epfStatus: 'Unknown', esicStatus: 'Unknown', taxRegime: 'NEW_2026' }).status, 'ESTABLISHMENT_CONFIGURATION_REQUIRED', 'payroll blocks before establishment applicability is configured');
  assert.equal(newRegimeTax2026(120_000_000).taxPaise, 0, 'resident new-regime rebate eliminates normal tax at ₹12 lakh taxable income before high-income exceptions');
  console.log('PASS  Laundry management workforce, return and finance-readiness self-test complete');
} finally { closeStore?.(); rmSync(tempDir, { recursive: true, force: true }); }
