import { randomUUID } from 'node:crypto';
import { store } from '../../kernel/store.js';
import type { EntityRow } from '../../kernel/types.js';
import { audit } from '../../kernel/audit.js';

export type SettlementLine = { code: string; label: string; amountPaise: number; direction: 'credit' | 'debit'; explanation: string };
export type MarketplaceSettlement = { id: string; externalOrderId: string; policyVersion: string; currency: 'INR'; customerCollectedPaise: number; refundPaise: number; lines: SettlementLine[]; vendorSettlementPaise: number; reconciled: true; createdAt: string };
const int = (value: unknown, label: string) => { if (!Number.isSafeInteger(value) || Number(value) < 0) throw new Error(`${label} must be non-negative integer paise`); return Number(value); };
const line = (code: string, label: string, amountPaise: number, direction: SettlementLine['direction'], explanation: string): SettlementLine => ({ code, label, amountPaise: int(amountPaise, label), direction, explanation });
export function calculateMarketplaceSettlement(input: { externalOrderId: string; policyVersion: string; customerCollectedPaise: number; refundPaise?: number; vendorServiceGrossPaise: number; vendorFundedDiscountPaise?: number; platformFundedPromotionPaise?: number; commissionBps: number; paymentFeePaise?: number; withholdingPaise?: number; adjustmentsPaise?: number }) {
  const customerCollectedPaise = int(input.customerCollectedPaise, 'customer collection'); const refundPaise = int(input.refundPaise || 0, 'refund'); const gross = int(input.vendorServiceGrossPaise, 'vendor gross'); const vendorDiscount = int(input.vendorFundedDiscountPaise || 0, 'vendor-funded discount'); const platformPromotion = int(input.platformFundedPromotionPaise || 0, 'platform-funded promotion'); const paymentFee = int(input.paymentFeePaise || 0, 'payment fee'); const withholding = int(input.withholdingPaise || 0, 'withholding'); const adjustment = Number(input.adjustmentsPaise || 0); if (!Number.isSafeInteger(adjustment)) throw new Error('adjustment must be integer paise'); if (!Number.isSafeInteger(input.commissionBps) || input.commissionBps < 0 || input.commissionBps > 10_000) throw new Error('commission must be 0..10000 basis points');
  const commission = Math.floor(gross * input.commissionBps / 10_000); const lines: SettlementLine[] = [line('VENDOR_SERVICE_GROSS', 'Vendor service gross', gross, 'credit', 'Contract service value before marketplace deductions'), line('VENDOR_FUNDED_DISCOUNT', 'Vendor-funded discount', vendorDiscount, 'debit', 'Discount responsibility assigned to vendor policy'), line('PLATFORM_FUNDED_PROMOTION', 'Platform-funded promotion', platformPromotion, 'credit', 'Promotion responsibility assigned to platform policy'), line('MARKETPLACE_COMMISSION', 'Marketplace commission', commission, 'debit', `${input.commissionBps} basis points of vendor service gross`), line('PAYMENT_FEE', 'Payment fee', paymentFee, 'debit', 'Provider fee allocated under the configured settlement policy'), line('WITHHOLDING', 'Configured withholding', withholding, 'debit', 'Tax withholding/TCS/TDS amount; legal treatment requires approved policy'), line('ADJUSTMENT', 'Approved adjustment', Math.abs(adjustment), adjustment >= 0 ? 'credit' : 'debit', 'Explicit approved settlement adjustment')];
  const vendorSettlementPaise = lines.reduce((sum, current) => sum + (current.direction === 'credit' ? current.amountPaise : -current.amountPaise), 0); if (vendorSettlementPaise < 0) throw new Error('SETTLEMENT_RECONCILIATION_FAILED');
  return { externalOrderId: String(input.externalOrderId).trim(), policyVersion: String(input.policyVersion).trim(), currency: 'INR' as const, customerCollectedPaise, refundPaise, lines, vendorSettlementPaise, reconciled: true as const };
}
export function recordMarketplaceSettlement(tenant: string, actor: string, input: Parameters<typeof calculateMarketplaceSettlement>[0]) {
  const calculated = calculateMarketplaceSettlement(input); const existing = store.rowsOf(tenant, 'marketplace_settlement').find((candidate) => candidate.data.externalOrderId === calculated.externalOrderId && candidate.data.policyVersion === calculated.policyVersion); if (existing) return existing;
  const timestamp = new Date().toISOString(); const record: EntityRow = { id: `settlement_${randomUUID()}`, entity: 'marketplace_settlement', tenant, status: 'Active', version: 1, created_by: actor, created_at: timestamp, updated_at: timestamp, data: { ...calculated, createdAt: timestamp, immutable: true } }; store.insertRow(record); audit(tenant, actor, 'marketplace:settlement-recorded', { entity: record.entity, row_id: record.id, after: { externalOrderId: calculated.externalOrderId, vendorSettlementPaise: calculated.vendorSettlementPaise, policyVersion: calculated.policyVersion } }); return record;
}
export function marketplaceSettlement(tenant: string, externalOrderId: string) { return store.rowsOf(tenant, 'marketplace_settlement').find((candidate) => candidate.data.externalOrderId === externalOrderId); }
