import { randomUUID } from 'node:crypto';
import { store } from '../../kernel/store.js';
import type { EntityRow } from '../../kernel/types.js';
import { audit } from '../../kernel/audit.js';

export type SettlementLine = { code: string; label: string; amountPaise: number; direction: 'credit' | 'debit'; explanation: string };
export type MarketplaceRefundAllocation = { allocationId: string; amountPaise: number; responsibility: 'Vendor' | 'Platform' | 'Shared' | 'PendingPolicy'; reason: string };
export type MarketplaceSettlement = { id: string; externalOrderId: string; policyVersion: string; currency: 'INR'; customerCollectedPaise: number; refundPaise: number; collectedCustomerValuePaise: number; refundAllocations: MarketplaceRefundAllocation[]; collectionLines: SettlementLine[]; lines: SettlementLine[]; vendorSettlementPaise: number; reconciled: true; createdAt: string };
const int = (value: unknown, label: string) => { if (!Number.isSafeInteger(value) || Number(value) < 0) throw new Error(`${label} must be non-negative integer paise`); return Number(value); };
const line = (code: string, label: string, amountPaise: number, direction: SettlementLine['direction'], explanation: string): SettlementLine => ({ code, label, amountPaise: int(amountPaise, label), direction, explanation });
export function calculateMarketplaceSettlement(input: { externalOrderId: string; policyVersion: string; customerCollectedPaise: number; refundPaise?: number; refundAllocations?: MarketplaceRefundAllocation[]; vendorServiceGrossPaise: number; vendorFundedDiscountPaise?: number; platformFundedPromotionPaise?: number; commissionBps: number; paymentFeePaise?: number; withholdingPaise?: number; adjustmentsPaise?: number }) {
  const customerCollectedPaise = int(input.customerCollectedPaise, 'customer collection'); const refundPaise = int(input.refundPaise || 0, 'refund'); const gross = int(input.vendorServiceGrossPaise, 'vendor gross'); const vendorDiscount = int(input.vendorFundedDiscountPaise || 0, 'vendor-funded discount'); const platformPromotion = int(input.platformFundedPromotionPaise || 0, 'platform-funded promotion'); const paymentFee = int(input.paymentFeePaise || 0, 'payment fee'); const withholding = int(input.withholdingPaise || 0, 'withholding'); const adjustment = Number(input.adjustmentsPaise || 0); if (!Number.isSafeInteger(adjustment)) throw new Error('adjustment must be integer paise'); if (!Number.isSafeInteger(input.commissionBps) || input.commissionBps < 0 || input.commissionBps > 10_000) throw new Error('commission must be 0..10000 basis points');
  const refundAllocations = (input.refundAllocations || []).map((allocation) => ({ allocationId: String(allocation.allocationId || '').trim(), amountPaise: int(allocation.amountPaise, 'refund allocation'), responsibility: allocation.responsibility, reason: String(allocation.reason || '').trim() }));
  if (refundAllocations.some((allocation) => !allocation.allocationId || !allocation.reason || !['Vendor', 'Platform', 'Shared', 'PendingPolicy'].includes(allocation.responsibility)) || new Set(refundAllocations.map((allocation) => allocation.allocationId)).size !== refundAllocations.length) throw new Error('SETTLEMENT_RECONCILIATION_FAILED');
  if (refundPaise > customerCollectedPaise || (refundPaise > 0 && refundAllocations.length === 0) || refundAllocations.reduce((sum, allocation) => sum + allocation.amountPaise, 0) !== refundPaise) throw new Error('SETTLEMENT_RECONCILIATION_FAILED');
  const collectedCustomerValuePaise = customerCollectedPaise - refundPaise;
  const collectionLines: SettlementLine[] = [line('CUSTOMER_COLLECTION', 'Customer amount collected', customerCollectedPaise, 'credit', 'Provider or immutable cash collection evidence'), line('CUSTOMER_REFUND', 'Customer refund', refundPaise, 'debit', 'Approved refund allocation against collected customer value')];
  const commission = Math.floor(gross * input.commissionBps / 10_000); const lines: SettlementLine[] = [line('VENDOR_SERVICE_GROSS', 'Vendor service gross', gross, 'credit', 'Contract service value before marketplace deductions'), line('VENDOR_FUNDED_DISCOUNT', 'Vendor-funded discount', vendorDiscount, 'debit', 'Discount responsibility assigned to vendor policy'), line('PLATFORM_FUNDED_PROMOTION', 'Platform-funded promotion', platformPromotion, 'credit', 'Promotion responsibility assigned to platform policy'), line('MARKETPLACE_COMMISSION', 'Marketplace commission', commission, 'debit', `${input.commissionBps} basis points of vendor service gross`), line('PAYMENT_FEE', 'Payment fee', paymentFee, 'debit', 'Provider fee allocated under the configured settlement policy'), line('WITHHOLDING', 'Configured withholding', withholding, 'debit', 'Tax withholding/TCS/TDS amount; legal treatment requires approved policy'), line('ADJUSTMENT', 'Approved adjustment', Math.abs(adjustment), adjustment >= 0 ? 'credit' : 'debit', 'Explicit approved settlement adjustment')];
  const vendorSettlementPaise = lines.reduce((sum, current) => sum + (current.direction === 'credit' ? current.amountPaise : -current.amountPaise), 0); if (vendorSettlementPaise < 0) throw new Error('SETTLEMENT_RECONCILIATION_FAILED');
  const collectionEquation = collectionLines.reduce((sum, current) => sum + (current.direction === 'credit' ? current.amountPaise : -current.amountPaise), 0); if (collectionEquation !== collectedCustomerValuePaise) throw new Error('SETTLEMENT_RECONCILIATION_FAILED');
  return { externalOrderId: String(input.externalOrderId).trim(), policyVersion: String(input.policyVersion).trim(), currency: 'INR' as const, customerCollectedPaise, refundPaise, collectedCustomerValuePaise, refundAllocations, collectionLines, lines, vendorSettlementPaise, reconciled: true as const };
}
export function recordMarketplaceSettlement(tenant: string, actor: string, input: Parameters<typeof calculateMarketplaceSettlement>[0]) {
  const calculated = calculateMarketplaceSettlement(input); const existing = store.rowsOf(tenant, 'marketplace_settlement').find((candidate) => candidate.data.externalOrderId === calculated.externalOrderId && candidate.data.policyVersion === calculated.policyVersion); if (existing) return existing;
  const timestamp = new Date().toISOString(); const record: EntityRow = { id: `settlement_${randomUUID()}`, entity: 'marketplace_settlement', tenant, status: 'Active', version: 1, created_by: actor, created_at: timestamp, updated_at: timestamp, data: { ...calculated, createdAt: timestamp, immutable: true } }; store.transaction(() => { store.insertRow(record); for (const allocation of calculated.refundAllocations) store.insertRow({ id: `settlement_refund_${allocation.allocationId}`, entity: 'marketplace_refund_allocation', tenant, status: 'Active', version: 1, created_by: actor, created_at: timestamp, updated_at: timestamp, data: { ...allocation, externalOrderId: calculated.externalOrderId, settlementId: record.id, immutable: true } }); }); audit(tenant, actor, 'marketplace:settlement-recorded', { entity: record.entity, row_id: record.id, after: { externalOrderId: calculated.externalOrderId, vendorSettlementPaise: calculated.vendorSettlementPaise, policyVersion: calculated.policyVersion, refundAllocations: calculated.refundAllocations.length } }); return record;
}
export function marketplaceSettlement(tenant: string, externalOrderId: string) { return store.rowsOf(tenant, 'marketplace_settlement').find((candidate) => candidate.data.externalOrderId === externalOrderId); }
export function recordMarketplaceCashCollection(tenant: string, actor: string, input: { collectionId: string; externalOrderId: string; amountPaise: number; method: 'CashOnPickup' | 'CashOnDelivery'; collectedBy: string; evidence: string }) {
  const amountPaise = int(input.amountPaise, 'cash collection'); if (!input.collectionId || !input.externalOrderId || !input.collectedBy || !input.evidence || !['CashOnPickup', 'CashOnDelivery'].includes(input.method)) throw new Error('CASH_COLLECTION_INVALID'); const existing = store.rowsOf(tenant, 'marketplace_cash_collection').find((candidate) => candidate.data.collectionId === input.collectionId); if (existing) return existing; const timestamp = new Date().toISOString(); const row: EntityRow = { id: `cash_collection_${input.collectionId}`, entity: 'marketplace_cash_collection', tenant, status: 'Active', version: 1, created_by: actor, created_at: timestamp, updated_at: timestamp, data: { ...input, amountPaise, state: 'Collected', collectedAt: timestamp, immutable: true } }; store.insertRow(row); audit(tenant, actor, 'marketplace:cash-collected', { entity: row.entity, row_id: row.id, after: { collectionId: input.collectionId, externalOrderId: input.externalOrderId, amountPaise, method: input.method } }); return row;
}
